### ISSUE TITLE
emcc not accepting -O20 like gcc

### ISSUE THREAD

**Issue by abergmeier** [kripken/emscripten#1499]
Some autoconf scripts use a excessive opt level to select the highest available.
This seems to work for _gcc_, but does not for _emcc_. Here the `config.log` of the tests

```
configure:12229: checking if /home/andreas/Projects/emscripten/emcc accepts -Wdeclaration-after-statement
configure:12244: /home/andreas/Projects/emscripten/emcc -o conftest -O20 -ffast-math -mno-ieee-fp -D_REENTRANT -fsigned-char -Wdeclaration-after-statement   conftest.c  >&5
clang: warning: argument unused during compilation: '-mno-ieee-fp'
error: invalid value '20' in '-O20'
configure:12244: $? = 1
configure: failed program was:
| /* confdefs.h */
| #define PACKAGE_NAME "libvorbis"
| #define PACKAGE_TARNAME "libvorbis"
| #define PACKAGE_VERSION "1.3.3"
| #define PACKAGE_STRING "libvorbis 1.3.3"
| #define PACKAGE_BUGREPORT "vorbis-dev@xiph.org"
| #define PACKAGE_URL ""
| #define PACKAGE "libvorbis"
| #define VERSION "1.3.3"
| #define STDC_HEADERS 1
| #define HAVE_SYS_TYPES_H 1
| #define HAVE_SYS_STAT_H 1
| #define HAVE_STDLIB_H 1
| #define HAVE_STRING_H 1
| #define HAVE_MEMORY_H 1
| #define HAVE_STRINGS_H 1
| #define HAVE_INTTYPES_H 1
| #define HAVE_STDINT_H 1
| #define HAVE_UNISTD_H 1
| #define HAVE_DLFCN_H 1
| #define LT_OBJDIR ".libs/"
| /* end confdefs.h.  */
| #include <stdio.h>
| int
| main ()
| {
| puts("Hello, World!"); return 0;
|   ;
|   return 0;
| }
```

I could not yet find where `invalid value` is output by code.

**Comment by juj** [comment]
The support for `-O20` was added in #5520. Love how one guy's arbitrary idea to do a `-O20` sweeps through affecting the whole industry, seen this in the past years in a number of other libraries (CMake, Clang, Visual Studio, ...). In any case, Emscripten is now `-O20` compatible as well, so  this can be closed.

Btw, I have recently authored CMake build scripts for Ogg and Vorbis, since I prefer building projects with that build system in many cases. These can be found at https://github.com/juj/ogg and https://github.com/juj/vorbis respectively.
