### ISSUE TITLE
Lower garbage creation

### ISSUE THREAD

**Issue by ArwedSchmidt** [kripken/emscripten#2299]
When developing games with Emscripten, one of the big issues with Emscripten is that it still creates garbage so the GC kicks in every once in a while - even if your own code is non-garbage (object pools, no temporary variables except for HEAP stuff, etc. pp.).

Still Emscripten generates code that is forcing GC to kick in. This is likely caused by two things, I can see:
- Internal functions like Array.slice, Array.splice, Function.bind - all of those create garbage and should be avoided in any loop running. 
- Function returns create temporary variables; it would be possible to optimize that to use the HEAP[] all the time.

I am developing WebGL / SDL Stuff via Emscripten - Windows 7 64-bit, Visual Studio 2010.

**Comment by juj** [comment]
Let me close this issue. We are generally very interested in removing unnecessary allocations everywhere in code, and routinely do so when we see such opportunities, e.g. see recent #2596, #3132, #2905 is an example, but the way this bug report is laid out, it's more a "mission" rather than a specific bug to correct. Feel free to open new bug reports with concrete code snippets where memory is allocated and does not need to. Pull requests are also welcome.
