### ISSUE TITLE
Unresolved symbols when using emscripten::val

### ISSUE THREAD

**Issue by orangebandit** [kripken/emscripten#2372]
I modified the example code from https://github.com/kripken/emscripten/wiki/embind,
```
#include <emscripten.h>
#include <emscripten/bind.h>
using namespace emscripten;
int main() {
        val xhr = val::global("XMLHttpRequest").new_();
        xhr.call<void>("open", std::string("GET"), std::string("http://url"));
        return 0;
}
```
When compiling, I get
```
$ em++ --bind emval.cpp -o emval.html
warning: unresolved symbol: _emval_get_method_caller
warning: unresolved symbol: _emval_run_destructors
warning: unresolved symbol: _embind_register_bool
warning: unresolved symbol: _emval_new
warning: unresolved symbol: _embind_register_integer
warning: unresolved symbol: _emval_decref
warning: unresolved symbol: _embind_register_emval
warning: unresolved symbol: _embind_register_std_string
warning: unresolved symbol: _embind_register_void
warning: unresolved symbol: _emval_call_method
warning: unresolved symbol: _embind_register_memory_view
warning: unresolved symbol: _embind_register_float
warning: unresolved symbol: _embind_register_std_wstring
warning: unresolved symbol: _emval_get_global
```
And when I browse to emval.html, nothing happens. No errors according to the web console, nothing. What am I doing wrong?

**Comment by TurkeyMan** [comment]
I'm having this same problem... and at runtime, this: `missing function: _emval_get_global`
Since that's the very first thing I do, nothing more works from there on.

**Comment by iboB** [comment]
@TurkeyMan: you should add "--bind" to the linker options

**Comment by chadaustin** [comment]
@waywardmonkeys This is fixed now, right?

**Comment by waywardmonkeys** [comment]
@chadaustin Yes. It feels like a decade, but I guess just last year!

**Comment by iamjustadd** [comment]
sir, I got such problem currently. While using different version emscripten to compile our project.
It works well in emsdk2.0.0, but show undefined symbols **Error** In 2.0.10.
The Error log is:
error: undefined symbol: _emval_as (referenced by top-level compiled C/C++ code)
warning: Link with `-s LLD_REPORT_UNDEFINED` to get more information on undefined symbols
warning: To disable errors for undefined symbols use `-s ERROR_ON_UNDEFINED_SYMBOLS=0`
warning: __emval_as may need to be added to EXPORTED_FUNCTIONS if it arrives from a system library
error: undefined symbol: _emval_run_destructors (referenced by top-level compiled C/C++ code)
warning: __emval_run_destructors may need to be added to EXPORTED_FUNCTIONS if it arrives from a system library
error: undefined symbol: _emval_take_value (referenced by top-level compiled C/C++ code)
warning: __emval_take_value may need to be added to EXPORTED_FUNCTIONS if it arrives from a system library
Error: Aborting compilation due to previous errors
em++: error: '/emsdk/node/12.18.1_64bit/bin/node /emsdk/upstream/emscripten/src/compiler.js /tmp/tmpaphk0ngd.txt' failed (1)
what happed to newer emscripten , how can i fix such problesm .
Thank you.
