### ISSUE TITLE
Use all of musl libc, including stdio, porting it by implementing syscalls

### ISSUE THREAD

**Issue by kripken** [kripken/emscripten#2701]
See initial discussion in the second half of #2658.

**Comment by kripken** [comment]
Was there any progress on this?

I've started a quick experiment of my own yesterday, `musl-emscripten` branch in emscripten plus https://github.com/kripken/musl-emscripten . The idea is to explore the idea of a from-scratch port of musl, with minimal changes (we do still need to modify things like `sbrk`, syscalls aren't enough), and overall trying to do everything through the linux syscall interface that musl uses.

Not sure if this will go anywhere, it's mostly for my own curiosity for now. I'm wondering what code size and perf will be.

cc @juj

**Comment by nickdesaulniers** [comment]
What happens if someone tries to port code that is making BSD syscalls?  The numbers are different between Linux and BSD and some exist in one but not the other!  So Emscripten picks Linux ones, and BSD syscalls (hopefully) fail?

**Comment by kripken** [comment]
Well, we would implement linux syscalls, and our libc would use those syscalls. If someone else implemented a libc that uses other syscalls, they'd need to implement those.

**Comment by nickdesaulniers** [comment]
And if someone is calling `int syscall (int number, ...)` from their C/C++ code?

I mean, at that point, you shouldn't hope for any portability.  The issue I see is that if they're implemented as Linux syscalls, any code that assumes BSD sockets won't necessarily fail outright if say one Linux syscall number has the same function signature as a different BSD syscall.

**Comment by kripken** [comment]
Yes, we can't hope for portability there. Anyone calling `syscall` would either rely on our syscalls being linux, or need to write their own.

**Comment by kripken** [comment]
I got hello world to work using musl+syscalls.

Compared to normal emscripten, `-O0` hello world goes from 370829 bytes to 561338 bytes, which is 50% bigger. The difference is due to musl's `printf_core` method, 3650 lines, versus 406 for emscripten's JS replacement for printf.

**Comment by kripken** [comment]
Building musl with `-Os` instead of `-O2` reduces `printf_core` to 2025 lines, and overall code size decreases to 525881 bytes. Still 40% larger than before.

**Comment by kripken** [comment]
Removing some no-longer pieces of js code for i64 printing, hello world goes to 471109 bytes, which is 25% larger than before.

**Comment by socketpair** [comment]
Very GOOD! The invetigation job was started due to lack of timer-related functions...i.e. SIGALRM support. This is required for some software (like qemu). I have a dream to compile QEMU using emscripten...

**Comment by juj** [comment]
Interesting! I pondered a while back about implementing syscalls, first when adding the musl sprintf et al, and later when implementing the musl pthreads. But then I figured that it might not be the nicest solution, since the syscall will be a big switch-case, and I'm not sure if Clang is able to dead code eliminate any unused cases out from the syscall, so it will have all the cases in it even if those would be unused? This might also bias the code size to look small initially when only a few syscalls are implemented/needed, but when more of those are added, it will increase the size of all code, even the ones that don't use all the syscalls? Or I wonder if LLVM might have an optimization pass that does flow analysis to switch-cases (and other code) to optimize out unused paths? Though I doubt it, since it sounds like an extremely complex problem, and it's easy for user code to accidentally kill that optimization opportunity if one passes a dynamic variable that can't be reasoned about instead of a constant.

For the futex API in the pthreads branch, I felt that the syscalls did not quite match 1:1 the futex operations in the JS spec, so I found it simpler and much more descriptive to just #ifdef the Emscripten specific parts. Perhaps for the asm.js filesystem though this might be useful?

**Comment by socketpair** [comment]
1. There is no requiements to implemnt big switch-case. `_syscallN` is a C macro (http://man7.org/linux/man-pages/man2/_syscall.2.html), so, we can convert `_syscall5(42,b,c,d,e)` to, say `asmjs("javascript_function_42(b,c,d,e)")` or so.

2. LLVM optimizer is VERY clever, especially when it know that no one can call functions from places other than it knows.

3. Futex, pthreads and so on can not be implemented, since it is not possible to implement shared data between web workers...Instead, we can emulate threads by soft-switching tasks using event-loop. I mean:

* make synchronous blocking syscalls  asynhronous, like `read()`,  `write()`, `futex()`. I mean we should be able to execute some code and return to userspace when operation complete.
* break long-executable threads (byte timer) to implement non-voluntary context switch.
* switch threads when some thread is calling some syscalls (especially blocking). so-called voluntary context switch.

After that any application can work, but unfortunatelly use only one CPU.

**Comment by kripken** [comment]
Yes, we could statically turn syscalls into direct calls, as I think they are never dynamic in musl. So `syscall(SYS_open, ..) => syscall_SYS_open(..)`. But my current experiment implements syscalls on the JS side, however - we'll see if it is an issue or not. So far there is a switch for now, but code size isn't so bad, mostly each switch case just calls directly into `FS.operation()`, e.g.

````
        case 83: { // SYS_symlink
          var target = get(), linkpath = get();
          FS.symlink(Pointer_stringify(target), Pointer_stringify(linkpath));
          return 0;
        }
````

**Comment by socketpair** [comment]
@kripken you previously say that code will become large. What about performance? I afraid, that after going to syscall-based emscripten, code base will reduced, affecting performance, since many functions will be implemented in llvm instead of native js. On other hand, this may be faster since asmjs is not always works and native js may be slower.

One new idea - is to implement syscalls and reimplement (in future) some musl libc functions in native js over implemented syscalls. Moreover, it may be switchable during linking phase. This may be required if one should switch between performance and compatibility.

**Comment by kripken** [comment]
Overall code size increased - the syscall implementation in JS itself is smaller, but we now use more musl code, which is larger than the code it replaces (which was in JS).

**Comment by socketpair** [comment]
I mean js code base (on github)  reduced. But question about performance is still actual.

**Comment by socketpair** [comment]
http://codemonkey.org.uk/projects/trinity/ - good project to test syscalls, since we will implement them.

**Comment by kripken** [comment]
Ok, I believe I have the test suite passing in the `musl-syscalls` branch (can test that using the incoming branches in the other repos). That basically replaces almost all our libc code with musl, and musl uses syscalls which we implement.

I ended up not using all of musl. One issue is DNS - all the `gethost*` methods open sockets, look at resolv.conf, etc. etc., when on the web we just want to use normal URLs and let the browser handle that. So I am not building those. Another issue is math functions - I kept us using the same `Math.*` methods we were using before (so I didn't add musl sin.c, etc.). Still, that means we use almost all of musl. In particular we now use the musl stdio stuff for printf, files, and so forth.

Overall the experiment went well. I didn't run into serious issues integrating with the JS filesystem code. So some of my worries have been shown not to be a problem. However, there are still some isuses with the syscall approach, that we should consider before deciding whether or not to merge. Here are the **downsides**:

* First, code size is affected. Hello world is significantly larger (50%), but the difference shrinks in optimized builds (20%):

|                 | before  | after   |
|-----------------|---------|---------|
| hello world -O0 |  371848 |  549729 |
| hello world -O2 |  157992 |  188409 |
| hello world -O3 |  156525 |  186816 |
| libc++ -O0      | 2266828 | 2263532 |
| libc++ -O2      |  535384 |  530145 |
| libc++ -O3      |  508752 |  503411 |

Luckily the difference basically vanishes in larger programs, like one using libc++ in the lower 3 lines there.

* Compilation times are slower for small programs, that might not have linked in libc before, but now must do so even for printf in hello world. 55% slowdown to build hello world - but the total time is still very small, of course. On large projects, there shouldn't be a difference. (It will slow down our test suite and bots, though, which build lots of small programs.)

* One concern is bugs in musl. Our test suite found one, ungetc on EOF, which they confirmed but I didn't check if they fixed it yet. There might be others.

* musl is also stricter, it disallows `printf("%Ld")` for example. We tolerated things like that when we saw glibc did. musl is right according to the spec, but this might break existing code - it required changes in the test suite. This is basically like porting to a new libc; musl is very good and very accurate in following the spec, but still, it is a change that will annoy some people.
 
* musl also does less error checking than we did - for example, a musl method receiving a `FILE*` will assume it is valid, and just operate on it. In our code, we did it all in safe JS, so we got an error on invalid input. musl is correct to do so, but we are losing some amount of error checking here.

* musl has some minor output differences than us and glibc, like what to print for a null `%p`, or some corner cases of float printing. Those might be a surprising change to some people, but both should be correct per the spec.

* musl triggered an LLVM LTO bug. Not musl's fault, but a large libc change like this may cause other breakages.

Now for the **upsides**:

* The syscall interface is smaller than the previous one. This makes it simpler to reason about. It can also make things like pthreads and signals simpler - fewer things to proxy to the main thread, just the syscall interface itself, mostly. Going forward, having a simpler libc implementation is probably a very good thing.

* musl code fixes a bunch of bugs in our libc code, and probably more we aren't aware of. It also makes a bunch of things faster, like printf, which generally don't matter but sometimes do.

* More generally, performance is hard to measure. There are reasons to suspect improvements or slowdowns (more ffi calls from asm.js in some cases, less in others). As one random thing, BananaBench does quite a lot of file IO, and it shows no significant change.

**Summary**: Merging this branch in has large advantages but also significant disadvantages. Very interested to hear what people think about this. Let's consider this carefully before making a decision either way.

(The only thing I feel strongly about is that we not support **two** libc options here.)

**Comment by NWilson** [comment]
I think it's generally a very good idea to use more rather than less of musl. Moving to a platform which is a bit less "weird" than the mostly-JavaScript libc, plus the reduction in maintained code, should make it easier to maintain.

The fact that musl is stricter than glibc is fine for us, we already support Android bionic libc, and Solaris/FreeBSD/MacOS libc as well, I wouldn't anticipate problems for us that we haven't already caught.

I have to admit, we're gradually using more of own JavaScript libraries, to try and keep our own low-level classes more similar on the different platforms. We've now got about thirty JS libraries in our build tree which try and leverage the browser more than emscripten's libc does currently (for example, with localisation support that we need). Moving to musl might be good for us if we can cut back on that a bit over time.

At some point, it would probably be worth going over each function library.js being replaced with musl, and doing a mental check whether moving to musl provides the same functionality. I'm thinking for example of the timezone handling code I contributed to library.js which uses the browser's timezone database to handle DST, whereas at best musl presumably builds in its own database which will get out of date. There's still justification for keeping home-grown implementations of certain bits of functionality like that, not just doing things through syscalls.

**Comment by kripken** [comment]
Good points. I should have given more detail - there are a few other pieces of musl not being used, including the `time/` methods. I think it does make sense to keep using that timezone code you mention and contributed. For example I would guess the browser detects the system timezone info and uses that, which is probably what users want.

Full list of parts of musl not used is at https://github.com/kripken/emscripten/blob/musl-syscall/tools/system_libs.py#L98 . Most are things we can't support, like signals (yet?) and setjmp (we support a subset, ourselves).

**Comment by kripken** [comment]
Assuming we decide to merge this in, I'll go through `library.js` and make sure about each thing that is being removed (I didn't do it yet because if we don't merge, it's pointless; also it depends on me merging latest incoming with all the pthreads updates there).

**Comment by waywardmonkeys** [comment]
> musl triggered an LLVM LTO bug. Not musl's fault, but a large libc change like this may cause other breakages.

Which one?

I've previously identified and created a minimized test case for an LTO bug triggered by musl code and it has been fixed on LLVM master.

**Comment by floooh** [comment]
Any idea why libc++ becomes slightly smaller with musl? I think it's a good decision. I wanted to complain about printf code bloat, but if it's around 30kByte for optimized builds that sounds ok (did you also check gzipped?).

**Comment by socketpair** [comment]
> Full list of parts of musl not used is at https://github.com/kripken/emscripten/blob/musl-syscall/tools/system_libs.py#L98 .

Can you verticalize list? I mean

```
blacklist = {
    'ipc', 'passwd', 'thread', 'signal', 
    'sched', 'ipc', 'time',
   ...
}
```
or even one module at list. this will simplify reviewing changes in that line....

**Comment by aidanhs** [comment]
I can't decide if I like this or not. The advantages have been covered comprehensively above.

My hesitation comes when considering the motivating idea of moving the boundary between vanilla and asm to a lower level. My (personal) conceptual view of emscripten is that it takes some input and produces output you can call from within JS. asm.js is just a convenient vehicle for this - from a very big picture point of view, I would be totally happy with emscripten recognising a cwrap around some C code that returns the base64 of a string and 'optimises' it all to `btoa` (obviously this is far fetched, hopefully you get the idea).

By contrast, by using musl you (in my mind) move away from the above and towards a posix compatibility layer/VM concept. Which isn't a bad thing in itself! I just think it needs to be a deliberate decision.

I think the former is useful for compiling libraries, the latter for applications. If applications are the main consumer of emscripten...seems like a reasonable choice.

**Comment by juj** [comment]
Absolutely great job Alon for doing such a large body of work so quickly, it is impressive! Though I must admit I'm not sure how I feel about this route. I think the greatest benefit here would be the ability to emulate compilation of native code that does depend directly on syscalls itself. Apart from that, I see some downsides that I feel really uncomfortable about:

  - The major thing is that after this, Emscripten would be "advertising" to be Linux syscall compliant, however I think that is not as well specified interface compared to the higher level C runtime and companion apis. Using syscalls does not remove the need for pthreads proxying and like mentioned above, we would migrate to proxying syscalls (343 items in switch-case), instead of proxying C functions (136 items in switch-case). Also, not all syscalls need to be proxied, and proxying some would be outright harmful/wrong (e.g mutex operation), so the logic would need to be considerably more intelligent than that. My thought was to gradually remove the need of proxying altogether by migrating to implement more things in asm.js directly, VFS being the first target, and this seems to go to the opposite direction of that plan, and take us to a path where we would be proxying more things instead of removing it.

  - The syscalls are currently implemented in JS, which is not ideal, it would be better to have it implemented in asm.js to avoid performance issues when crossing the boundary. If there's state being preserved that should be process global to all threads, having the implementation in JS would mean more proxying instead of less.

  - The syscall switch-case at https://github.com/kripken/emscripten/compare/incoming...musl-syscall#diff-90cd3df61c63a416e21c328f86078932R585 has the same problem that the current pthreads proxying switch case has at https://github.com/kripken/emscripten/blob/incoming/system/lib/pthread/library_pthread.c#L252 , in that it is a large switch-case that is effectively non-dead code eliminatable. It was mentioned before that it might be possible to prohibit the generic `syscall()` api and only allow a compile-time `syscall_n() `to choose which syscall to invoke, but that would go against the benefit of emulating support for existing code, in case that might do a generic syscall.

  - Getting us more musl is a great benefit. If we don't care about user code depending on syscalls, and only want more musl, I think it would work better if we take a arch-specific approach inside musl directly and implemented the alternative paths to avoid syscalls (or implement the few `syscall_n()` in arch specific directory) there and submitted those to upstream musl as well. That approach feels like a tighter fit where the code would be implemented in asm.js and not need proxying as much. I think that would be simpler and more flexible, as some of the syscalls only need a oneliner change like here: https://github.com/kripken/emscripten/blob/incoming/system/lib/libc/musl/src/internal/pthread_impl.h#L136 , or in some cases we need more complex added logic that doesn't map to a syscall, like here: https://github.com/kripken/emscripten/blob/incoming/system/lib/libc/musl/src/thread/__timedwait.c#L37 .

Perhaps we could do the most interesting syscall_n()s internally in musl arch-specific directories in asm.js, without the large switch-case table, if the goal is to keep musl clean from `#ifdef __EMSCRIPTEN__` blocks as much as possible? For the proposed approach, I think the greatest benefit of this would be to support `syscall()` emulation for existing applications?

**Comment by kripken** [comment]
@waywardmonkeys : https://llvm.org/bugs/show_bug.cgi?id=23814

@floooh : Regarding gzipped sizes, I checked now:

|                 | before  | after   |
|-----------------|---------|---------|
| hello world -O3 |  43283 |  52100 |
| libc++ -O3      | 123693 | 120398 |

But actually both those numbers and the previous are a little misleading, since I forgot the mem init file. Taking that into account, the gzipped mem init size is 3174 before, and 4451 after. Which shrinks the gap, but does not change it. Some of the musl printf logic is actually in table format (state machine), which could explain part of that.

Another reason why libc++ after might be smaller is that we had some duplication between JS and compiled libc code, actually, like some printf support code. After, it is just in libc.

@socketpair : i split it up into sections now, each on its own line. individual lines are still fairly long, though.

@aidanhs : I agree it's a significant change in the approach, very good point. Just for libc though - this wouldn't limit libraries in general from being ported. Unless I missed something you meant there?

@juj In general, I don't think we have an either-or decision here. Almost all the syscalls I implemented are for files and networking, which must be done in JS; for pthreads and signals, if we can implement them in C, perhaps it is better to not do them using the syscall interface. Most musl ports don't ifdef like in your last link, but if that is best for us, it sounds fine to me.

I guess the reason this issue has the general framing is that I started it before pthreads landed :) Before that, almost all syscalls are files and networking, which calls into JS immediately.

Another distinction is that the file and networking syscalls need to be proxied, while pthreads do not, as you mention. Which is another possible reason for using syscalls for most of libc, but leaving some things like pthreads and signals to a higher libc level.

Some other notes regarding your comments:

 * Regarding the syscall interface being more or less specified compared to libc, in one sense yes, but in another, actually most syscalls have simple one-line libc wrappers (I was surprised to learn this). Overall lack of docs has not been an issue. But what is definitely clear is that the syscall API surface is much smaller than libc.
 * I don't think we need to support generic syscalls - just musl's usage of syscalls. It has only static ones. But yes, this is not friendly to code elimination, without extra work. Right now, using one syscall pulls in code for them all. That causes the code size downside in hello world, as shown above - but it basically vanishes in larger projects.

**Comment by socketpair** [comment]
Seems, I have found a bug :) unfortunatelly some stupid programs use `p?read*()`/`p?write*()` functions (and also this mean corresponding syscalls) over sockets instead of `recv*()`/`send*()`. Moreover, some syscalls should return error if tried to use over inappropriate FD, like `seek()` over socket/pipe/terminal(?) or, say, `fchmod()` over socket.

So, we should check FD type in every FD-oriented syscall implementation. I have found various approach in different syscall implementations in sources of `musl-syscall` branch. The Linux kernel maps FD to some structure that have fields=function-pointers for all FD-operations, thus FD-type checking is not even required. If operation is not defined in that structure => EINVAL. So, sockets will not define `seek` operation for example, but define `write`. Seems we should copy that semantics.

Also, we may reduce syscall list by using new, universal ones instead of old and plain. I mean calling `dup3()` (with special flags) while implementing `dup2()`. We can call `readv()` internally when implementing `read()`, `accept4()` instead of `accept()` and so on.

As mentioned earlier, we should not try to implemented interface of syscalls available to user, since application that require specific syscall (and opposed to libc function) is really NOT portable.

**Comment by kripken** [comment]
I am not sure I understood the problem. The code should handle FDs of both files and sockets, but definitely bugs are very likely. Do you have a testcase or testcases showing the issue?

**Comment by socketpair** [comment]
Sorry, I have not very deep dived into the source code... I thought that `FS.write` is related only to file system....

Have you check this branch using https://github.com/kernelslacker/trinity  ( http://codemonkey.org.uk/projects/trinity/) ?

**Comment by aidanhs** [comment]
@kripken yes, it doesn't limit library porting. You actually touch on what I was trying to say in your post:

> this is not friendly to code elimination, without extra work. Right now, using one syscall pulls in code for them all. That causes the code size downside in hello world, as shown above - but it basically vanishes in larger projects.

i.e. if have some code in C you want to expose as a small(ish) library in JS, moving to musl is unfriendly. But bigger apps benefit from the more robust library code. Hence my statement: "I think the former is useful for compiling libraries, the latter for applications."

**Comment by kripken** [comment]
@socketpair : syscall fuzzing sounds interesting, but probably only a lot later, when things are otherwise complete and solid (and that's assuming we decide to land this)

@aidanhs : i see, ok. yes, for quite small libraries this makes things worse. unless we implemented some optimization to find out which syscalls were actually used, and eliminate the rest.

**Comment by juj** [comment]
`Almost all the syscalls I implemented are for files and networking, which must be done in JS`

`Another distinction is that the file and networking syscalls need to be proxied...`

I agree there is a lot of functionality that must be done in JS land, and a lot of those calls need to be proxied. But I feel that drawing that JS vs asm.js & proxying boundary to the `syscall()` function is not a nice fit. In general I would favor that we'd expose the various JS-specific APIs in their "purest" form as small functions of their own. For filesystem, this would be XHRs and IndexedDB, and I think the way we expose those with `emscripten_wget_...` and `emscripten_idb_...` would be a good way, and then all the higher logic could then be implemented directly in C, like the file system hierarchy and so on, which would be very generic C code. Since both XHRs and IndexedDB is available to workers, I believe we shouldn't need to proxy anything related to the filesystem, and it should be possible to implement our VFS pretty much fully in C code?

For the misc non-VFS -related syscalls, I like the function `emscripten_get_now()` how it exposes one very small thing, and we could have similar functions for exposing different time and locale specific logic. For any stateless calls, this feels like the most ideal form, and if that function call would need to be proxied, we would choose to do so directly inside that `emscripten_...()` function call. For other JS APIs that need to retain JS objects as state, such as networking, we could have small functions that expose the different websockets and webRTC related calls as `emscripten_websockets_...` and similar, and have the JS<->C object mapping tables in those libraries, like we do for GL.

This scheme would have the advantage that people who want to directly call the 1:1 mapped browser functionality can do so by invoking the various `emscripten_...` functions, and those that are not used, will get dead code eliminated away. Also it will ensure the fewest amount of code in JS land, and least amount of state retained in JS land, which helps pthreads to proxy less.

If we want to be very musl-friendly without #ifdefs inside the code, we could do specific individual `syscall_n()` functions (either in JS or C, depending on which one makes more sense), and for those larger #ifdef blocks, we could move the implementation of those files into the `musl/arch/js/` directory. If musl never calls into `syscall()`, but always to `syscall_n()`, then perhaps we could implement the latter, and then have the flexibility to choose at a basis of individual functions whether to implement that in C or in JS, and whether it needs proxying or not. Overall, the big junction table in JS side is the thing that scares me the most.

**Comment by kripken** [comment]
I am in favor of `emscripten_*` APIs that expose individual atomic functionalities. However, regarding

> it should be possible to implement our VFS pretty much fully in C code?

Possible, but it would be a big change, a lot of work, and no longer would the filesystem be easily hackable and extensible from JS.

In other words, I am in favor of `emscripten_*` APIs, but not necessarily implementing everything in terms of them.

> Overall, the big junction table in JS side is the thing that scares me the most.

A simple solution to that is to have the backend note which syscalls are called, then build only the parts of the syscall interface that are needed. Other solutions include header changes like you suggest, although we would need to verify that they can be done in the `arch/` dir without hacking up the rest of musl. In general, I think we can get rid of the big switch in JS, one way or another.

**Comment by kripken** [comment]
Discussing this with @juj, he agrees we can merge this, assuming we avoid the big monolithic switch and its code-size downsides. I think that would address all the concerns raised here, or did I forget something?

Currently I am merging `incoming` into `musl-syscalls`. This requires supporting pthreads, which landed on incoming since I finished the first prototype of syscalls. I believe i have that all working now, so the next thing is to look at the code size issue.

**Comment by kripken** [comment]
I converted musl to use static syscalls, that is, `syscall(54, ..)` turns into `syscall54(...)`. This means we can statically analyze it at compile time, and we no longer have a big switch with all possible syscalls all the time.

A downside is that dynamically doing a syscall is no longer possible. I had to remove the `syscall()` libc method, for example, and a few others like `set*id()`, but I believe nothing of importance was lost.

Here is where we stand on code size now:

|                 | incoming  | syscalls   | incoming gzipped | syscalls gzipped |
|-----------------|---------|---------|----------------|---------------|
| hello world -O0 |  393934 |  523827 |          90621 |        115431 |
| hello world -O3 |  157036 |  156690 |          43387 |         43903 |
| libc++ -O0      | 2645665 | 2560150 |         420046 |        397903 |
| libc++ -O3      |  522956 |  486231 |         126553 |        117387 |
| BananaBread     | 4712497 | 4694013 |        1071785 |       1068887 |

(syscalls is the musl-syscalls branch; all measurements of optimized builds include the mem init file)

On hello world at -O0 we lose, like in previous measurements (before static syscalls). On optimized hello world we are now about the same as incoming, which is an improvement from before. On larger codebases like libc++ and BananaBread, we do quite well - a little better at -O0, and significantly better on optimized builds, 7% smaller on libc++, with or without gzip.

Overall, then, it looks like merging this branch will actually improve code size, on everything but unoptimized hello world. The issue there is that on incoming we use reasonably-well written JS to do many libc things, that in the musl-syscalls branch we do in C. In -O0, that C is turned into not very well optimized JS (no variable elimination, etc.). But on anything more realistic, like optimized small programs or any large programs, musl with static syscalls wins.

I think this branch is almost ready to merge. I'll do some more tests before. Please let me know if I should check anything else before merging.

**Comment by kripken** [comment]
Compilation speed comparison:

|                  | before |  after |
|------------------|:------:|:------:|
| hello world -O2  |  0.671 |  0.877 |
| hello libc++ -O2 |  2.415 |  2.500 |
| BananaBread      | 12.892 | 12.739 |

As expected, tiny programs get slower - we link and build to JS a lot more C code. The difference on a medium size program like libc++ is much less noticeable. On a more realistic project like BananaBread, I actually see a slight speedup. Might be noise, although I did do multiple iterations, so I don't think so.

**Comment by kripken** [comment]
Merged to incoming.

**Comment by socketpair** [comment]
WOW! Will explore how to get glib to be compiled.

**Comment by floooh** [comment]
I get a linking problem when compiling with NO_FILESYSTEM=1, wrote a separate ticket: https://github.com/kripken/emscripten/issues/3627

**Comment by kripken** [comment]
incoming looks stable, aside from two NODEFS issues on windows, which I don't think are related to this. I landed a branch on incoming that cleans up no longer needed library.js code, basically everything that is now done by musl.

**Comment by quirinpa** [comment]
Implementing syscalls sounds like the job of the kernel. Why not make it mainly in C? I mean... The linux kernel just has to be ported... lol. Kernel inception.
