### ISSUE TITLE
844929b makes sound much worse in DOSBox

### ISSUE THREAD

**Issue by dreamlayers** [kripken/emscripten#3122]
When I first [ported DOSBox](https://github.com/dreamlayers/em-dosbox), sound was quite good. After  recompiling with recent versions, it is very bad. I tried older versions of src/library_sdl.js and found that 844929b makes sound much worse. Before it, there are some occasional short interruptions. At that revision, sound has frequent short beepy sounds, just like in 1.29.0.

I have a new branch with SDL 2 which has good sound with Emscripten 1.29.0. So, I have a solution, but there are still lots of SDL 1 apps which could benefit from improved sound.

**Comment by juj** [comment]
Oh no, this is not great news. I think the new queueing code should be strictly better than the old one, since it avoids the use of timers that introduce jitter.

Can you try playing with the different parameters related with the queueing code, to see if there is a better default:
https://github.com/kripken/emscripten/commit/844929b805564bb99a006655b063e155cc4218a4#diff-52ac12f797aa53539b7d78c3dc313fadR2145

https://github.com/kripken/emscripten/commit/844929b805564bb99a006655b063e155cc4218a4#diff-52ac12f797aa53539b7d78c3dc313fadR2150

**Comment by dreamlayers** [comment]
I tested in Emscripten 1.29.0, compiling with -O1 and editing those values in dosbox.js in a text editor. Changing default SDL_numSimultaneouslyQueuedBuffers from 5 to the previous value 3 greatly reduces the amount of those short beepy sounds in Chrome 39 and Firefox 34. More beepy sounds remain in Firefox than in Chrome, but it is a big improvement in both.

SDL.audio.bufferingDelay changes the audio delay but does not seem to affect quality. (Delay is undesirable as it desynchronizes audio and video.)

Now the question is: why would increasing SDL_numSimultaneouslyQueuedBuffers cause problems? I think there must be some bug elsewhere which causes them to be scheduled incorrectly, with overlaps.

**Comment by dreamlayers** [comment]
Sound works great now! Thanks for quickly merging the pull request.
