### ISSUE TITLE
Optimizer build fails on Ubuntu 12.04 (GCC 4.6) by default

### ISSUE THREAD

**Issue by jgranick** [kripken/emscripten#3189]
Using Ubuntu 12.04, the Emscripten SDK installation fails because "-std=c++11" is not a recognized flag in GCC 4.6. I did not notice this as a requirement for Emscripten, it seems to only be when building the optimizer in the "emscripten-master" package.

I'm not sure if it would be possible to build using "-std=c++0x" instead, or if GCC/G++ 4.8 is a clear requirement. Fortunately, I was able to update to 4.8 using the following commands, but I wanted to point this out for either documentation or perhaps a small tweak to the build script, to help prevent this issue :smile:

    sudo add-apt-repository ppa:ubuntu-toolchain-r/test
    sudo apt-get update
    sudo apt-get install gcc-4.8 g++-4.8
    sudo update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-4.8 50
    sudo update-alternatives --install /usr/bin/g++ g++ /usr/bin/g++-4.8 50

I also installed `g++-4.8-multilib` for cross-desktop builds elsewhere on the system

**Comment by juj** [comment]
Oh darn, this is annoying.. Not sure what a good fix is. The native optimizer will need C++11'ish features, and also not sure if C++0x will be enough, and also not sure if G++ 4.6 support for C++0x is enough.

In any case, the lines in question are these:
   - automatic on-demand build of native optimizer (not used when using via emsdk): https://github.com/kripken/emscripten/blob/master/tools/js_optimizer.py#L59
   - emsdk build of native optimizer (based on cmake): https://github.com/kripken/emscripten/blob/master/tools/optimizer/CMakeLists.txt#L15

If you have an easy way to use g++ 4.6 on your system, it would be nice to know if replacing those lines with -std=c++0x works well. CC @kripken .

**Comment by kripken** [comment]
I think c++11 is strictly needed. But the system should handle failure to build by using the more portable (and slower) JS optimizer. Did that work properly in this case?

**Comment by jgranick** [comment]
In that case, perhaps the setup needs to be able to fall through in case of an error, or perhaps warn and skip if an older GCC version is detected.

This was all in the process of running `./emsdk install latest`, trying to get it to complete :smile:

**Comment by kripken** [comment]
Oh, this is an SDK issue? @juj, does the SDK not continue if the native one fails to build (the js optimizer will then be used)?

**Comment by juj** [comment]
The installation will report an error, but there are no other steps that it will perform there, so when one does compile something with the emscripten installation, native optimizer will then be used.

**Comment by kripken** [comment]
And emscripten will automatically see that there isn't one built, will try to build it, fail, then use the js optimizer from then on forward - is that what happens in practice? Or is there something we need to fix here?

**Comment by juj** [comment]
That is what should be happening. It probably makes sense to demote the error message during emsdk installation to a warning message, since the JS optimizer does exist as a fallback, so that the user will not interpret that the whole installation would have been a failure.

**Comment by kripken** [comment]
Ok, sounds good. A warning mentioning that compilation speed will be slower, but otherwise everything will work, seems reasonable.

**Comment by samsamm777** [comment]
This is also an issue building on GCC 4.4

**Comment by aidanhs** [comment]
Since we have them built anyway, couldn't we use clang/clang++ from fastcomp?

**Comment by aidanhs** [comment]
In addition, this would help with memory consumption on Windows because of things like https://github.com/kripken/emscripten/blob/1.34.9/tools/optimizer/simple_ast.h#L91

**Comment by kripken** [comment]
I don't remember the details, but @juj made windows always use cmake, and visual studio, while on other platforms we do try out clang first.

**Comment by aidanhs** [comment]
Well...given this issue (the system compiler on Linux being unable to compile the optimizer), evidence suggests we don't default to clang on Linux!

As it sounds like it *should* default to clang, this issue is therefore a relatively easy fix. I'll wait for a comment from @juj about the motivation behind using VS on Windows - maybe that can be changed at the same time.

**Comment by juj** [comment]
It is not possible to use Clang on Windows, because it requires Visual Studio and/or Windows SDK to be installed on the system anyways, for standard library headers. Also, Clang Windows support is not complete enough that it would be able to be relied on.

It might be possible to use our built Clang to build on Linux however, though I am not sure what that details precisely. Possibly it can be as easy as setting the `CC` and `CXX` etc. environment variables before issuing `emsdk install`, since CMake directly reads those to find the system compiler.

**Comment by kripken** [comment]
Hmm, we should definitely be using our clang first, on non-windows,

https://github.com/kripken/emscripten/blob/incoming/tools/js_optimizer.py#L148

Perhaps this bug report is out of date?

**Comment by aidanhs** [comment]
https://github.com/juj/emsdk/blob/master/emsdk#L648 - can't see `clang++` mentioned in this file. Though I'm now falling into the maze of build possibilities. I'll have to take another look at some point in the future.

**Comment by kripken** [comment]
@juj doesn't the sdk build the optimizer using emscripten's code, which does use our clang?

**Comment by juj** [comment]
Ops, very sorry that I had dropped a question here.

Emscripten SDK uses the CMake script at https://github.com/kripken/emscripten/blob/master/tools/optimizer/CMakeLists.txt to build the optimizer. The bug mentioned in this issue was fixed in https://github.com/kripken/emscripten/commit/d3c384d133ed234f15cccddefd6f64bbce1ed251, so let me close this as resolved.
