### ISSUE TITLE
SIMD no longer runs in current Firefox Nightly.

### ISSUE THREAD

**Issue by juj** [kripken/emscripten#3198]
Testing this code

	#include <xmmintrin.h>
	#include <stdio.h>

	unsigned int u[4];
	__m128 __attribute__((noinline)) foo() { return _mm_set1_ps(1.f); }

	int main()
	{
		__m128 m = foo();
		_mm_storeu_ps((float*)u, m);
		printf("%x %x %x %x\n", u[0], u[1], u[2], u[3]);
	}

no longer builds and runs on Firefox Nightly, but instead gives the error

	exception thrown: TypeError: invalid 'instanceof' operand SIMD.float32x4,SIMD.float32x4.check@file:///C:/code/emsdk/emscripten/incoming/b.js:236:9
	__Z3foov@file:///C:/code/emsdk/emscripten/incoming/b.js:10701:24
	_main@file:///C:/code/emsdk/emscripten/incoming/b.js:10710:29
	asm._main@file:///C:/code/emsdk/emscripten/incoming/b.js:14167:8
	callMain@file:///C:/code/emsdk/emscripten/incoming/b.js:14286:15
	doRun@file:///C:/code/emsdk/emscripten/incoming/b.js:14344:42
	run/<@file:///C:/code/emsdk/emscripten/incoming/b.js:14355:7

	TypeError: invalid 'instanceof' operand SIMD.float32x4

Building with a bit older version of Emscripten does not give that error, but instead says

    TypeError: invalid arguments

on a line that is compiled from the `_mm_storeu_ps` and reads

    $38 = $38;SIMD_float32x4_store(HEAPU8, $38, $98);

**Comment by juj** [comment]
CC @sunfishcode , is this a known recent regression?

**Comment by sunfishcode** [comment]
Yes. Upgrading to the latest trunk SpiderMonkey fixes it.

The polyfill is trying to be clever and use whatever parts of any native SIMD implementation might be available, and it usually works to use a mix of native and polyfilled features. However, it turns out that it doesn't work in the case of the newly added 'check' function, because the polyfill version of check calls instanceof, which doesn't work with a native (non-polyfiled) SIMD type. Browsers with no native SIMD type work because everything is polyfilled, and newest SpiderMonkey works because both the SIMD types and the check function are native.

**Comment by juj** [comment]
Thanks, looks like this was very recent, my Firefox was just a few days old, updating again works.

However, now I understand what the second problem is: since I'm working on this with the pthreads work, HEAPU8 is a `SharedUint8Array` instead of a regular `Uint8Array`, hence the operations will fail. I reported that at https://bugzilla.mozilla.org/show_bug.cgi?id=1133859 .
