### ISSUE TITLE
Glitch in structure members access

### ISSUE THREAD

**Issue by Olivier-myriad** [kripken/emscripten#3301]
Hi,

After trying "Hello world", I decided to give a shot with a more complex project.

I then got an issue that I can reproduce each time, but is too embedded in my project (20 plain-C source files) to be extracted. 

Here is what I get, after working on some data structure:
A function sets masque->lettres.items (unsigned long) to 1.
Then, I have :

`printf("Addr %08lx size %d content %lu\n",`
`   (long)&(masque->lettres.items),`
`   sizeof(masque->lettres.items),`
`   masque->lettres.items);`

`printf("Memory at %08lx = %lu\n",`
`     (long)&(masque->lettres.items),`
`     *(unsigned long *)&(masque->lettres.items));`

Whatever I did before, the content of memory should be equal to the structure member. Hence, the output is :

`Addr 005bdcf6 size 4 content 1703936`
`Memory at 005bdcf6 = 1`

How can it be explained otherwise than an error in the Emscripten compiler?

Note : I compiled my whole project using the -g4 option, as well as -s ALLOW_MEMORY_GROWTH=1.

Does anybody have a clue?

Thanks,

**Comment by juj** [comment]
Your code is incorrect, since it is accessing an unaligned pointer. That is undefined behavior in C. See http://stackoverflow.com/questions/28893303/is-a-misaligned-load-due-to-a-cast-undefined-behavior . You can use the Emscripten linker flag `-s SAFE_HEAP=1` or `-s CHECK_HEAP_ALIGN=1` to add runtime logging to detect bad code that attempts to do so.

In general C code that is compiled to target native x86 allows this to work, since the platform instruction set does have support for unaligned memory accesses, but for example if you were targeting ARM (Android or iOS), the code would not work either.

**Comment by Olivier-myriad** [comment]
Right, the pointer is indeed unaligned.
I just realized that in my headers, there were some #pragma pack(2). Removing them makes the program work.
However, what is curious is that the compiler itself accepts to create misaligned data structures, but isn't able to process them. Shouldn't it prevent the use of structure packing that it can't manage?

**Comment by juj** [comment]
#pragma pack() should work just fine, but the issue is that you are using a C cast like this `*(unsigned long *)&(masque->lettres.items)`. That discards alignment information, and tells the compiler "trust me, this address points to an aligned unsigned long". If you want to cast to an unaligned unsigned long, you  will have to say so via something like

    typedef unsigned long __attribute__((aligned(2))) ulong_align2;
    ulong_align2 *d = (ulong_align2*)&(masque->lettres.items);
    printf("data: %ul\n", *d);

Using the typedef is required due to Clang compiler GCC compatibility-specific reasons ( https://llvm.org/bugs/show_bug.cgi?id=19881 ). Emscripten also provides a set of predefined typedefs for convenience: https://github.com/kripken/emscripten/blob/master/system/include/emscripten/emscripten.h#L34

**Comment by Olivier-myriad** [comment]
Well, please consider that the "*(unsigned long *)&(masque->lettres.items)" actually works (it gives the 1, the expected value). The direct access to the data structure doesn't.

Above this, "&(masque->lettres.items)" is supposed to provide the memory address of the structure member _after alignment_. On any compiler, with any structure alignment, it should work. There is absolutely _no reason_ for the compiler to provide a pointer to a memory address if the requested structure member isn't located at this address.

Alignement of structure members is decided by the compiler when parsing the structure definition. 
Please read the definition of the *offsetof* macro as well as its usage to be definitely convinced :)
 
So, in this code snippet, I don't add an arbitrary offset to a base pointer, I ask for the direct pointer to a structure member, which is perfectly legit.

**Comment by juj** [comment]
You are most likely seeing the effects of a previous write to a badly casted address, which makes it look as if the C cast works and the direct access doesn't. Here is an example, which works as expected with `#pragma pack`, and illustrates how accessing via a C cast corrupts the data and how a later access to that data may seem like C cast might work and direct access doesn't:

	#include <stdio.h>
	#include <inttypes.h>

	#pragma pack(2)
	struct Foo
	{
		uint16_t a;
		uint32_t b;
		uint16_t c;
	};

	int main()
	{
		Foo f;
		f.a = 10;
		f.b = 42;
		f.c = 64;
		printf("f.a <- 10, f.b <- 42, f.c <- 64.\n");
		printf("alignment of a: %X. Value at a: %u\n", ((uintptr_t)&f.a) % 4, f.a);
		printf("alignment of b: %X. Value at b: %u\n", ((uintptr_t)&f.b) % 4, f.b);
		printf("alignment of b: %X. Value at b: %u\n", ((uintptr_t)&f.b) % 4, *(uint32_t*)&f.b);
		printf("alignment of c: %X. Value at c: %u\n", ((uintptr_t)&f.c) % 4, f.c);

		uint32_t *data = (uint32_t*)&f.b;
		*data = 90;
		printf("Bad attempted write to f.b <- 90.\n");
		printf("After bad write: alignment of a: %X. Value at a: %u\n", ((uintptr_t)&f.a) % 4, f.a);
		printf("After bad write: alignment of b: %X. Value at b: %u\n", ((uintptr_t)&f.b) % 4, f.b);
		printf("After bad write: alignment of b: %X. Value at b: %u\n", ((uintptr_t)&f.b) % 4, *(uint32_t*)&f.b);
		printf("After bad write: alignment of c: %X. Value at c: %u\n", ((uintptr_t)&f.c) % 4, f.c);
	}

Building with `em++ x.cpp -g4 -s ALLOW_MEMORY_GROWTH=1 -o x.js`, and running `node x.js` gives

	f.a <- 10, f.b <- 42, f.c <- 64.
	alignment of a: 0. Value at a: 10
	alignment of b: 2. Value at b: 42
	alignment of b: 2. Value at b: 2752522
	alignment of c: 2. Value at c: 64
	Bad attempted write to f.b <- 90.
	After bad write: alignment of a: 0. Value at a: 90
	After bad write: alignment of b: 2. Value at b: 0
	After bad write: alignment of b: 2. Value at b: 90
	After bad write: alignment of c: 2. Value at c: 64

However this is just a guess, since I don't see your full code. In any case, compiling the same code with `-s SAFE_HEAP=1` gives added error checks so that it is possible to pinpoint locations where badly aligned loads or stores occurs:

    f.a <- 10, f.b <- 42, f.c <- 64.
    alignment of a: 0. Value at a: 10
    alignment of b: 2. Value at b: 42
    alignment error loading from address 1066, which was expected to be aligned to a
     multiple of 4
    alignment error loading from address 1066, which was expected to be aligned to a
     multiple of 4

    C:\code\emsdk\emscripten\incoming\x.js:86
          throw ex;
                ^
    abort("alignment error loading from address 1066, which was expected to be aligned to a multiple of 4") at Error
        at jsStackTrace (C:\code\emsdk\emscripten\incoming\x.js:1239:13)
        at stackTrace (C:\code\emsdk\emscripten\incoming\x.js:1256:22)
        at abort (C:\code\emsdk\emscripten\incoming\x.js:10357:44)
        at SAFE_HEAP_LOAD (C:\code\emsdk\emscripten\incoming\x.js:384:27)
        at _main (C:\code\emsdk\emscripten\incoming\x.js:9903:8)
        at Object.asm._main (C:\code\emsdk\emscripten\incoming\x.js:10107:19)
        at Object.callMain (C:\code\emsdk\emscripten\incoming\x.js:10226:30)
        at doRun (C:\code\emsdk\emscripten\incoming\x.js:10284:60)
        at run (C:\code\emsdk\emscripten\incoming\x.js:10298:5)
        at Object.<anonymous> (C:\code\emsdk\emscripten\incoming\x.js:10381:1)

so that is a good way to locate misbehaving code.

**Comment by Olivier-myriad** [comment]
I respectfully disagree.

If b is a 32-bits int, the expression `*(uint32_t*)&(f.b))` should *always* provide an aligned pointer on the 4-bytes data that actually contains the value of this member, whatever the alignment chosen by the compiler. 
Otherwise, it's a fault in the compiler.

**If `<expr>` is a long int, `*(long *)&(<expr>)` has to be equal to `<expr>`. Always.** 

In C, if you get the address of a variable, a structure member, or an array element, as well as its size through `sizeof` and if you binary preserve `<size>` bytes from this address, you will preserve the actual content of the item, not some random fillers that could have been added by the compiler to align the members.

In C, you can write a function that receives a pointer, and work on the content of this pointer.

If you write:
```
#pragma pack(2)
struct Foo
{
int16 a;
int32 b;
};

void SetLong(int32 * addr,int32 value)
{
*addr=value;
}

int main(void)
{
struct Foo f;
int32 i;

SetLong(&i,10);
printf("i= %ld\n",i);
SetLong(&(f.b),10);
printf("f.b= %ld\n",f.b);
}
```
you don't have to worry whether the address sent to the "SetLong" function points to a single variable, a structure member or an array element. It should work, period. There is just no reason for the compiler to align the pointer to a 4-bytes boundary when getting &(f.b), since pack(2) is supported and longs can be read and write on unaligned addresses.

**Comment by sunfishcode** [comment]
In plain C, longs cannot be read or written as longs on unaligned boudaries under any circumstances.

#pragma pack is an extension which allows for unaligned accesses. Direct accesses to packed members are covered by the extension. But, if you take the address of a packed member, the resulting pointer is just a normal pointer, subject to the normal rules for normal pointers, including alignment.

The example code here invokes undefined behavior, meaning "demons may fly out your nose" at any time, even if that's not what usually seems to happen in practice.

There are tools which can help detect such problems, such as those mentioned above.
