### ISSUE TITLE
ENVIRONMENT_IS_NODE is a false positive in browserify

### ISSUE THREAD

**Issue by fabiosantoscode** [kripken/emscripten#3379]
When using browserify, this flag in the generated code will be set to true, since there is indeed a `process` variable.

The problem with this is that `process` variable is a shim, and it doesn't have a lot of features it has in node.

The `ENVIRONMENT_IS_NODE` flag should be false when in the presence of a `window` object.

Emscripten should still export to module.exports if it's present, but that's another issue.

Thanks for your work on this awesome project!

See defunctzombie/node-process#40

**Comment by kripken** [comment]
Thanks for reporting. My tendency is to fix this by making `ENVIRONMENT_IS_NODE` check for something more specific, e.g. a property on the `process`. When looking at what we have now, I saw we also check for `require`. Is that is also present in browserify? If so it's almost like it's trying to fake node ;)

**Comment by fabiosantoscode** [comment]
It is trying to fake node :) most node modules (those which don't require any C++ extensions) are accidentally compatible with browserify because of these shims.

There are differences, such as the absense of process.stdin/stdout/stderr.

`require` is a separate thing. It's part of commonJS, which node happens to implement: http://wiki.commonjs.org/wiki/Modules/1.1

I'm sure there's something like a NODE_VERSION property somewhere, let me check for it. But I'd recommend to adopt a more loose definition of "node" so that it embraces things which may not be node, but are javascript running in a non-browser environment. Detecting node is like user agent sniffing, while feature detection may be a better idea.

**Comment by fabiosantoscode** [comment]
(Pull request is cooking)

**Comment by kripken** [comment]
Fixed by that pull.

**Comment by blixt** [comment]
I just ran into this issue by running a Browserified script inside of a Web Worker, which does not have the `window` object available... Does it make sense to update `ENVIRONMENT_IS_NODE` to also check `!ENVIRONMENT_IS_WORKER`?

**Comment by blixt** [comment]
This still happens if Browserify is used to create a Web Worker script. I propose this fix, but I'm not sure if it might break something else?

https://github.com/blixt/emscripten/commit/2f904b3d88e83551b4a72c8f092967fec810b4ca#diff-b0b85d67c2201828828422795fb44581

**Comment by fabiosantoscode** [comment]
(sorry for the late reply, my inbox is flooding!)

I don't think we should count on importScripts just being present in the browser. There are some web-worker emulation modules in nodeJS that attempt to be isomorphic by emulating the standard API.

How about checking `navigator` instead of `window`?

**Comment by kripken** [comment]
I'm ok with that, assuming it works in all known browsers.

**Comment by fabiosantoscode** [comment]
According to this page (
https://developer.mozilla.org/en-US/docs/Web/API/NavigatorID/userAgent)
navigator.userAgent is present since at least Netscape 6 and all the
browsers today feature it as well.

This page (https://msdn.microsoft.com/en-us/library/ms534712(v=vs.85).aspx
) shows it on IE6.

I'm personally pretty sure it's as universal as `window`.

**Comment by blixt** [comment]
@fabiosantoscode Did you see https://github.com/kripken/emscripten/pull/3577 ?

The concept for the `ENVIRONMENT_IS_*` constants is that only one is `true` (the others should be `false`). So the choice has to be whether `ENVIRONMENT_IS_WORKER` should be `true` and `ENVIRONMENT_IS_NODE` should be `false` (current status quo after my fix), or vice versa (what you're proposing?)

I don't think having this "only one may be true" constant logic will work in the long run, and I instead think that there should be feature detection (e.g., "should we use `Buffer` or `ArrayBuffer`?", "can we use `require(…)`?", etc. etc.) Changing the current logic probably won't improve the situation since there is no way to reflect "Web Worker on Node.js" unless we add yet another constant (which I don't think is a good solution either).

**Comment by fabiosantoscode** [comment]
I agree. Are these being used in too many places?

**Comment by fabiosantoscode** [comment]
About only one of them being true, I don't think that's so good either.

When we're in the browser and in a worker I would expect both is_browser
and is_worker to be turned on.

If we were to add environment_is_es6 for some reason (relying on tail call
elimination for instance), it wouldn't make sense to make
environment_is_browser false.

I couldn't agree more that the best way here is through feature detection.
Maybe HAS_REQUIRE, HAS_CANVAS, HAS_XHR... would make much more sense than
trying to guess what is running us.

**Comment by kripken** [comment]
I'm ok with using `navigator`, then.

I would also be ok with changing the entire `ENVIRONMENT_*` system to be more feature detection-ey. But first we would need to inspect all the usages of those variables throughout the codebase to see if there isn't a use in which we do care about what the environment is, as opposed to a specific feature in it.

**Comment by blixt** [comment]
@kripken: My recommendation would be to set up feature constants, and then have a single constant that can be called `ENVIRONMENT` or some such, which tries to represent which environment you're in. It would have to be more conservative and well-defined than today, to avoid cases like the Web Worker one (which can be both web and Node.js).

I'd suggest only setting the environment constant to one of `"browser"`, `"shell"`, or `"node"` and resolving everything else via feature flags. Examples:

```javascript
if (HAS_REQUIRE) { … }
if (ENVIRONMENT === 'node' && IS_WEB_WORKER) { … }
if (ENVIRONMENT === 'web' && HAS_REQUIRE) { … }
```

**Comment by kripken** [comment]
I don't understand what `if (ENVIRONMENT === 'node' && IS_WEB_WORKER) { … }` means. Are you saying there is a single "environment" and multiple possible properties, like "is a web worker" (which node can be)?

What would be the code inside those curly braces? Couldn't it check something more feature-specific than "is a web worker"?

**Comment by blixt** [comment]
My suggestion is that any code in Emscripten that today checks `if (ENVIRONMENT_IS_WORKER) { … }` will instead have more detailed checks like the one you quoted. The reality is that being in a Web Worker doesn't exclude being Node.js, nor does it exclude being in a browser (it can be either or). So that check needs to be detailed as in my example. It's also possible that the code doesn't care if we're using Node.js or the browser, in which case it would just check `if (IS_WORKER) { … }`. The important thing is that being a Web Worker is not exclusive to being a browser or a Node.js script.

As for more feature specific, yes, there is a lot more. I think `IS_WEB_WORKER` is a good feature check as well because it implies a lot of things like `importScripts` and `self` globals (I think creating constants for them separately would be overkill because there is no example in the world of one existing and not the other), as well as the absence of DOM. But then there could also be other constants like `HAS_DOM`, `HAS_REQUIRE`, `HAS_XHR`, `HAS_TYPED_ARRAYS`, etc. I think they would need to be defined on an as-needed basis because otherwise you'd get a lot of constants (see http://caniuse.com/ for an example of some feature sets that differ based on environment).

**Comment by kripken** [comment]
Why not directly check for `importScripts`? Are you worried that it might exist in a non-worker environment?

**Comment by fabiosantoscode** [comment]
I think that @blixt is trying to centralize all feature detections in one spot. It may be easier to change things later on like this.

I agree with his approach. Also, it will be easier to read `if (IS_WORKER){...}` than `if (typeof importScripts !== 'undefined') {...}`.

**Comment by ekaitz-zarraga** [comment]
Hi,

I arrived to this issue from kripken/sql.js#187 

The problem I see is that when I'm trying to Browserify a module generated with EMSCRIPTEN the environment flags are not checked.

Browserify just concatenates all the possible *require*s and doesn't matter if they are used on execution time. In the case of sql.js:

``` javascript
if (ENVIRONMENT_IS_NODE) {
  var nodeFS = require('fs');
  var nodePath = require('path');
```

Doing this, Browserify does not execute the code, it only looks for all the requires and add them to the output bundle. This means the final bundle will also contain a Browserified version of `fs` and `path` in this case, even if they are never executed because the execution flow never falls there thanks to the environment flags.

This creates a 8.7MB bundle in sql.js because of that.

I don't know if it's really a EMSCRIPTEN problem or it's from Browserify but even if in this issue is solved what does the browser execute, it does not solve which modules are *require*d when bundle is created.

Did you also encounter this problem?

Thanks!
