### ISSUE TITLE
32-bit floating point operating in 64-bit mode

### ISSUE THREAD

**Issue by httpdigest** [kripken/emscripten#3408]
Hi there,

I was testing some 32-bit floating-point arithmetics in Emscripten and it seems that Emscripten is emitting 64-bit floating-point arithmetics when compiling C code with `-O0`.
Everything starting and above `-O1` works correctly.

The following program wrongly prints `9.999999933815813e+38` instead of the IEEE 754 32-bit correct value `Infinity`:

```C
#include <stdio.h>
int main(int argc, char** argv) {
  float a = 1E+37f;
  float b = 1E+2f;
  float result = a * b;
  printf("%f \n", result);
  return 0;
}
```

I compiled with: `./emcc test.c -o test.html`.
Is Emscripten only emitting asm.js code above and including `-O1` ?

**Comment by httpdigest** [comment]
Oh wait... The reason why `-O1` and above worked was constant-folding.
When inspecting the generated asm.js source I found this:
`HEAPF64[$vararg_buffer>>3] = inf;`
I find it strange that HEAPF64 is being used here and not some HEAPF32...
I try to build an example that does not constant-fold to reproduce the issue with `-O1` and above.

**Comment by httpdigest** [comment]
So, I managed to build an example that also fails on `-O1` by wrongly printing `9.999999933815813e+38`:

```C
#include <stdio.h>
#include <time.h>
float someNumber() {
  time_t rawtime;
  struct tm * timeinfo;
  time(&rawtime);
  timeinfo = localtime(&rawtime);
  if (rawtime > 0) {
    return 1E+2f;
  } else {
    return 1E+3f;
  }
}
int main(int argc, char** argv) {
  float result = 1E+37f * someNumber();
  printf("%f \n", result);
  return 0;
}
```

I do this time querying only to make clang not inline the function `someNumber`.

**Comment by juj** [comment]
This is expected. Try building with the linker flag `-s PRECISE_F32=1` to get exact single-precision floating point. The reason why we don't do this by default, but have all floats be doubles at runtime is that browsers other than Firefox have had horrible performance when Math.fround() is involved, since they don't specially recognize and optimize that pattern. Not sure though if the very recent advances in browsers (Turbofan for Chrome, FTL for Safari) have managed to improve this scenario though. Eventually we would like to make `-s PRECISE_F32=1` the default build option, but before doing so, we must be absolutely sure that this doesn't kill performance such dramatically anywhere.

Also iirc, the LLVM IR syntax only has 64-bit double support as immediates, so the fmul line above will always show a 64-bit double quantity even if you were operating a 32-bit float.

**Comment by httpdigest** [comment]
Oh, thanks for the hint to `PRECISE_F32`. It works! :)
I'd say LLVM IR has both float and double as type specifiers.
Also the C++ API has `Type::getDoubleTy` and `Type::getFloatTy`. And I think it would be very unwise for them whilst trying to provide such a general low level intermediate language to not having thought about representing 32-bit and 64-bit floating-point values differently. :)

**Comment by juj** [comment]
Oh, I meant that the syntax for float immediates - even if you have a single precision float, you'll always see full 64-bit wide constant being written in the IR, though the type half/float/double then gives the actual width.

**Comment by httpdigest** [comment]
Oh yes, you are right. That seems like so, when looking at the 'literal' `0x479E17B840000000`. It seems to be 8 bytes wide. Is that the binary (in hexadecimal notation) representation of 1E+37f?

**Comment by juj** [comment]
Yeah, checking from e.g. http://gregstoll.dyndns.org/~gregstoll/floattohex/ , `0x479E17B840000000` -> convert to double gives `9.99999993382e+36`.

When entering `9.99999993382e36`

**Comment by httpdigest** [comment]
Okay, thanks for the info.
I would close this issue now for not having known about PRECISE_F32. With that flag, everything seems to work as expected and compiles as asm.js.
And since for the time being I am using Firefox Nightly/Trunk anyways (for the pthreads stuff), I have no concern with performance on other browsers. :)
