### ISSUE TITLE
Runtime failure: missing function: fesetround

### ISSUE THREAD

**Issue by klaussilveira** [kripken/emscripten#3422]
How can i include this function in an emscripten build? Here's the affected code: https://github.com/ioquake/ioq3/blob/master/code/sys/sys_unix.c#L799

**Comment by kripken** [comment]
JS doesn't allow changing the CPU float rounding mode, so we can't implement those. You can try just removing it from the project, and unless it depends heavily on float rounding specifics, it should be fine (perhaps not as fast though).

**Comment by sunfishcode** [comment]
The code linked above is just using FE_TONEAREST. That's the default mode in asm.js, so it should be good.

@juj Do you know why system/lib/libc/musl/src/fenv/fenv.c defines __fesetround instead of plain fesetround? It seems like we ought to be able to have a minimal fesetround/fegetround that just does FE_TONEAREST.

**Comment by juj** [comment]
@sunfishcode : The musl structure is that `fesetround` is the user facing standard function, and `__fesetround` is an internal "do it" function. The file `fesetround.c` in musl (which we don't carry in Emscripten atm it looks like) has the implementation of `fesetround`. We could add a no-op function that only validates the input and yells on unsupported modes, but not sure if that would be worth it - as it would shift potential portability problems from being detected at compile time to being detected at runtime only if the code is tested to execute through the problematic path.
