### ISSUE TITLE
Function pointers to js functions

### ISSUE THREAD

**Issue by coolwanglu** [kripken/emscripten#3432]
Sample code:
```
// tmp.c
void f();
int main() {
  void (*g)() = &f;
  (*g)(); 
  return 0;
}

// tmp_lib.js
// mergeInto...
hello: function() {}
```

The output would fail at `(*g)()`, and it turns out that `_f` is not stored in`FUNCTION_TABLE_v`. Instead, there's a `_f__wrapper` in `FUNCTION_TABLE_vi`.

I couldn't find relevant info in the docs, is it a bug?

**Comment by coolwanglu** [comment]
If `f` and `g` are of type `int(int)`, there seems to be no problem.
What is `__wrapper` for? Maybe for asm.js I guess?

**Comment by kripken** [comment]
Yes, the wrapper is because asm.js doesn't allow external non-asm functions in tables. So emscripten will wrap it automatically.

The problem here is that C is weird... you need to write `void f(void);`, otherwise it thinks it is a variadic function, since it "doesn't know" how many arguments it has. Saying `void` there tells it that there are no arguments. (And in emscripten, a variadic function has a single argument, an int, to the varargs on the heap.) Luckily, this isn't a problem in C++, just C.

**Comment by coolwanglu** [comment]
Oh I didn't know that in C. Thanks for the explanation.

Shall we put a warning in emcc or the docs?

**Comment by kripken** [comment]
If you find a good place to put that in the FAQ, sure - I don't remember if we already do mention it or not.

**Comment by coolwanglu** [comment]
Hmm, it is still confusing, as f and g appear to be of the same type.
Does it make sense to treat g as a vi function also?

**Comment by coolwanglu** [comment]
Sure I will do that tomorrow, probably in the page about function pointer casting.

**Comment by coolwanglu** [comment]
On a second thought, maybe the current way is more intuitive and standard. `void (*g)();` is more like `void (*g)(void);`, and `void f();` is more like `void f(...);`. 
After a bit of further reading, I realized that it's a common sense for C programmers that I was lack of :)

Thanks.
