### ISSUE TITLE
GL_DEBUG flag does not cause WebGL calls to be printed

### ISSUE THREAD

**Issue by croes** [kripken/emscripten#3433]
When linking with `-s GL_DEBUG=1`, I expect calls into WebGL to be printed out (as stated by the flag's [documentation](https://github.com/kripken/emscripten/blob/b3efd9328f940034e1cab45af23bf29541e0d8ff/src/settings.js#L217)). However, the generated code does not print out these calls. Some things are missing:

1) The call to wrap the context in it's debug wrapper. Only a [comment mentioning this call](https://github.com/kripken/emscripten/blob/master/src/library_gl.js#L747) is generated.
2) The `dump` function is undefined. I presume this should just delegate to `Module.print`?
3) The documentation states that passing a runtime flag (`GL.debug`) should also wrap the context in a debug context. This is currently impossible, as the `wrapDebugGL` function is only generated when passing the `GL_DEBUG` linker flag. Also, no checks are done on the runtime flag. What would be the expected behavior here? Would you generate the `wrapDebugGL` function in all build types, but only call it when `GL_DEBUG` is set or the runtime `GL.debug` is set?

I can make a pull request fixing these points if they actually are issues.
I'm using Emscripten version 1.32.0.

**Comment by juj** [comment]
2) The `dump` function is a reference to Firefox specific `about:config` flag `browser.dom.window.dump.enabled`. See https://developer.mozilla.org/en-US/docs/Web/API/Window/dump . Code should test whether calling it, and skip it if not present. It's not good to blindly override this.

1&3) It is desired that `wrapDebugGL` is only generated to code when `GL_DEBUG` is specified. A good fix would be to also register a call to `wrapDebugGL()` to occur by default when `GL_DEBUG` is specified. Removing the `#ifdef GL_DEBUG`s so that `wrapDebugGL` is unconditionally always emitted is not ideal, since it's then lying around in all generated code when it's only a debugging feature. The best is to fix documentation so that only if `GL_DEBUG` is set, then the variable `GL.debug` can be accessed.

**Comment by croes** [comment]
Included the following changes, based on juj's helpful response:

* `dump` does not override `window.dump`. Also, a check is added to see if `window.dump` is present. If it is not present, the dump is skipped. It does not fallback to `console.log` as it cannot handle a the large amount of prints.
* Only generate `wrapDebugGL` if `GL_DEBUG` is set. The call to `wrapDebugGL` is also only generated if `GL_DEBUG` is set.
* Updated documentation on `GL_DEBUG` to clarify it prints using `window.dump` and refer to the `window.dump` MDN.

**Comment by kripken** [comment]
Let's move discussion to the pull.
