### ISSUE TITLE
WebGL 2 calls broken when using closure compiler

### ISSUE THREAD

**Issue by mosra** [kripken/emscripten#3473]
When using the `--closure 1` flag, calls to WebGL 2 functions (such as `texStorage2D` etc.) are mangled into two-character names and the browser then complains that given name is not a function. This is not an issue with WebGL 1. Is there any "exports file" or something where WebGL 2 functions should be added to avoid the mangling?

**Comment by juj** [comment]
You can try changing the code in `src/library_gl.js` to change all comma accessors to array accessors, e.g. `GL.texStorage2D(params)` -> `GL['texStorage2D'](params)`. That should force closure to not minify the symbol name. 

That is the approach we've taken in general to be closure friendly, instead of specifying an exports list (which I think Closure does support, but I am not very familiar with it).

Feel free to submit pull requests to fix these instances (they are a bit of an oversight, not all code is tested with closure by the current test suite). Also apparently closure does not always preserve asm.js semantics, which has made it a bit unpopular, and instead we rely on the `--minify 1` option instead (default on in optimized builds).

**Comment by mosra** [comment]
Just curios now -- the WebGL 1 calls are not affected because Closure somehow detects and skips them? So, in theory, the WebGL 2 ones could be also handled automagically in some future release of closure compiler but it's too early now so we have to "work around" them?

**Comment by juj** [comment]
That is possible, since we've had to do this for random entry points in WebGL 1 as well, but not all.
