### ISSUE TITLE
Figure out a solution for resizable asm.js heap + pthreads.

### ISSUE THREAD

**Issue by juj** [kripken/emscripten#3499]
When compiling with pthreads enabled, it is not possible to enable the heap resizing, since the heap is shared. Figure out how to resolve this problem.

**Comment by lars-t-hansen** [comment]
On 64-bit x86 this is probably straightforward since we map a very large region of virtual memory for the heap and can just move the heap-limit pointer.

On 32-bit we can attempt to grow the region, but that may not work out in many cases.  A hint might help, when the buffer is first allocated, as might an attempt to spread the heap out in the address space.  (And e10s might help a lot in keeping the address space sparsely populated.)

**Comment by juj** [comment]
This has since been resolved, by implementing `brk()` and `sbrk()` functions to be thread-safe, as well as building `malloc()` as thread safe when multithreading is enabled. This allows compiling code with heap resizing enabled, and from asm.js/wasm side, things behave "safe". However under the hood in the browser land, like Lars mentions above, on 32-bit+multithreading, we are in big trouble, since after having created any threads, resizing the heap would require freezing the world and patching all live pointers, which is likely impossible, so it's possible that resizing will work more rarely compared to the singlethreaded case.

From the perspective of Emscripten runtime behavior, there should not be anything further to do here, so closing this as resolved.
