### ISSUE TITLE
Add support for compiling switch-cases of unbounded length.

### ISSUE THREAD

**Issue by juj** [kripken/emscripten#3534]
We are hitting a case where a large switch-case is autogenerated by a tool, and has a very simple pattern like follows

    const char *foo(int x)
    {
        switch(x)
        {
            case 1: return "a";
            case 2: return "b";
            ...
            default: return "";
        }
    }

that has a lot of cases. When compiling this code, we are seeing two different issues pop up:
   - Firefox aborts with "too much recursion" when running the generated code: https://bugzilla.mozilla.org/show_bug.cgi?id=1172895
   - LLVM crashes by blowing up the call stack.
   - Earlier in issue #781, a test was disabled since node.js crashes by blowing up the call stack.

Looking at the generated code, it becomes a huge nested if-else chain, and most parsers seem to be recursive in their handling of these blocks. Would we be able to retain a C/C++ switch-case, no matter how big, as a JS-side switch-case, if that would help avoid needing a linear amount of stack? That might also improve performance since it would not need a linear runtime with the if-elses?

Added a pull request with a new test #3533 to easily test this behavior.

**Comment by kripken** [comment]
We do not always emit a switch because there are limits on switches in JS engines and in asm.js.

We could emit code like `flatten()` in the js optimizer does,

````
var moar = true;
if (x == 0) {
  ...
  moar = false;
}
if (moar && x == 1) {
  ...
  moar = false;
}
...
````

Or it could have chunks each of which is a switch, to decrease the linear time cost. How does that sound?

**Comment by juj** [comment]
Would it be feasible to top-down binary bisect the switch-case into if()-else() halves until the number of cases is small enough to retain a switch-case internally. Something like:

    switch(foo) {
        cases 1-40000: ...; break;
        default: /*defaultblock*/; break;
    }

would be first halved to

    var default = false;
    if (foo <= 20000) {
        switch(foo) {
            cases 1-20000: ...; break;
            default: default = true; break;
        }
    } else {
        switch(foo) {
            cases 20001-40000: ...; break;
            default: default = true; break;
        }    
    }
    if (default) {
        /*defaultblock*/;
    }

which would then get recursively subdivided by halving the cases, until each switch-case contains fewer cases than some fixed limit for the size of a switch-case. If there is no `default:` block, then emitting the code for default handling could be omitted, and when doing multiple nested levels, there would not be need to recursively add such default handling variable to each level, but just the top level.

To me this kind of subdivision scheme sounds like the most performant (logN growth), and the call stack in parsers (I am not expert on parsers, so this is an assumption), would then grow only logarithmically, so 100k-ish cases in a switch should be easily achievable. CC @bnjbvr for a more technically expert opinion?

**Comment by bnjbvr** [comment]
I am compiling a browser to make some experiments with respect to parsing thread stack sizes and long chains of if/else vs switches, but in the meanwhile, here is some information I've compiled with respect to compilation time.

On my machine, with the test files @juj provided to me, with a recently Nightly on which these test cases compile, total compilation time is ~30 seconds, with two functions compiled slowly, namely the two functions that contain the big chains of if/else.
So I decided to make an experiment to see how compilation time was behaving with respect to the number of "else if" or the number of "case" statements within a switch statement. Here are the results:

```
Time of compilation, in ms (switch (number of cases) / if (number of "else if"))

1: 0 / 0
10: 0 / 0
100: 0 / 0
200: 2 / 4
400: 18 / 37
800: 218 / 240
1000: 510 / 761
1100: 656
1200: 952 / 1257
1300: 1340 / 1495
1400: 1647 / 1800
1500: 2507 / 2273
1600: 2999 / 2774
1700: 3383 / 5533 (!)
1800: 4567 / 4517
1900: 5378 / 6499 (!)
2000: 7126 / 6367
3000: 29057 / 29855
```

For instance, the line `1600: 2999 / 2774` reads as:

- for a switch statement with 1600 cases + default, compilation took 2999ms
- for a chain of if/else with 1600 `else if`, compilation took 2774ms

That shows two things;

- choosing `switch` over `else if` chains (almost) doesn't impact compilation time
- the more cases, the longer the compilation

So, in terms of compilation time, the approach suggested by @juj makes sense to me, with a low number of switch cases.

I'll try to get some numbers for the same experiment, with respect to stack size this time.

**Comment by bnjbvr** [comment]
Actually, with these compilation times in mind (which have been measured on the really powerful dev machine I have), it seems that compilation time would be a no-go anyways on low-end platforms like phones (before we have a baseline compiler for asm.js on Firefox, at least). So we have a strong argument in favor of splitting switch here and by doing so, we wouldn't encounter the stack size issues anyways. As a matter of fact, the series of experiments I was planning to do seems to be of lesser value, so I won't do them right now.

**Comment by kripken** [comment]
Wow, 30 seconds for 3,000 cases in a switch? Am I reading that right?

**Comment by bnjbvr** [comment]
Yes, that is the number on my machine (haswell processor with 8 cores 2.6Ghz, 16 GB of RAM). I wonder if we should limit the number of cases at asm.js validation? Or at least emit a warning telling to avoid this pattern and recompile with a more recent version of emscripten (when that's fixed in emscripten of course), to not break existing code? @lukewagner, wdyt?

**Comment by lukewagner** [comment]
Hmm, probably a good idea to first file a bug to see if there is some accidental O(n^2) algorithm in the backend or generally what the reason is.

**Comment by bnjbvr** [comment]
And that would be https://bugzilla.mozilla.org/show_bug.cgi?id=1174230

**Comment by kripken** [comment]
I have a patch that bisects switches similar to what @juj suggested earlier. This really doesn't solve the problem, though:

 * Odin AOT times are still bad. A switch with 20,000 cases is broken up into many smaller ones, and there might be some improvement, but there is also extra control flow code to move around. Total code size is enormous, and still contains lots of smaller switches instead of one big one.
 * LLVM opt times on such a switch are slow, as are our js opt times. This makes for very slow compilation times.

Overall then it is still painful even with split up switches. Perhaps the `moar` option I mentioned would avoid this, by having no switches whatsoever, but that would increase code size even more.It seems like it is not a good thing for code generators to emit switches with 20,000 cases. @juj, the only testcase I am aware of is the one you refer to - can their codegen avoid doing this, or is it necessary?

**Comment by kripken** [comment]
Some numbers on a 20,000 case switch

| max switch size | AOT time (ms) | Code Size |
|-----------------|:-------------:|:---------:|
|       none      |      5913     |   849483  |
|       8192      |      5806     |   849447  |
|       4096      |      5924     |   849429  |
|       2048      |      5905     |   849992  |
|       1024      |      6077     |   851130  |
|       512       |      6096     |   853257  |
|       256       |      6090     |   857563  |
|       128       |      5915     |   866261  |
|        64       |      6473     |   884033  |
|        32       |      7031     |   918062  |

The smaller numbers are not that interesting (max switch size of 32 is pretty ridiculous), but just to show the trend. AOT time is extremely high regardless of bisecting switches. It's basically **linear in the number of switch cases**, instead of polynomial in the max switch size.

Due to that, my patch seems only useful to avoid "too much recursion" in the browser, but not AOT times.

However, I don't see a "too much recursion" error even with a switch with 20,000 case statements, so I am not sure what value to use in the switch bisector. @juj , on what size did you see it?

**Comment by kripken** [comment]
I opened pull requests for the splitter and the test updates. Splitter is at https://github.com/kripken/emscripten-fastcomp/pull/102

**Comment by juj** [comment]
Tested the PR locally on Windows computer, and I can see it works as intended, and no more `too much recursion` error. Discussed on IRC with @kripken , and I think the new bisecting switch-cases behavior is superior to the old if-else emitting. AOT times are not improved (but not really hurt either), and there should never be a danger of recursing to kill the call stack after this (this happened in Firefox, LLVM and IE11 on the partner's test case), so it's just great. Nice job!

**Comment by kripken** [comment]
Ok, I merged those two.
