### ISSUE TITLE
code with packed struct miscompiled on x86_64-unknown-linux-gnu 

### ISSUE THREAD

**Issue by zhendongsu** [kripken/emscripten#3535]
The following code (small.c) seems to be miscompiled at -O0 and above:

```
#include <stdio.h>

#pragma pack(1)
struct S0
{
  short f0;
  int f1;
};

short a = 1;
struct S0 b = { 0, 1 };
int *c = &b.f1;

int
main ()
{
  *c &= 1;

  printf("%d\n", *c); 

  return 0;
}
```

$ emcc -v 
emcc (Emscripten gcc/clang-like replacement) 1.33.0
clang version 3.7.0 (https://github.com/kripken/emscripten-fastcomp-clang/ 2a66b5ffba63f1e36458d41fafc2874a1abf63fe) (https://github.com/kripken/emscripten-fastcomp/ e2939f6878307899c17d1a23f51ba3fe5afbe6af)
Target: x86_64-unknown-linux-gnu
Thread model: posix
Found candidate GCC installation: /usr/lib/gcc/i686-linux-gnu/4.9
Found candidate GCC installation: /usr/lib/gcc/i686-linux-gnu/4.9.2
Found candidate GCC installation: /usr/lib/gcc/i686-linux-gnu/5.1.0
Found candidate GCC installation: /usr/lib/gcc/x86_64-linux-gnu/4.4
Found candidate GCC installation: /usr/lib/gcc/x86_64-linux-gnu/4.4.7
Found candidate GCC installation: /usr/lib/gcc/x86_64-linux-gnu/4.6
Found candidate GCC installation: /usr/lib/gcc/x86_64-linux-gnu/4.6.4
Found candidate GCC installation: /usr/lib/gcc/x86_64-linux-gnu/4.7
Found candidate GCC installation: /usr/lib/gcc/x86_64-linux-gnu/4.7.3
Found candidate GCC installation: /usr/lib/gcc/x86_64-linux-gnu/4.8
Found candidate GCC installation: /usr/lib/gcc/x86_64-linux-gnu/4.8.2
Found candidate GCC installation: /usr/lib/gcc/x86_64-linux-gnu/4.9
Found candidate GCC installation: /usr/lib/gcc/x86_64-linux-gnu/4.9.2
Found candidate GCC installation: /usr/lib/gcc/x86_64-linux-gnu/5.1.0
Selected GCC installation: /usr/lib/gcc/x86_64-linux-gnu/4.9
Candidate multilib: .;@m64
Candidate multilib: 32;@m32
Candidate multilib: x32;@mx32
Selected multilib: .;@m64
INFO     root: (Emscripten: Running sanity checks)
$ 
$ emcc -O0 small.c
$ node ./a.out.js
0
 
$ clang -O0 small.c
$ ./a.out
1
$

**Comment by juj** [comment]
I believe the code is invoking undefined behavior by accessing an unaligned variable when dereferencing the pointer `c`, since that points to unaligned data. To fix this, you have to either align the data correctly to four bytes, or to tell the compiler at that point that it should expect to be reading in an unaligned pointer.

To do the second approach, try changing the line 

    int *c = &b.f1;

to

    emscripten_align2_int *c = &b.f1;

That will tell the compiler that it should assume `c` to point to data that is aligned only to two bytes, which helps it to generate the desired code.

Detecting unaligned pointer accesses is extremely costly, which is why Emscripten does not do it by default. This is a bit awkward, but you can use the `-s SAFE_HEAP=1` linker flag to add such checks in, which should cause your original code to abort at runtime and point to the issue.

**Comment by zhendongsu** [comment]
Thanks; I see.
