### ISSUE TITLE
Shallow clone?

### ISSUE THREAD

**Issue by kirbyfan64** [kripken/emscripten#3587]
I'm new to Emscripten, so forgive me if this has already been solved, or if I'm opening it up in the wrong repo.

Currently, when `emsdk install` clones a Git repo, it does a normal clone. This is inefficient because 99% of users will never need to access that repo's history. I changed the last line of the `git_clone` function in `emsdk` to read:

```python
return run([GIT(), 'clone', url, dstpath, '--depth=1']) == 0
```

This is *much* faster.

I would open a PR, but I can't find the `emsdk` script in this repo...

**Comment by juj** [comment]
I believe your 99% number was made up on the spot?

Using shallow clones will speed up things, although we do have several developers who are using emsdk to contribute to Emscripten itself, and switch between developed tags and branches, so we can't unilaterally do a shallow clone. The only choice would be to have some kind of option here. The emsdk repository lives at https://github.com/juj/emsdk , so these can be discussed there.

There is a feature request to enable cloning of tags (https://github.com/juj/emsdk/issues/34). I think these could be combined, e.g. cloning a branch would do a full clone, but cloning a tag would just shallowly clone the desired tag. How does that sound?

**Comment by kirbyfan64** [comment]
@juj Sounds neat, but it might cause a bit of confusion as to why getting the full repo takes so much longer than just a tag, whereas, to Git, they're both the same (I think... ;).

What about defaulting to a shallow clone but adding a `--dev` option that does a full clone? If someone forgets, I think you can always get the rest of the history from a shallow clone.

**Comment by kirbyfan64** [comment]
Oh, yeah:

> I believe your 99% number was made up on the spot?

Pretty much. :)

**Comment by juj** [comment]
I'm wary of changing any default behavior, since changing it to do a shallow clone can break existing continuous integration systems and documented developer workflows that different companies have already in place. I know of a number of setups where the CI scripts `emsdk install sdk-incoming-64bit`, and then `git checkout some_custom_commit/tag` to take a specific revision the developers have fixed to. That is why the current form would be good remain to be the default to not break any existing assumptions that developers have in place.

The cleanest would be to add something like a `emsdk install sdk-tag-1.30.0`, which would shallow clone (and build) only that specific tag version. That would work for new users who don't care about developing emscripten, and it would be easy to document: if one develops, install a "branch sdk", but if one just wants to use, install a "tag sdk". That sounds like it would work for everyone's needs?

**Comment by kirbyfan64** [comment]
@juj Sounds good!
