### ISSUE TITLE
Option to hide intrinsic headers

### ISSUE THREAD

**Issue by Kagami** [kripken/emscripten#3676]
Some software (e.g. [LAME](https://github.com/rbrito/lame/blob/lame3_99/configure#L15683)) tests presense of xmmintrin.h header in order to enable SSE optimizations which might be undesirable in some cases:
* It invalides asm.js in stable version of browsers
* SSE implementation in Emscripten is not complete yet, e.g. lame fails to build because of [_mm_prefetch lack](https://github.com/kripken/emscripten/issues/3050)

It's possible to patch configure script or select different arch but maybe emcc should also has option to completely disable all SIMD-related functionality while SIMD.js is not mature yet? Sorry if request is stupid.

**Comment by kripken** [comment]
I agree that since SIMD.js is still in early stages, and so emscripten support for SIMD is as well, that perhaps it might make sense to put the header itself behind a flag. (Perhaps the `SIMD` option, athough it turns on the autovectorization, and perhaps people might want SIMD enabled without it?)

What do you think, @juj and @sunfishcode ?

**Comment by sunfishcode** [comment]
I think putting `<xmmintrin.h>` behind the SIMD flag sounds reasonable.

**Comment by juj** [comment]
@Kagami : what kind of check does it do? If it performs a test compilation, then the pending SSE1 + SSE2 fixing pull request here https://github.com/kripken/emscripten/pull/3542/files#diff-24284899b4994bad5bc1b486f7126a98R10 should fix that, since it will cause `#include <xmmintrin.h>` to fail unless one also specifies `-msse` in the command line. That aligns with standard behavior when compiling to native. Then if you make sure LAME doesn't pass `-msse` when it wants to build without SSE, things should be good.

**Comment by Kagami** [comment]
Yes, it looks like simple compilation check: https://github.com/rbrito/lame/blob/lame3_99/configure#L11916-L11937
So I believe we can close this then?

**Comment by juj** [comment]
Let's close after the PR is merged and you have confirmed that it works.

**Comment by Kagami** [comment]
I built latest emscripten and emscripten-fastcomp and now lame compiles without SSE by default. Thanks!
