### ISSUE TITLE
Option to disable CLOCK_MONOTONIC

### ISSUE THREAD

**Issue by Kagami** [kripken/emscripten#3716]
Right now it's [enabled by default](https://github.com/kripken/emscripten/blob/1.34.6/system/include/libc/time.h#L86) and that cause [some problems](https://github.com/Kagami/webm.js/issues/1) in browsers which doesn't support it, e.g. Edge. FFmpeg for example [uses ifdef](https://github.com/FFmpeg/FFmpeg/blob/n2.7.2/libavutil/time.c#L58) to check the `CLOCK_MONOTONIC` availability and the only way to disable it is to patch the application source.

**Comment by Kagami** [comment]
Or probably we can just fix `emscripten_get_now` in Edge? I can see it tries to fallback to `Date.now` but that still results in wrong values in Edge. I will try to investigate what's going on.

**Comment by Kagami** [comment]
So Emscripten in `clock_gettime` [checks](https://github.com/kripken/emscripten/blob/1.34.6/src/library.js#L2519) the `CLOCK_MONOTONIC` support by calling `emscripten_get_now_is_monotonic`; since Edge doesn't have `self.performance` in Worker context it returns false and FFmpeg doesn't check the return value of `clock_gettime` which is -1 in that case.

Since it's not possible to determine the `self.performance` availability at compile time and a lot of C software I suppose use preprocessor for that type of checks, such option in Emscripten still may be useful.

**Comment by kripken** [comment]
Is ffmpeg doing something valid there? I thought that `CLOCK_MONOTONIC` being defined doesn't mean it's actually supported (and `clock_gettime` returns an error if it isn't) - the constant is just a label for a monotonic clock, that you can ask for.

**Comment by Kagami** [comment]
Probably you're right. Just thought it might be common case in real-world codebases. Thanks anyway!

**Comment by Kagami** [comment]
One more thought. Probably POSIX API is just not convenient enough in that case. You either need to do some checks at startup and set function pointer/global variable/pass argument to function or check for `EINVAL` every time function is being called which is kinda kludgy IMO.

**Comment by kripken** [comment]
A check at startup seems ok? And necessary, if you build a binary on one machine and run on another, things might be different there.

Although, probably monotonic is present everywhere so no one worries about this. The web might be different in that regard. Perhaps we could "fake" a monotonic timer using just `Date.now()`: i.e. if the new time is before the last one, start reporting offsets from that new time from that point (so the current time difference is 0, a "skip"). That might help codebases like this, but I'm not sure it's worth the risk.

**Comment by NWilson** [comment]
Just to comment on how things got the way they are, it's my fault! In our application, we _wanted_ `clock_getttime` to return a nice error code if a true monotonic clock wasn't available, because we already had code in our application to hunt for the best supported clock source, and if a monotonic clock wasn't available, to use the wall clock but with some extra logic for restarting timers if the system time jumps backwards or forwards.

So for our codebase, the current solution works well, but I can see it's not ideal for libraries that assume a monotonic clock is there. For your interest, RHEL 3 (I think!) doesn't have CLOCK_MONOTONIC, everything more recent does, so I'm not surprised people don't check the `clock_gettime` return code anymore.
