### ISSUE TITLE
SAB/atomics asm.js validation?

### ISSUE THREAD

**Issue by kripken** [kripken/emscripten#3719]
Do we expect SAB/atomics to validate as asm.js on Firefox Nightly?

We don't have any tests for this in Emscripten currently, and indeed the output does not validate, first error right now is

````
test.js:3:20 warning: asm.js type error: could not match typed array name:
test.js:3:20 warning: "use asm";var a=new global.I8Array(buffer);var b=new global.I16Array(buffer);var
test.js:3:20 warning: ....................^
````

Just wondering if we should fix that, or if the API is still changing so there's no point.

cc @lars-t-hansen @juj @mraleph

**Comment by lars-t-hansen** [comment]
In general it validates if you use it correctly.  I8Array is not a valid name though.  SharedInt8Array would be appropriate.  Eventually that will be "Int8Array", but that change will not land for a few weeks still, at the earliest.

Also see here for the full details:
https://docs.google.com/document/d/19X8Geo_7OMyyUICMvIqzEgSDms0rRMDODdMIkXIm9m0/edit?usp=sharing

**Comment by mraleph** [comment]
fwiw, it's not an error that I saw. I saw Emscripten emitting 

```js
var b = 0;
b = fe(...) // fe is Atomics.load
```

which did not validate with "intish is not subtype of int"

and 

```
Atomics_exchange(...)
```

where `Atomics_exchange` was not properly imported in the module "prologue".

**Comment by lars-t-hansen** [comment]
There were some changes to the type system recently, these landed along with Atomics.exchange if I remember correctly.  It is possible emscripten has not been updated.  For that matter, it's possible that document I referenced has not been updated either (a bad oversight if so).  Let me investigate.

**Comment by lars-t-hansen** [comment]
Yes indeed, changeset 250825 on mozilla-inbound changed the return type of many atomic ops from Signed to Intish, thus an appropriate cast will be needed.  This was in response to a bug, https://bugzilla.mozilla.org/show_bug.cgi?id=1155176, which was that even for Uint32 the type was Signed.  @juj said on that bug he would update emscripten.

The spec document I quoted still says that the return type is Signed and justifies that by "calls cannot return Intish".  So the spec document is stale relative to the code, but that reason may still be true for all I know.  Summoning @lukewagner for expert advice.

**Comment by lukewagner** [comment]
I don't know what that footnote is referring to.  I'll add that, as explained in [comment 8](https://bugzilla.mozilla.org/show_bug.cgi?id=1155176#c8), the return could actually be `int` when `Atomics.load` starts throwing on OOB instead of returning `undefined` (the spec doc seems stale on that point as well).

**Comment by juj** [comment]
Yes, pthreads should validate correctly. This is on me, I remember now that @lars-t-hansen mentioned the changed cast, and I have forgotten to update codegen to adjust. I'll fix and update our tests to check that pthreads do validate.

**Comment by juj** [comment]
Actually, I see that is only one reason for not validating, there is another issue here that comes from that my strategy at https://github.com/kripken/emscripten/pull/3705 breaks validation, namely that this code

	function AsmJsModule(stdlib, foreign, buffer) {
	  "use asm";

	  var f64View = new stdlib.F64Array(buffer);

	  function func() { return +f64View[0]; }
	  return { func: func };
	}

	var heap = (typeof SharedArrayBuffer !== 'undefined') ? new SharedArrayBuffer(0x10000) : new ArrayBuffer(0x10000);
	var F64Array = (typeof SharedArrayBuffer !== 'undefined') ? SharedFloat64Array : Float64Array;

	var global = { "Math": Math, "F64Array": F64Array };

	var view = new F64Array(heap);
	view[0] = 10;

	var fast = AsmJsModule(global, null, heap);
	console.log(fast.func());

does not validate. Thinking..

**Comment by lars-t-hansen** [comment]
@lukewagner, the footnote probably relates to http://asmjs.org/spec/latest/#return-type-annotations which admits only double, signed, float, and void as the types of return statements (and by my reading, thus as the types of functions).

Signed is a subtype of intish, but I've found subtype relationships in asm.js to be very fiddly and hard to work with, so I've probably discounted that.

Anyway the bug for throwing on OOB access (and changing the result type in asm.js) is https://bugzilla.mozilla.org/show_bug.cgi?id=1178793.  There seems to be no reason not to just implement and land this.

@juj, keep in mind that once here are no SharedTypedArray view types this will change again.  (Long aside: I'm actually not quite sure how that is going to work, since it's important that there be no run-time checks around atomic operations yet the atomic operations are only legal if the memory is shared.  But there are not going to be any syntactic indicators at view construction time that the memory is shared, since the AB/SAB will be constructed outside the asm.js module and there is only one kind of view constructor.  The best I had come up with so far was that if we syntactically observe that an atomic is used in the module then we will back-propagate a constraint so that we'll require shared memory at runtime to construct the views.  But that will break polyfills like these.  Actually, since the atomics are open-coded I'm not sure how a polyfill of atomics would work at all.  I'll record this in bug #3705 as well.)

**Comment by lukewagner** [comment]
The return type annotation is for user-defined functions.  In general, [function types](http://asmjs.org/spec/latest/#global-types) can have any [value type](http://asmjs.org/spec/latest/#value-types).

To get the syntactic shared vs. non-shared distinction, I had been thinking that the construction of the buffer would be moved into the asm.js module:
```
function f(stdlib) {
  "use asm";
  var buf = new stdlib.SharedArrayBuffer(...);
  var i32 = new stdlib.Int32Array(buf);
  ...
  return { ..., buf:buf };
}
```
This still will not allow external code to dynamically determine whether the code is using shared memory or not, but I also don't know how to do that while generating fast inline atomics like we do.

**Comment by lars-t-hansen** [comment]
@lukewagner, the idea I posted at https://github.com/lars-t-hansen/ecmascript_sharedmem/issues/20 is possibly less invasive than what you're suggesting.

**Comment by lukewagner** [comment]
Yes, I realized the above proposal simply [doesn't work](https://github.com/lars-t-hansen/ecmascript_sharedmem/issues/20#issuecomment-135777637).

**Comment by gouletr** [comment]
I'm getting this error when I load a .js file with pthread enabled (Emscripten incoming branch, commit 108797d366f4e0ee8fab90908310736665c8b103)

```
TypeError: asm.js type error: could not match typed array name
TypeError: asm.js type error: Disabled by javascript.options.asmjs in about:config
```

Will that prevent it from working properly or I can ignore this for now?

**Comment by juj** [comment]
You can ignore it for now - the effect is that performance will be lost, but it should work correctly. I am working on a fix, but that is a bit messy since it will need to do a bit of string matching, similar to how `-s PRECISE_F32=2` works (Lars says that there's also a fix to occur in Firefox Nightly side regarding the |0 casts that currently would also drop asm.js validation)

**Comment by lars-t-hansen** [comment]
@juj, that fix landed this morning (CET).  As a result the return value of the Atomics should not need to be cast after the next Nightly build.

**Comment by juj** [comment]
That sounds excellent, thanks!

**Comment by kripken** [comment]
That pull landed - is there any additional work here?

**Comment by juj** [comment]
No, this should be fixed now. Thanks for the quick review and rebase of the PR! Let me know if you still see any issue locally.
