### ISSUE TITLE
How do I stream medium latency audio from main thread? (not using OpenAL)

### ISSUE THREAD

**Issue by reduz** [kripken/emscripten#3758]
Hi, I want to mix audio in the main thread and stream it to WebAudio. Is there any example or documentation on how to do it? (I don't want to use OpenAL since most of my back-end maps better to the node layout of WebAudio)

So, some questions (some emscripten related and some not):

1) Which node do I use to stream? from what I can see [ScriptProcessorNode](https://developer.mozilla.org/en-US/docs/Web/API/ScriptProcessorNode) does this, with configurable latency.. but (as usual) documentation does not specify if it's possible to create one of such nodes with only outputs and no inputs. Can I create it without inputs and expect it to work? If not, can I somehow feed it silence and then write my own audio? Is there a recommended way?

2) How can I feed audio to this node efficiently from C++ using the EM_ASM macros? I've been told I can pass pointers and they get converted to integers, but I also need to convert from int32 to float. Any recommendations?

Thanks!

**Comment by kripken** [comment]
cc @juj

About 2: The pointer itself is an integer in JS. But you can use a pointer to ints or a pointer to floats, for example `HEAPU8.subarray(ptr, ptr+len)` gives you a slice (no copying) of uint8s, while substituting `HEAPF32.subarray(ptr/4, (ptr+len)/4)` would give you the same slice of memory but as float32s.

**Comment by cwoffenden** [comment]
You can create a `ScriptProcessorNode` with no input channels, it works just fine. The `onaudioprocess` callback you set will get called, then you just fill the `AudioProcessingEvent`'s `outputBuffer`.

For my use I did this from Emscripten using embind ([old demo here](http://www.numfum.com/cw/emscripten/xm/)). This is a custom XM player, mixing 24 channels from C++ and copying the samples in the worst possible way:
```
val ch0 = out.call<val>("getChannelData", 0);
val ch1 = out.call<val>("getChannelData", 1);
const int16_t* next = buffer + (len * 2 - 1);
for (int n = len - 1; n >= 0; n--) {
	ch1.set<int>(n, val(*next-- / static_cast<float>(INT16_MAX)));
	ch0.set<int>(n, val(*next-- / static_cast<float>(INT16_MAX)));
}
```
Still, performance is pretty good, even on low-end hardware.

**Comment by juj** [comment]
In Emscripten, the `src/library_sdl.js` has the best example of how to synthesize streaming audio. `src/library_openal.js` also does this, but it has other features in it as well, so it might be a bit more confusing to follow which of the bits refer to streaming audio.

1) We used to use ScriptProcessorNode in Emscripten SDL backend to implement audio, see https://github.com/kripken/emscripten/commit/75f82f615709421193f956c66a8b526dd8791ec7 . Like @cwoffenden mentions, it is possible to do such nodes without inputs, but only outputs. However in the end, it was concluded that ScriptProcessorNode brought more issues than fixes, so it was dropped at https://github.com/kripken/emscripten/commit/9440047e4b99425032874d870683ca4a3c833e35. The main issue was that it was only a partial solution to SDL use case, since one can't choose the sampling rate of the ScriptProcessorNode/AudioContext, but in SDL one needs to be able to, so the SPN approach would not be able to cover all SDL use cases, and the non-SPN approach would still always be needed. Since the AudioContext sampling rate is not fixed, but depends on the user's audio card on the system, the page author doesn't have control when the SPN backend is possible. Hence it was too brittle to have an apparently randomly used SPN path, and setTimeout-fallback otherwise. Also, controlling latency is easier with setTimeout than SPN, so the setTimeout approach is more flexible.

2) Here I recommend using the `--js-library` linker flag instead of the `EM_ASM` macros, since with the .js library files, it's easier to control large bodies of JavaScript and maintain data structures. The code that @cwoffenden pointed shows an embind example of marshalling `int16` sample data to WebAudio `float` data. The file `src/library_sdl.js` shows another example of how to fetch and convert the sample data to WebAudio buffers.

**Comment by reduz** [comment]
Thanks! Will check. I don't mind much using ScriptProcessorNode I guess
since my audio mixing will do the required resampling

**Comment by cwoffenden** [comment]
Just to add, in my notes on using a SPN, [AudioBuffer.copyToChannel](https://developer.mozilla.org/en-US/docs/Web/API/AudioBuffer/copyToChannel) and a `memory_view` is probably much more efficient (if you're not needing to convert interleaved data).

**Comment by juj** [comment]
I'll label this OpenAL, since it's explicitly about avoiding it. Sounds like this was resolved - is there still something that could be addressed here, or was this ok to close?

**Comment by reduz** [comment]
Oh it's allright, I managed to get it to work directly with WebAudio, thanks!
