### ISSUE TITLE
Single-build SIMD polyfill?

### ISSUE THREAD

**Issue by kripken** [kripken/emscripten#3783]
Could we experiment with an asm.js polyfill of SIMD.js that we would hotpatch in to make the performance cliff smaller and adoption easier, avoiding separate builds, sort of like we have with `Math.fround()` that we can eliminate on the client?

cc @juj @sunfishcode

**Comment by kripken** [comment]
My guess is this is not practical. We'd need to emit code that is valid asm.js, so we'd need to allocate space on the stack for each variable, and write an asm.js version of every single operation.

It seems more practical to make it easier to create two parallel builds and pick between them? The two builds need to be tested anyhow, nothing can be saved there.

**Comment by juj** [comment]
There is now a hotpatch fallback for pthreads to drop SAB+Atomics use from a pthreads-enabled build when SAB+Atomics is not supported. The hotpatching ends up looking like this with regexes: https://github.com/kripken/emscripten/commit/685fad2501206bed1e2f9ba2fc1eab6b0d299c7e , and it is far from pretty. For SIMD it would look like something similar, but I am not sure if I have the guts to even try it out.

If we did make it a compile-time option that would be transparent to the user, i.e. compiler would automatically emit `a.js` and `a.simd.js` and `a.html` would pick between the two, then I suppose we should write c libraries that implemented simd in scalar, i.e. `library_sse1.c` and `library_sse2.c` and `library_emscripten_simd.c` (or similar), since the final .bc file already has LLVM vector ops in it, and we can't easily scalarize them otherwise?

Another way would be to have the build do two builds at each step, one with `-msse`/`-msse2`/`-s SIMD=1` enabled, and another with all of them disabled. However that might make the build chain very messy, so not sure if it would be any much sensible than just having the developer manually do it.

**Comment by kripken** [comment]
With `--separate-asm`, this should be as easy as the developer building both ways, and picking the right `project.asm.js` file at runtime.

**Comment by juj** [comment]
Talked in Vidyo with @lukewagner the other day, and we discussed the potential of how wasm modules will import functions. There it sounded like it'd be possible to import in asm.js scalar implementations of SIMD functions on the fly in the future, so we could polyfill inside asm.js a missing SIMD implementation.

I suppose that is the best that we can do here for now, so closing.
