### ISSUE TITLE
emsdk doesn't support 32-bit systems

### ISSUE THREAD

**Issue by mlimber** [kripken/emscripten#3803]
*Note: I first posted this question [on the emsdk project](https://github.com/juj/emsdk/issues/39) but got no answer, so I'm trying again here.*

I see that 32-bit support was dropped as of 1.16. I'd like to see that brought back because some of my customers are stuck on 32-bit OSes. I may be willing to contribute the code to do it depending on what's involved, but perhaps it was dropped because of issues that I am not aware of.

Is it worth adding it back?

Specifically, the error message I get on Windows is:

> This version of [...]\emscripten\python\2.7.5.3_64bit\python.exe is not compatible with the version of Windows you're running. Check your computer's system information to see whether you need a x86 (32-bit) or x64 (64-bit) version of the program, and then contact the software publisher.

On the face of it, this doesn't seem like it would be a lot of work to adapt to a 32-bit system -- replace the x64 Python with x86 Python. (And so on for node, clang, etc.)

**Comment by juj** [comment]
Sorry for not noticing this on the emsdk tracker.

Emscripten SDK does still carry 32-bit python 2.7.5.3 and 32-bit node and some other tools as 32-bit. What we no longer do is build and ship 32-bit precompiled binaries of Emscripten. You should still be able to compile a 32-bit version yourself by running `emsdk install sdk-master-32bit` (or replace `master` with `incoming` for current dev branch, or with a specific version like `tag-1.34.0` to build that version as 32-bit), which should install 32-bit python, node and java, and build 32-bit version of Emscripten and LLVM/Clang/JSBackend. Have you tried that and found some issue that it did not work?

**Comment by waywardmonkeys** [comment]
I fixed at least some of the issues with using emscripten itself on 32 bit Windows last month sometime. Those fixes are all on ``incoming``.

**Comment by polkovnikov-ph** [comment]
@juj The fun part is that `emsdk install sdk-master-32bit` doesn't work on Windows because emscripten ships with 64-bit python. 2.7.5.3 is absent from python website, and I have no clue where do I get one.

With a fresh install of 2.7.5, reading `emsdk.bat` and renaming of directories, the same command results in
```
Error parsing emsdk_manifest.json!
[Errno 2] No such file or directory: 'C:/Program Files/Emscripten/emsdk_manifest
.json'
```

I guess `emsdk update` fixes this, though the message is odd.

**Comment by polkovnikov-ph** [comment]
Then the build fails with
```
-- Build files have been written to: C:/Program Files/Emscripten/clang/fastcomp/
build_master_vs2013_32
Performing a parallel build with 3 cores.
Traceback (most recent call last):
  File "C:\Program Files\Emscripten\\emsdk", line 1734, in <module>
    sys.exit(main())
  File "C:\Program Files\Emscripten\\emsdk", line 1717, in main
    success = tool.install()
  File "C:\Program Files\Emscripten\\emsdk", line 1007, in install
    success = tool.install()
  File "C:\Program Files\Emscripten\\emsdk", line 1016, in install
    success = build_fastcomp_tool(self)
  File "C:\Program Files\Emscripten\\emsdk", line 615, in build_fastcomp_tool
    success = make_build(build_root, build_type, 'x64' if tool.bitness == 64 els
e 'Win32')
  File "C:\Program Files\Emscripten\\emsdk", line 528, in make_build
    make = [find_msbuild(os.path.join(build_root, solution_name)), '/t:Build', '
/p:Configuration='+build_type, '/p:Platform='+build_target_platform, '/nologo',
'/verbosity:minimal', solution_name]
  File "C:\Program Files\Emscripten\\emsdk", line 500, in find_msbuild
    os.path.join(os.environ['ProgramFiles(x86)'], 'MSBuild/12.0/Bin/amd64'),
  File "C:\Program Files\Emscripten\python\2.7.5.3_32bit\lib\os.py", line 423, i
n __getitem__
    return self.data[key.upper()]
KeyError: 'PROGRAMFILES(X86)'
```
and without any sign of a readable message. After removing several items from `search_paths_vs2013` array and commenting `make_env['VCTargetsPath'] = ...` the build finally starts.

**Comment by polkovnikov-ph** [comment]
@juj Seems related: https://github.com/juj/emsdk/issues/2

**Comment by polkovnikov-ph** [comment]
With the distinct smell of open source system software (i.e. enormous amount of warnings, wasted disk space due to `git clone`ing whole repos that resulted in filling the remaining space on SSD with system volume and forcing me to redo everything starting from the installation of emscripten, and building several unused executables) it finally got built.

The bad part is that it doesn't work due to dependency on python, that lacks basic unicode support in 2015.
```
D:\heroku\asmjs-test>em++ -Oz -s NO_FILESYSTEM=1 -s NO_BROWSER=1 -s VERBOSE=1 --
llvm-lto 1 --closure 1 -I...\VC\include\boost index.cpp
ERROR:root:Error in evaluating C:\Users\=ї ж■а\.emscripten
 (at None): invalid syntax (<string>, line 1), text: C:\Users\=ї ж■а\.emscripten
```

**Comment by polkovnikov-ph** [comment]
Changing `EM_CONFIG` environment either directly or via `emsdk:53: emscripten_config_directory = os.path.expanduser("Z:/Otherpath")` didn't help due to
```
Exception: File F:\Program Files\Emscripten\.emscripten passed to --em-config does not exist!
```
Looks like this file should've been generated automatically at some moment, but the process failed. I hope very much this file is really needed, because I see no reason why automatically generated file may ever be required enough to deny any way to use a program.

**Comment by polkovnikov-ph** [comment]
Yep, a copy of that file and a little bit of imagination (and searcing for `optimizer.exe` that is lacking in the build) resulted in yet another non-working `em++`.

**Comment by juj** [comment]
Let me close this, since Emscripten SDK is not officially supported on 32-bit Windows. You should not download a 64-bit installer if you are trying to manually set up a 32-bit installation. I updated the documentation to clarify the confusion and the steps that one can try to set up 32-bit emsdk at https://github.com/juj/emsdk/commit/c925156ab2dfadc425cc8db953dc1023193e051e .

**Comment by polkovnikov-ph** [comment]
@juj Great, thanks.

Though it seems the absence of installer for 32-bit systems is the reason Unity can do WebGL builds only on 64-bit systems. It seems strange that 32-bit support was dropped. Everything would work just fine, the only thing needed is a simple extension to the deploy script and a bit more disk space on a server.

**Comment by juj** [comment]
Unity does their own packaging for Emscripten. The reason they do not support 32 bit is not related to this issue.

**Comment by advancedwebdeveloper** [comment]
@mlimber , @waywardmonkeys: I will be contributing to 32bit build of emscripten, on Linux and Windows

**Comment by abenelazar** [comment]
> Sorry for not noticing this on the emsdk tracker.
> 
> Emscripten SDK does still carry 32-bit python 2.7.5.3 and 32-bit node and some other tools as 32-bit. What we no longer do is build and ship 32-bit precompiled binaries of Emscripten. You should still be able to compile a 32-bit version yourself by running `emsdk install sdk-master-32bit` (or replace `master` with `incoming` for current dev branch, or with a specific version like `tag-1.34.0` to build that version as 32-bit), which should install 32-bit python, node and java, and build 32-bit version of Emscripten and LLVM/Clang/JSBackend. Have you tried that and found some issue that it did not work?

The updated command seems to be `./emsdk install sdk-upstream-master-32bit`
