### ISSUE TITLE
"malloc" crashes program

### ISSUE THREAD

**Issue by Kleshni** [kripken/emscripten#3822]
In some cases if the program tries to allocate too much memory, the following exception is thrown:

>Cannot enlarge memory arrays. Either (1) compile with -s TOTAL_MEMORY=X with X higher than the current value 16777216, (2) compile with ALLOW_MEMORY_GROWTH which adjusts the size at runtime but prevents some optimizations, or (3) set Module.TOTAL_MEMORY before the program runs.

This is the example code:

``` C
#include <stdlib.h>
#include <stdio.h>

int main(void) {
	printf("%p\n", malloc(0x0fffffff));

	return EXIT_SUCCESS;
}
```

Compiled with `emcc main.c`, it throws the expection. If `0x0fffffff` is changed to `0xffffffff`, the expected "0" is printed to the console.

The C standard requires "malloc" to return with any input:

>The malloc function returns either a null pointer or a pointer to the allocated space.

And many programs rely on this behaviour. It's especially important in case of libraries, compiled with `NO_EXIT_RUNTIME=1`, where aborted function doesn't terminate the program and can cause leaks.

**Comment by kripken** [comment]
We do have that behavior when `ALLOW_MEMORY_GROWTH` is on - then we allocate more memory from the browser when we need, and when the browser fails to do so we return 0. But when memory growth is off, we are in a kind of non-standard situation of a fixed memory size, and we've wanted a clear error for people to see when malloc fails (because it will fail far before the system runs out of memory).

But I'm open to suggestions here for something less confusing. Perhaps we should return 0 but show the current error as a logging warning?

**Comment by Kleshni** [comment]
I see at least three reasons for the returning malloc:

1. It conforms to the standard. The standard doesn't distinguish between memory lack on the system side (with `ALLOW_MEMORY_GROWTH=1`) and the environment without expanding heap.
2. Not every `malloc` is crucial for the program execution. A smart program can try to allocate a smaller array or even avoid this branch.
3. It prevents the program from a correct clean up. It's important for libraries, where failing calls can cause leaks. And a usual program can, for example, flush files or send some message to the network.

And anyway there is an inconsistency, because `malloc(0xffffffff)` currently returns 0.

>Perhaps we should return 0 but show the current error as a logging warning?

I think, this would be the perfect solution.

**Comment by juj** [comment]
I recommend we should fix to return 0 on malloc failure, and print a warning. Aborting on OOM is very helpful, especially when new developers are learning about `TOTAL_MEMORY` and the heap behavior, so perhaps we could keep a build flag that controls malloc failure behavior (silent, log warning, or abort), with log warning being the default?

**Comment by kripken** [comment]
My worry is that a lot of code out there is **not** smart about mallocs, and assumes mallocs always succeed, because a program that needs say 128MB of RAM gets it 100% of the time on a desktop machine. Those programs will fail in hard to debug ways, unless they look in the log **and** the warning is close enough to the bottom (the malloc might be followed by other warnings that push it up).

A malloc can also fail inside of libc, causing some libc method people assumes always works to fail.

For those reasons I think we should have an option as @juj says, but the default should be aborting.

**Comment by juj** [comment]
A malloc should not fail in libc in a way that libc is not prepared to handle. (by setting errno or similar defined behavior)

I'd be ok with defaulting to abort, instead of logging a warning.

**Comment by NWilson** [comment]
If I can chip in with an opinion, I too would prefer `malloc()` to fail hard (with an abort) if the allocation is not possible. Many applications can't really cope with malloc failures, since reasonably-sized allocations almost always succeed on modern OSes. Instead the OOM killer kills off processes after the fact, when swap is exhausted, and malloc only fails for impossibly large input values.

If malloc did return NULL in emscripten, that would be OK too, but aborting the emscripten application is an equally valid choice, since there's not much you can do when memory allocation fails: realistically you have to abort anyway. (Certainly, it's not portable to attempt to allocate increasingly large chunks of data to "detect" the optimum amount of memory to use. This would cause terrible swap thrashing. For applications which can scale their memory use to take into the account system's amount of RAM, emscripten could provide a proper call that returns the compiled-in limit. I guess applications that do this expect the data to be available through `/proc`?)

Aborting doesn't exactly cause "leaks", the entire application just dies with all resources invalidated in potentially inconsistent states. Any application which uses NO_EXIT_RUNTIME should check the `ABORT` variable before calling into emscripten as the bottom-most function on the stack, so that the application doesn't come back from the dead by mistake.

**Comment by kripken** [comment]
Ok, sounds good, I think the agreed plan is to add an option for fallible malloc, defaulting to 0 which is the current aborting behavior. Perhaps `FALLIBLE_MALLOC`? When set to 1, malloc would fail with 0 as per the C spec.

I think this is as easy as editing `enlargeMemory` in `src/preamble.js`, where it aborts if memory growth is off. (When memory growth is on, we are already doing the proper behavior according to the spec.)

**Comment by The-Humanoid** [comment]
Most of us expect correct behaviour from the start.  Having to search for and read the descriptions of every option in order to hunt and find every option (like FALLIBLE_MALLOC) that we need to change for correct behaviour is not cool at all.

Having correct behaviour is important because those of us who write correct code and check malloc's return value don't want to see the console littered with hundreds of error messages regarding running out of memory.  And we especially don't want our program to be aborted by malloc.  It's not malloc's job to do that, and has never been in the decades that it existed.  There's a reason why malloc's documentation says that it returns a null pointer when there's not enough memory, because people who call malloc want to KNOW wether or not the allocation was successful, and we don't want it to abort our program.

If you really want the default behaviour to not be correct, put it into a single global CORRECT_BEHAVIOUR option, and make it clear in the documentation that emscripten does not behave correctly by default, and that we need to turn CORRECT_BEHAVIOUR on in order to get correct behaviour.

Correct behaviour should work the same whether or not ALLOW_MEMORY_GROWTH is turned on or off.  There is a reason to want to turn it off, and that's because of the performance issue.  So we may want to set a fixed amount of ram, but still expect correct behaviour with malloc telling us that there's not enough ram, rather than having the console littered with error messages, or worse having our program aborted.

**Comment by kripken** [comment]
I fully agree that having to search for and read every option, like the proposed `FALLIBLE_MALLOC` is something to avoid. When implementing `FALLIBLE_MALLOC`, the default aborting behavior should very clearly mention that option as well as `ALLOW_MEMORY_GROWTH` (which it already does).

But for the reasons mentioned above, I don't think we can make `FALLIBLE_MALLOC` on by default. The main issue is that the web is a very nonstandard target in that we are forced to allocate all memory up front (since Chrome is still slow on memory growth), and people allocate the smallest possible sizes there (since large allocations often fail, especially on 32-bit browsers and especially on 32-bit Chrome), and so failing mallocs are much much more likely than on other typical OSes. And we know of a lot of real-world code that can break in odd ways on that. It's preferable for some code to break in a clear way - an abort with a message "flip this option to get fallible malloc if you want that", the dev would only ever see it once - vs odd hard to debug ways.

**Comment by The-Humanoid** [comment]
> the dev would only ever see it once

That's **if** the dev ever sees it.  It might be that he never sees it on his own machine since he doesn't try loading a large amount of data when he's testing the program (knowing that his code correctly handles running out of memory).  But then a client/user of the program is the first one to see it!

I saw the error message myself, and feel lucky that I saw it sooner rather than too late!

I don't see anything "nonstandard" about allocating all memory up front.  Computers come with a fixed amount of ram, and when the OS has virtual memory support, there's still a fixed amount of storage space.  Running out of ram is very common.

**Comment by The-Humanoid** [comment]
Also, if you insist on having an option specific for malloc, do not call it FALLIBLE_MALLOC, because malloc failing is what is considered normal.  So instead, invert the value, and call it ABORTING_MALLOC so that it describes the way in which normal malloc is modified, rather than describing what a normal malloc does.

**Comment by kripken** [comment]
I agree, that is a serious risk if the dev never sees it, and the code running on a client allocates more than on the dev's machine.

But I do think it's a mitigating factor here that we have a low default memory, 16MB. We want it low because we don't want people leaving the default and wasting memory all over the web. But a side benefit of it being so low is that people tend to run into that limit and see that abort.

`ABORTING_MALLOC` does sound like a better name, thank you. Let's go with that.

**Comment by kripken** [comment]
Pushed to incoming.

Btw, I am fine with an option like `CORRECT_BEHAVIOUR` which was suggested before, that would flip this on and other options as well if they are similar deviations from the standard. E.g., it would turn on `PRECISE_F32` and so forth, despite the perf downsides, etc. Please file a new issue for that though.
