### ISSUE TITLE
O_CLOEXEC doesn't work on NODEFS

### ISSUE THREAD

**Issue by Kagami** [kripken/emscripten#3862]
Hi. The following code:

```js
#include <stdio.h>
#include <errno.h>
#include <string.h>
#include <fcntl.h>
#include <emscripten.h>

int main(void)
{
    EM_ASM(
        FS.close(FS.open("/test1", "w+"));
        FS.mkdir("/test2");
        FS.mount(NODEFS, {root: "."}, "/test2");
    );
    int fd1 = open("/test1", O_RDONLY | O_CLOEXEC);
    printf("%d %s\n", fd1, strerror(errno));
    int fd2 = open("/test2/cloexec.c", O_RDONLY | O_CLOEXEC);
    printf("%d %s\n", fd2, strerror(errno));
    return 0;
}
```

produces the following output:

```
$ emcc cloexec.c && node a.out.js 
3 No error information
-1 Invalid argument
```

on Emscripten 1.34.12. As you can see, it's possible to open file at MEMFS with `O_CLOEXEC` flag defined, but not at NODEFS.

[This code](https://github.com/kripken/emscripten/blob/1.34.12/src/library_nodefs.js#L49-L82) is responsible for that: there is no `02000000` entry defined in permissions map. It couble be easily fixed similar to `O_LARGEFILE` but maybe you know what's the reason for that? I think I was able to run the same application with Emscripten 1.34.6 (haven't checked the example code yet because it takes rather long time to recompile llvm).

**Comment by Kagami** [comment]
Ah, found it. [This recent commit](https://github.com/kripken/emscripten/commit/b135a8aecd5e7d797db7a1ecadb41ebb8922ddc0) enforces `EINVAL` for all unknown flags.

Can we be a bit more forgiving? Or at least add support for missed flags? (I'm primarly interested in `O_CLOEXEC` since it's what my application uses.)

**Comment by kripken** [comment]
@juj, do you remember the full background there?

IIRC, we had a windows-specific issue, and decided to be very careful about what we let through. Safest seems to just directly add `OC_CLOEXEC`?

**Comment by juj** [comment]
Very sorry about the regression @Kagami !

The reason why we added the `EINVAL` was because the way that function is crafted, it is a map lookup, rather than a identification bit by bit. This means that a single unknown bit can cause the whole map lookup to fail, and notice how the previous code at https://github.com/kripken/emscripten/commit/b135a8aecd5e7d797db7a1ecadb41ebb8922ddc0#diff-8b6bab9e0fdb975150c5cd7e939a76d5L79 would just return the input bitfield (number) unmodified on an unknown input, when the role of that function should be to always return a flags combination (string).

The reason why it worked before on unixes is that node.js apparently is forgiving on its filesystem api and as undocumented behavior, supports file open to take in a bitfield number instead of a flags combination string, but only on unixes. The same undocumented behavior does not work on Windows.

Adding support to yet unsupported flags sounds ok (e.g. as explicit known ignores like `O_LARGEFILE` is already treated), but we don't want to return to the old behavior before the commit https://github.com/kripken/emscripten/commit/b135a8aecd5e7d797db7a1ecadb41ebb8922ddc0#diff-8b6bab9e0fdb975150c5cd7e939a76d5L79 which relies on the undocumented filesystem open behavior. Can you submit a PR @Kagami ?

**Comment by Kagami** [comment]
Done, #3864.
