### ISSUE TITLE
Error: WebGL: drawBuffers: invalid <buffers> (buffers must not be empty)

### ISSUE THREAD

**Issue by gouletr** [kripken/emscripten#3890]
This is WebGL2 code. I am getting this error in Firefox Nightly when calling `glDrawBuffers(0, nullptr)`. Technically, this should be allowed per [the GLES3 documentation for glDrawBuffers](https://www.khronos.org/opengles/sdk/docs/man3/html/glDrawBuffers.xhtml). They says:

> The draw buffer used for user defined outputs assigned to locations greater than or equal to n is implicitly set to GL_NONE and any data written to such an output is discarded.

which basically means all the draw buffers should be set to `GL_NONE` in that case. I am wondering if this is an issue with how Emscripten translate this to JavaScript corresponding call, or if its a wrong report in Firefox Nightly?

Here's the code in Emscripten:
```javascript
  glDrawBuffers__sig: 'vii',
  glDrawBuffers: function(n, bufs) {
#if GL_ASSERTIONS
    assert(GLctx['drawBuffers'], 'Must have WebGL2 or WEBGL_draw_buffers extension to use drawBuffers');
#endif
    var bufArray = [];
    for (var i = 0; i < n; i++)
      bufArray.push({{{ makeGetValue('bufs', 'i*4', 'i32') }}});

    GLctx['drawBuffers'](bufArray);
  },
```
I'm not much familiar with JavaScript, but could it be that passing an empty array is not valid behavior?

**Comment by juj** [comment]
Ugh, reading the GLES3 spec at https://www.khronos.org/registry/gles/specs/3.0/es_spec_3.0.0.pdf (section 4.2.1), it has the following two statements: 

   - If the GL is bound to the default framebuffer, then n must be 1 and the constant must be BACK or NONE.

   - In both cases [GL is bound to default framebuffer, or GL is bound to a framebuffer object], the draw buffers being defined correspond in order to the respective fragment colors. The draw buffer for fragment colors beyond n is set to NONE.

Therefore one can conclude that passing `n=0` is only valid in native `glDrawBuffers` when a FBO is bound, and that would translate to `gl.drawBuffers` accepting an empty array only if a FBO is set. One can experiment with the following code:

	<html><body>
	<canvas id="c" width="64" height="64"></canvas>
	<script>
	var gl = document.getElementById('c').getContext('webgl2');
	gl.drawBuffers([]); // Empty array when no FBO, should not be accepted.

	var fb = gl.createFramebuffer();
	gl.bindFramebuffer(gl.FRAMEBUFFER, fb);
	gl.drawBuffers([]); // Empty array when with FBO, should be accepted.
	</script>
	</body>
	</html>

should generate one error only, but in FF Nightly, it generates an error in both cases. The WebGL 2 specification does not have a special wording regarding this. Given that the GLES3 spec is so obtuse here, it's probably best to validate and enforce this directly in Emscripten.

**Comment by gouletr** [comment]
Thanks @juj ! Perhaps we should file a bug to mozilla so that we don't have to keep this work-around forever?

**Comment by juj** [comment]
A more precise workaround:

	<html><body>
	<canvas id="c" width="64" height="64"></canvas>
	<script>
	console.log('case no fbo:');
	var gl = document.getElementById('c').getContext('webgl2');
	while(gl.getError() != 0) gl.getError(); // flush
	gl.drawBuffers([]); // Empty array when no FBO, should not be accepted.
	console.log('gl error: ' + gl.getError()); // Should have an error


	console.log('case yes fbo:');
	var fb = gl.createFramebuffer();
	gl.bindFramebuffer(gl.FRAMEBUFFER, fb);
	while(gl.getError() != 0) gl.getError(); // flush
	gl.drawBuffers([]); // Empty array when with FBO, should be accepted.
	console.log('gl error: ' + gl.getError()); // Should not have an error
	</script>
	</body>
	</html>

**Comment by juj** [comment]
Reported https://bugzilla.mozilla.org/show_bug.cgi?id=1221077 .

**Comment by gouletr** [comment]
Thanks!

**Comment by kvark** [comment]
The test case works properly in FF nightly now.

**Comment by juj** [comment]
Thanks for checking this @kvark ! Dropping the workaround in Emscripten since not needed anymore.
