### ISSUE TITLE
issue or not  : compiler does not export default parameter

### ISSUE THREAD

**Issue by claudiodaffra** [kripken/emscripten#3942]
about this line of code ...

	extern "C"
	char * php_load ( const char *id,const char *fn,
					  const char *url="http://localhost/em/server/file.read.php" )
	...

follow by this cmd line :

	em++ main00.cpp -o main.js -std=c++11 -s EXPORTED_FUNCTIONS="['_php_load']"

and then in javascript :

	php_load = Module.cwrap('php_load', 'number' , ['string','string','string']);

to finish there is not the management of default parameters

i have to add line of code, in c++ source ,

	if (url==NULL) url = (const char*)"http://localhost/em/server/file.read.php" ;

**Comment by kripken** [comment]
Fundamentally, C does not have default parameters. So that function is exported as C, but it's only valid C++. I'm not sure how internally C++ handles default parameters, but I would guess at the ABI level, it would not just work with calling from JS - we would need to add special support, if that's practical.

Instead, adding a check in the C++ source code, as you did, seems the right solution, so I think that is the proper approach and we can close this.
