### ISSUE TITLE
Recent SIMD changes

### ISSUE THREAD

**Issue by kripken** [kripken/emscripten#3980]
Recent SIMD updates in the spec have arrived in SpiderMonkey on mozilla-inbound. Checking emscripten against that, we need to do some changes. These are the main things that are now different:

* The comparison operators will return a Bool32x4 vector instead of Int32x4. We need to import Bool into the asm module, and to make the backend emit locals with that type, as the output of comparisons. Or we could immediately cast them to an Int32x4, and cast back for a select, etc.? I see we have `castIntVecToBoolVec` and vice versa, perhaps the solution lies there?
* The select functions will expect a Bool32x4 instead of Int32x4 as the mask argument. They will throw a TypeError if you pass an Int32x4. Related to previous issue.
* The signMask property is going away. It has been replaced by the allTrue / anyTrue functions on boolean vectors.
* The .x/.y/.z/.w properties are going away. Use the extractLane functions instead.

cc @juj

**Comment by kripken** [comment]
Some easy fixes are in #3981

**Comment by stoklund** [comment]
The same change also removed the bitwise operators (and, or, xor, not) from Float32x4. I don't think Emscripten uses those.

**Comment by bnjbvr** [comment]
> The .x/.y/.z/.w properties are going away. Use the extractLane functions instead.

This should have been fixed and landed a long time ago in Spidermonkey, so this shouldn't be necessary to fix now.

**Comment by juj** [comment]
I think the SIMD.js changes will be in tomorrow's nightly, I'll start testing on that. Our SIMD.js codegen has not been using the member accessors since the recent SSE2 work, `extractLane` and `replaceLane` are already in use, so that should be ok. The new `BoolXxY` types will need a bit of work. My initial thought there is to start generating code that has the Bool types, and not immediately cast on operations. Since LLVM has the Bool vectors already, this should be straightforward. Iirc we don't use `signMask` anywhere. There does exist the intrinsic `emscripten_float32x4_signmask`, but that can be just erased.

**Comment by juj** [comment]
This was resolved in the above PRs, plus a few in fastcomp side.
