### ISSUE TITLE
libstdc++6 breaks emscripten (Debian package)

### ISSUE THREAD

**Issue by KeyboardFire** [kripken/emscripten#3989]
When I try to install emscripten via `aptitude` (`apt-get` complains as well):

    root@llama:/home/llama# aptitude install emscripten
    The following NEW packages will be installed:
      emscripten libandroid-json-org-java{a} libargs4j-java{a} 
      libatinject-jsr330-api-java{a} libclosure-compiler-java{a} 
      libguava-java{a} libjsr305-java{a} 
    0 packages upgraded, 7 newly installed, 0 to remove and 0 not upgraded.
    Need to get 27.7 MB of archives. After unpacking 103 MB will be used.
    The following packages have unmet dependencies:
     libstdc++6 : Breaks: emscripten (<= 1.22.1-1) but 1.22.1-1 is to be installed.
     libstdc++6:i386 : Breaks: emscripten (<= 1.22.1-1) but 1.22.1-1 is to be installed.
    The following actions will resolve these dependencies:

         Keep the following packages at their current version:
    1)     emscripten [Not Installed]

Also:

    root@llama:/home/llama# aptitude why-not emscripten
    i   libstdc++6 Breaks emscripten (<= 1.22.1-1)

It appears that emscripten's Debian package has some sort of conflict with `libstdc++6`, for some reason.

**Comment by juj** [comment]
We do not develop or maintain linux distro packages, I'm unsure who authored the Debian package or if he follows this bug tracker. If not, I'm inclined to close this as unsupported - perhaps there is a more official bug tracker somewhere for Debian package bugs?

The official method of installing Emscripten on linux is to get the Emscripten SDK:

    wget https://s3.amazonaws.com/mozilla-games/emscripten/releases/emsdk-portable.tar.gz
    tar -xvf emsdk-portable.tar.gz
    cd emsdk-portable
    ./emsdk install latest

If you want a development branch instead of a tagged release, you can replace `latest` with some other sdk targets, see `./emsdk list` for details.

**Comment by KeyboardFire** [comment]
Ah, okay. I wasn't aware of that. I used the SDK instead; thanks!

**Comment by pwaller** [comment]
This was reported downstream as [bug 809997](https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=809997) in the debian bug tracker.
