### ISSUE TITLE
webidl test expected output not checked ?

### ISSUE THREAD

**Issue by andreasplesch** [kripken/emscripten#3995]
After replacing files
``` 
output_ALL.txt
output_FAST.txt
output_DEFAULT.txt
```
in the tests/webidl folder with empty files of the same name, running
```python tests/runner.py test_webidl```
still finishes successfully with an 'ok'. Are these file supposed to contain the expected outputs ?

**Comment by kripken** [comment]
Yes, but a potentially confusing thing is that we check that the expected output is *contained* in the seen output. That allows the seen output to have additional things that we don't test, and is useful in some tests like where there are absolute pointer offsets, etc.

If you modify those files instead of clearing them, you should see an error.

**Comment by andreasplesch** [comment]
Ah, ok, this makes sense now. I tested by modifying the first line of output_DEFAULT.txt and the test did report an appropriate error.
