### ISSUE TITLE
Module.HEAPF32.set RangeError: Source is too large

### ISSUE THREAD

**Issue by noamtcohen** [kripken/emscripten#4003]
Hi, this is the code I'm running, and I get a this error: `RangeError: Source is too large`
```
var samples = new Float32Array(1024);
var buffer = Module._malloc(1024*4);
Module.HEAPF32.set(samples, buffer);
Module._free(buffer);
```
Could you explain to me what I'm doing wrong?
Thanks.

**Comment by juj** [comment]
This looks like a bytes versus indices problem. Try

    var samples = new Float32Array(1024);
    var buffer = Module._malloc(1024*4);
    Module.HEAPF32.set(samples, buffer >> 2);
    Module._free(buffer);

**Comment by noamtcohen** [comment]
Can you please explain this to me?

**Comment by juj** [comment]
The `malloc` function returns pointer to a memory address, but the typed array `.set()` function takes as the second parameter an index to the array that is being set. The index value refers to units of float32 (4 bytes in size) since `HEAPF32` is a `Float32Array`, so the memory address needs to be divided by four. See the diagram on this page for an illustration: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Typed_arrays

**Comment by noamtcohen** [comment]
Thanks. got it.

**Comment by noamtcohen** [comment]
I'm trying to compile an audio re-sampler, but for some reason the total number of samples processed is always 0. Could you take a look, maybe I'm not compiling correctly: https://github.com/noamtcohen/DigiResampler

**Comment by juj** [comment]
Sorry, it looks a bit too wieldy to start digging into a full codebase to debug. Perhaps try adding `console.log()` traces to both sides of the relevant function calls in C and JS code to see why it might be passing a zero value? Possibly the function call doesn't pass enough values so the remaining function parameters all come out `undefined` which becomes zero in arithmetic?

**Comment by noamtcohen** [comment]
Thanks,  I had to learn a bit more on how to use emscripten and there where a few mistakes in the way I was using the code. After a bit of digging I got this working. Thanks again for your help.
