### ISSUE TITLE
accessing memory outside the emscripten module without copying

### ISSUE THREAD

**Issue by soliton4** [kripken/emscripten#4050]
in broadway.js one of the biggest time consumers is memory copying.
is there a way to give a c function access to a arraybuffer memory without copying it?

one hack to do so could be to change the arraybuffer variable used inside asm.js
i am not sure i know what i am talking about thou.

any insights would be appreciated very much

**Comment by kripken** [comment]
JS can access the emscripten memory by just referring to the HEAP views. But giving compiled code access to outside array buffers is not possible in asm.js, because it's hard to optimize.

However, this can be done without asm.js,

https://github.com/kripken/emscripten/wiki/Split-Memory

In almost all cases that is going to be slower, though. Unless the copy is the only significant factor and nothing else.

**Comment by soliton4** [comment]
thx for the reply. and yes i pretty much knew that already.

if you want to access incoming stream data it could be a significant performance boost if you could access that data from within asm.js

maybe instead of addressing this here i should talk to the asm.js team?

**Comment by kripken** [comment]
I don't think it's likely this will change in asm.js - browser vendors are focused on WebAssembly, going forward. asm.js is actually losing features (like memory growth recently).

For WebAssembly, similar things are already on the roadmap,

https://github.com/WebAssembly/design/blob/master/GC.md#javascript-integration

It might be useful to suggest specifically adding typed arrays there.

**Comment by juj** [comment]
Hey, stumbled on to this after a while. @soliton4: would be nice to have some standalone benchmark of broadway.js decoding. Any chance you'd have some available already?
