### ISSUE TITLE
libcxx does not use exceptions even with -s DISABLE_EXCEPTION_CATCHING=0

### ISSUE THREAD

**Issue by k21** [kripken/emscripten#4053]
libcxx seems to be compiled without support for exceptions. Steps to reproduce:
```
$ emcc --clear-cache # just to be sure
WARNING:root:clearing cache
INFO:root:(Emscripten: Running sanity checks)
$ cat main.cpp 
#include <string>
#include <iostream>
#include <stdexcept>

int main() {
  std::string s;
  try {
    std::cout << s.at(0) << std::endl;
  } catch (const std::out_of_range& e) {
    std::cout << "Exception caught:" << std::endl;
    std::cout << e.what() << std::endl;
  }
  return 0;
}
$ em++ -s DISABLE_EXCEPTION_CATCHING=0 main.cpp -o a.js
WARNING:root:generating system library: libcxx.a...
WARNING:root:                                      ok
WARNING:root:generating system library: libcxxabi.bc...
WARNING:root:                                          ok
WARNING:root:generating system library: libc.bc...
WARNING:root:                                     ok
WARNING:root:generating system library: dlmalloc.bc...
WARNING:root:                                         ok
$ node a.js 
warning: a problem occurred in builtin C++ name demangling; build with  -s DEMANGLE_SUPPORT=1  to link in libcxxabi demangling

/home/k21/tmp/a.js:97
      throw ex;
      ^
Assertion failed: !"basic_string out_of_range", at: /home/k21/projects/ext/emsdk/emscripten/master/system/include/libcxx/string,1175,__throw_out_of_range at Error
    at jsStackTrace (/home/k21/tmp/a.js:1173:13)
    at stackTrace (/home/k21/tmp/a.js:1190:22)
    at ___assert_fail (/home/k21/tmp/a.js:1644:210)
    at __ZNKSt3__121__basic_string_commonILb1EE20__throw_out_of_rangeEv [??_()] (/home/k21/tmp/a.js:9113:2)
    at Array.__ZNSt3__112basic_stringIcNS_11char_traitsIcEENS_9allocatorIcEEE2atEj [??_()] (/home/k21/tmp/a.js:25316:3)
    at Object.dynCall_iii (/home/k21/tmp/a.js:66269:39)
    at invoke_iii (/home/k21/tmp/a.js:6438:33)
    at _main (/home/k21/tmp/a.js:6784:9)
    at Object.asm._main (/home/k21/tmp/a.js:66817:19)
    at Object.callMain (/home/k21/tmp/a.js:66984:30)
$ echo $?
7
```

Expected behavior (reproduced with clang):
```
$ clang++ main.cpp -o a.out
$ ./a.out 
Exception caught:
basic_string::at: __n (which is 0) >= this->size() (which is 0)
$ echo $?
0
```

The output of `emcc -v`:
```
$ emcc -v
emcc (Emscripten gcc/clang-like replacement + linker emulating GNU ld) 1.35.0
clang version 3.7.0 (https://github.com/kripken/emscripten-fastcomp-clang/ dbe68fecd03d6f646bd075963c3cc0e7130e5767) (https://github.com/kripken/emscripten-fastcomp/ 4e83be90903250ec5142edc57971ed4c633c5e25)
Target: x86_64-unknown-linux-gnu
Thread model: posix
Found candidate GCC installation: /usr/lib/gcc/x86_64-linux-gnu/4.8
Found candidate GCC installation: /usr/lib/gcc/x86_64-linux-gnu/4.8.4
Found candidate GCC installation: /usr/lib/gcc/x86_64-linux-gnu/4.9
Found candidate GCC installation: /usr/lib/gcc/x86_64-linux-gnu/4.9.2
Selected GCC installation: /usr/lib/gcc/x86_64-linux-gnu/4.9
Candidate multilib: .;@m64
Selected multilib: .;@m64
INFO:root:(Emscripten: Running sanity checks)
```

**Comment by k21** [comment]
This is the source code of the function from `/home/k21/projects/ext/emsdk/emscripten/master/system/include/libcxx/string` that should throw the exception:
```c++
template <bool __b>                                                                  
void                                                                                 
__basic_string_common<__b>::__throw_out_of_range() const                             
{                                                                                    
#ifndef _LIBCPP_NO_EXCEPTIONS                                                        
    throw out_of_range("basic_string");                                              
#else                                                                                
    assert(!"basic_string out_of_range");                                            
#endif                                                                               
}
```

It looks like when libcxx is compiled for Emscripten, `_LIBCPP_NO_EXCEPTIONS` is defined and the compiled code is hitting the `assert` branch. This macro is defined in multiple places in `/home/k21/projects/ext/emsdk/emscripten/master/system/include/libcxx/__config` like this:
```c++
#if !(__has_feature(cxx_exceptions))                                                
#define _LIBCPP_NO_EXCEPTIONS                                                       
#endif

[...]

#if !__EXCEPTIONS                                                                
#define _LIBCPP_NO_EXCEPTIONS                                                    
#endif
```

**Comment by kripken** [comment]
Thanks for reporting. This turned out to be a subtle issue, in which libc++abi disables libc++ exceptions internally - at least it thinks it does. But then since the header methods, like the one throwing an exception here, is linked weakly, it ends up overriding the one built with the exceptions-enabled libc++.

In other words, this ends up being complicated because of c++ weak linking, exceptions, and that we do static linking for maximal code size reduction.

To fix this, I made libc++ link in last.

**Comment by k21** [comment]
Awesome, thanks for the quick fix!

Just out of curiosity, wouldn't it be safer to have multiple versions of `libc++abi` and choose one of them based on whether exceptions are enabled or not, like it is done for `libc++`? It looks like with the current fix there is code in `cxa_demangle.cpp` that goes out of its way to disable exceptions, but it is then linked to code that might throw an exception anyway.

**Comment by kripken** [comment]
Yes, good question. I considered that but I don't think it would work: libc++abi is actually using the same methods from the `string` header as libc++ is. So we can't have both exceptions and non-exceptions versions linked in at the same time, unless we disable weak linking for those symbols, which is (1) bad for code size, and (2) risky, I hardly understand c++ linking as it is ;) In other words, even if we have libc++abi versions with exceptions and without, the `string` code they run will be weakly linked/merged with other code anyhow.

The reason I believe the current solution is correct is that libc++abi doesn't actually require that exceptions be off in order to work. It uses some strings, and they don't need exception handling for them, because their usages are very basic, they don't throw themselves, and if an error occurs in that low-level code, there isn't anything to be done anyhow. So they disabled libc++ exceptions there. Which is fine, if the libraries are statically linked. For us, we'll just have that code in libc++abi be run against exception-enabled libc++ (when exceptions are on).

The biggest risk is that what once would throw an assert due to an internal libc++abi problem will instead throw a full C++ exception. Which in theory could be caught by something outside, which would be "wrong". But a libc++abi error is already game over. And we do have full guaranteed stack traces when debugging exceptions (from the JS runtime) so this should not be too hard to figure out, if it happens.

cc @juj for his thoughts.

**Comment by juj** [comment]
Alon's analysis sounds ok to me. If there does come up a case that would warrant adding libc++abi both with and without exceptions, then that should be ok as well and we could add that, however I agree that this should not be necessary.
