### ISSUE TITLE
Recent breakage in browser.test_locate_file and browser.test_in_flight_memfile_request

### ISSUE THREAD

**Issue by kripken** [kripken/emscripten#4055]
````
9576b490c7fb1351d66ed06b6536addfbde1ac42 is the first bad commit
commit 9576b490c7fb1351d66ed06b6536addfbde1ac42
Author: Jukka Jylänki <jujjyl@gmail.com>
Date:   Mon Jan 18 21:24:14 2016 +0200

    Once the memory initializer file .mem.js has been applied, make sure that all references to it are released so that the GC can reclaim the memory used by the memory initializer typed array.
````

This broke two browser tests for me locally, `browser.test_locate_file` and `browser.test_in_flight_memfile_request`.

Do the bots just warn about browser errors now?

**Comment by juj** [comment]
Thanks, and sorry, should have caught this before! Fixed in above commit.

The bots were changed to generate only warnings about the browser run since we got the bad Firefox bug which broke the per-pixel reftests. That issue has since been fixed, so we should definitely work towards making the browser tests report failure correctly. Looking into that now.

**Comment by kripken** [comment]
Great, thanks!
