### ISSUE TITLE
x11 support

### ISSUE THREAD

**Issue by chepilot** [kripken/emscripten#4071]
Hi, 
It may be a dumb question, I am trying to build something with cmake using emscripten cmake toolchain, it depends on X11 on OSX itself. Does it mean if emscripten doesn't fully support X11(I think it is the case now), I won't be able to build it this way?

What happens to me is that when I try to cmake the project normally without emscripten, it can find x11, freeType, but when I use the toolchain, it can't find all the x11 lib and include path, it can only find those in the emscripten include folder.

Thanks!

**Comment by kripken** [comment]
The tricky thing is that emscripten is a cross-compiler - it can't use the local libraries like X11, freetype, etc.

We do have a port of freetype that you can use, and there is some limited X11 support. But you have to use those directly - we don't have a way for cmake to automatically work, since it looks in the local system, and not in our libraries.

**Comment by chepilot** [comment]
Thanks, I try to read through the emscripten toolchain and roughly get the idea. Then I actually put the X11 includes in the `emscripten include`, then manually link the X11 libs, I don't know why but the result works.

**Comment by DevScholar** [comment]
Hi, I am trying to implement x11 support in Emscripten.
https://github.com/DevScholar/em-x11

<img width="540" height="294" alt="Image" src="https://github.com/user-attachments/assets/77e2f5e0-264e-4b2a-8d68-a6f85f5125a6" />

**Comment by sbc100** [comment]
@DevScholar looks like you are having some success!   Very cool

**Comment by DevScholar** [comment]
Now this project can run more programs. 

In fact, the results of this project shown in the picture were completely written using Claude Opus 4.7 in less than a week. Although most open-source projects reject AI-generated code, and the EmX11 project is still in the Pre-Alpha stage, I hope that in the future the Emscripten project can officially support X11.

<img width="493" height="675" alt="Image" src="https://github.com/user-attachments/assets/077fb26d-32fb-4f6c-9c3c-9972a3675b6e" />

<img width="572" height="348" alt="Image" src="https://github.com/user-attachments/assets/b03635ec-642b-4410-80b5-aa801259995e" />

**Comment by sbc100** [comment]
> Although most open-source projects reject AI-generated code

I don't think that is true.  Maybe there are a handfull that completely reject it, but most open source projects I know of will accept AI assisted code as long it passed the quality bar, and has the correct license.

**Comment by sbc100** [comment]
If you have fixes or improvements for our builtin xlib support (src/lib/libxlib.js) they would be most welcome.

**Comment by DevScholar** [comment]
Hi, I want to know whether the EmX11 project is suitable for merging into the Emscripten project itself or whether it is better maintained as an independent project. Since EmX11 is written using AI, its coding standards, quality, API style, and so on may not match the requirements of the Emscripten project. Moreover, the Emscripten project does not have documentation on how to handle third-party projects that attempt to complement the functionality of Emscripten, especially in cases where third-party projects try to complement special cases like Stubs. There is also no dedicated documentation on how to make third-party projects align as closely as possible with Emscripten's own code style and requirements.

I mention this because the Pyodide official team invited me to add my PyodideTK project to their organization, which made me think of this issue.

<img width="835" height="673" alt="Screenshot of TWM, xeyes, xcalc and glxgears" src="https://github.com/user-attachments/assets/d6891bd2-8de3-4834-a116-79f1d31d9f0f" />

**Comment by sbc100** [comment]
I this code quality is questionable then perhaps we could incubate it as an external project?    I could then consider merging into emscripten later.

I terms of answering the questions around how to maintain external projects that integrate well with emscripten, I think doing so in this case would help us flesh out some of the anwsers.  For example, it should be easy for you to override/replace emscripten's builtin X11 support using a third-party library.  If that doesn't work well today its something we should certain fix. 

Is your project purely as JS library or does it have some native code?

Perhaps it would make sense to manage it as an external port like we for `tools/ports/emdawnwebgpu.py` and `tools/ports/contrib/glfw3.py`?   Would you like send a PR to add `tools/ports/contrib/EmX11.py` perhaps?

**Comment by DevScholar** [comment]
I agree with the Emscripten project's philosophy of maintaining its code quality. Therefore, perhaps EmX11 will maintain a long-term independent project status and pre release status until the code quality meets standards, or it should become a Ports project, just like SDL. Perhaps I will use AI to scan Emscripten to confirm its code quality constraints and API style constraints, and apply them to EmX11. EmX11 contains a large amount of C code. Perhaps PR is too early now.

**Comment by moticeanim** [comment]
> Thanks, I try to read through the emscripten toolchain and roughly get the idea. Then I actually put the X11 includes in the `emscripten include`, then manually link the X11 libs, I don't know why but the result works.

I'm trying to build a project, but I think I'm getting the same issue. I don't have access to any X11 .h or include files, and I think it's because I'm on Windows, but is there any way that I could still get X11 files to import to put somewhere?
