### ISSUE TITLE
accessing functions from javascript in Unity3d webgl 

### ISSUE THREAD

**Issue by whimsica** [kripken/emscripten#4201]
Unity3d uses emscripten to run unity in javascript for webgl.  I'm trying to access functions that I wrote in unity from javascript but I get errors that it cannot find the functions.

I'm using the documentation examples of communicating found here
https://kripken.github.io/emscripte...l#interacting-with-code-direct-function-calls

I've tried the example of putting int_sqrt  into the code and then using _ underscore for direct call to the function. I also tried the ccall and cwrap.  The functions are not found using either of these methods.

Assertion failed: Cannot call unknown function int_sqrt (perhaps LLVM optimizations or closure removed it?)

The function is there because I can call it using a unity specific SendMessage command that unity included.  Why can't I see it using the underscore or cwrap commands?

**Comment by kripken** [comment]
Is this the same as was just posted in the mailing list?

**Comment by whimsica** [comment]
Yes should I delete one of them?

**Comment by kripken** [comment]
Yes, let's close this (as I already wrote a comment in the other). Otherwise the discussion is fragmented, and later people searching for the same question might find only half the discussion, etc.

No preference between github and mailing list from me, either is fine, it's just parallel discussions seems less efficient, so best to pick one.
