### ISSUE TITLE
Minor optimizer simplification opportunity

### ISSUE THREAD

**Issue by aidanhs** [kripken/emscripten#4367]
https://github.com/kripken/cashew/commit/f729e3894f0e7fcd8a8935fcb62c6e07c4828b7d#diff-3

The 'true' appears to be inherited from the uglifyjs 1 parser where it could be replaced by one of `['+', '-', '/', '*', ...]` to represent the corresponding assignment operators. I don't see any of these complex operators in the asm.js spec - http://asmjs.org/spec/latest/

Two questions:
1. Am I correct in saying that those assignment operators aren't used in asm.js?
2. Is it desirable to remain compatible with the uglifyjs parser? (fair enough if so)

**Comment by kripken** [comment]
Yes, the `true` is for that. And yes, asm.js doesn't have those assign+operation things, and asm.js is almost certainly not going to be updated. So in theory we could optimize this away.

However, there is still some chance we'll want that functionality, and it's probably not a big difference in overhead, so I think it's not worth doing.

If you are looking for optimizer optimization opportunities, I suggest focusing on the [binaryen](https://github.com/WebAssembly/binaryen) optimizer. It should be much faster than the asm.js optimizer since it has a much nicer IR to operate on - in particular, it doesn't have any quirks like this uglify issue here. If we can get it fast enough, and we can write an efficient wasm2asm pass, then we could deprecate the asm.js optimizer, in fact - although both of those ifs are still open questions.

Right now I am still adding optimizations to it, but there is already a lot of data-structure type optimization that could be done (`set` vs `unordered_set` vs `vector`, etc.) on what already exists.

**Comment by aidanhs** [comment]
Cool, thanks for the confirmation.

I stumbled across it mainly because I'm reimplementing the emscripten optimizer in rust. Parsing code porting is complete and the in-memory representation seems to be 1/3 of the size.

After that's done, I'll probably also implement the binaryen optimizer in rust and keep track pace with the changes you make.

**Comment by kripken** [comment]
Oh, very interesting about the rust reimplementations! Is there a repo I can follow?

**Comment by aidanhs** [comment]
https://github.com/aidanhs/ayzim - the general code organisation should be pretty familiar ;)

You won't be able to build it without https://github.com/servo/string-cache/pull/136 and it only parses JS/JSON+emits JSON so far, but in terms of LOC % it's probably about halfway there.

**Comment by kripken** [comment]
Cool, thanks.
