### ISSUE TITLE
Unusual big speedup using -s SIMD=1

### ISSUE THREAD

**Issue by flash1293** [kripken/emscripten#4568]
I tried to speed up a simple, straight-forward matrix multiplication using SSE intrinsics.

This is the scalar version:
```
float* mul(float *a, float *b, int size) {
	float *c = (float *) malloc(size * size * sizeof(float));
	for(int x = 0; x < size; x++) {
		for(int y = 0; y < size; y++) {
			float tmp = 0;
			for(int i = 0; i < size; i++) {
				tmp += a[y * size + i] * b[x * size + i];
			}
			c[y * size + x] = tmp;
		}
	}
	return c;
}
```

This is the SIMD version:
```
float* mul(float *a, float *b, int size) {
	float *c = (float *) malloc(size * size * sizeof(float));
	float *tmpArray = (float *) malloc(4 * sizeof(float));
	for(int x = 0; x < size; x++) {
		for(int y = 0; y < size; y++) {
			float tmp = 0;
			__m128 tmpVec = _mm_setzero_ps();
			for(int i = 0; i < size; i+=4) {
				__m128 aVec = _mm_load_ps(a + (y * size + i));
				__m128 bVec = _mm_load_ps(b + (x * size + i));
				__m128 cVec = _mm_mul_ps(aVec, bVec);
				tmpVec = _mm_add_ps(tmpVec, cVec);
			}
			_mm_store_ps(tmpArray, tmpVec);
			for(int i = 0; i < 4; i++) {
				tmp += tmpArray[i];
			}
			c[y * size + x] = tmp;
		}
	}
	return c;
}
```

It is compiled using `emcc matrix.simd.c -msse -s SIMD=1 ... -O3 -o matrix.simd.asm.js`. For a matrix-multiplication of 2 128x128 matrices (average of 500 runs), this results in a speedup of 4.98.

What could be the reason for this? At least for me there is no obvious optimization possibility in the SIMD-code which is not present in the scalar-code.

**Comment by juj** [comment]
Speedup of 4.98x sounds great. Why should that not have occurred?

SIMD is not about strict 4.0x speedup, it is possible to get 10x or 20x speedups or otherwise on some algorithms, because there are many factors in play to consider, one being that SIMD code can fit 4x data in registers, and scalar version might have to spill, which is not a "linear" slowdown. Also, instruction clock cycles are complicated with separate latency and throughput measures, and there's no rule that would say that the SIMD version would have to have exactly 1/4th of the throughput cycles per data element compared to scalar. (SIMD also has some instructions that scalar doesn't (rcp, rsqrt) that can give greatly disproportionate speedups, although those aren't used here)

Also note that the second loop is 4x unrolled, but the first one is not, so this benchmark is not apples to apples.

**Comment by flash1293** [comment]
The reasons you listed sound very plausible. Thanks for the insight. My naive chain of thought was: "The hottest part of the code is executed in 4 parallel lanes (speedup = 4), but there is still scalar code, so the overall speedup will be a bit lower (3 +- 0.5)", but you are right, there are a lot more things to consider.
