### ISSUE TITLE
Determine GL mode at runtime

### ISSUE THREAD

**Issue by kripken** [kripken/emscripten#462]
We should consider forcing people to call something like `emscripten_set_gl_mode`, to decide between fast (webgl subset) or emulated (gles or even desktop). Currently we autodetect, and this can be confusing.

**Comment by juj** [comment]
Closing this as resolved, we now seem to have a pretty good set of WebGL modes, including WebGL2. Recapping:

- building without any flags gives ability to target WebGL 1.0 support via GLES2 headers. No emulation. This is practically core GLES2.
- building with `-s LEGACY_GL_EMULATION=1` gives (a very limited set of) desktop GL emulation
- building with `-s FULL_ES2=1` gives WebGL 1 via core GLES2 headers + emulation to get some missing GLES 2 features, most notably client side rendering support. The flags `-s LEGACY_GL_EMULATION=1` and `-s FULL_ES2=1` are mutually orthogonal since it's not sensible to target both desktop GL and GLES at the same time.
 - building with `-s USE_WEBGL2=1` enables targeting core WebGL 2.0 via GLES 3 headers. No emulation of GLES3 features that don't map directly. Having this flag does not yet mean that one will initialize a WebGL 2 context, or that WebGL 2 context will be required by the browser to run the generated build, but the application is capable of then initializing either aWebGL1 or WebGL 2 (GLES2 or GLES3) context. Once browsers ship stable versions of WebGL2, we'll likely make this flag default to 1 instead of current 0.
  - building with `-s USE_WEBGL2=1 -s FULL_ES3=1` enables creating WebGL 2 contexts, and also adds emulation for some GLES3 features that we can emulate (mainly buffer mapping).

Closing this issue as resolved.
