### ISSUE TITLE
SIMD errors on latest spidermonkey

### ISSUE THREAD

**Issue by kripken** [kripken/emscripten#4645]
`asm2.test_simd_float32x4` and `asm2.test_simd_int32x4` both fail on latest spidermonkey, with

```
asm.js type error: asm.js does not support 3-element SIMD loads or stores
```

Perhaps something changed in the spec? cc @juj @sunfishcode

**Comment by sunfishcode** [comment]
Yes; the load3/store3 functions were removed from asm.js.

**Comment by juj** [comment]
Why were they removed? Those functions are still part of the SIMD spec? [load3](http://tc39.github.io/ecmascript_simd/#simd-load3), [store3](http://tc39.github.io/ecmascript_simd/#simd-store3)

**Comment by sunfishcode** [comment]
load3/store3 were removed from asm.js due to pushback from implementors because they are inconvenient to implement (they are a special case for some bounds-checking strategies because they aren't power-of-2 sized), they don't correspond directly to a single instruction on any hardware, and they can always be reintroduced in the future if there's sufficient demand.

**Comment by juj** [comment]
Is there a conversation trail or a spec document regarding this to reference to? Please include a heads-up when these kinds of changes occur, so that Emscripten will know to adapt. Is the intent to drop `load3` and `store3` from SIMD.js altogether?

**Comment by juj** [comment]
Authored PR #4673 to remove these.

However I feel uneasy authoring the PR, because I'm writing this based on what latest nightly SpiderMonkey validation is spitting out, I don't have any reference or changelog to read about this, or any conversation history.  Are there some other SIMD.js features that have been removed? Is there a bugzilla number for these removals that I could follow?

I think it would be good to have this documentation online with the SIMD.js spec. Posted https://github.com/tc39/ecmascript_simd/issues/349 about that.

**Comment by juj** [comment]
For reference, the conversation about removing them occurred in https://bugzilla.mozilla.org/show_bug.cgi?id=1298202.

**Comment by juj** [comment]
The PR that removed load3 and store3 were merged, so closing this as resolved.
