### ISSUE TITLE
Building on Windows

### ISSUE THREAD

**Issue by MikeGameDev** [kripken/emscripten#4657]
I'm on Windows using VS2015 and I'm trying to figure out what kind of options I have for building. The project is pretty large (100+ source files) and it's windows only, so we don't have any Make or Cmake files, we just use visual studio.

So far the options I have come across are:
- Manually writing a Makefile (or CMake) and passing that into emmake
- Passing a list of source files into emcc

The second option is the one I'm interested in since it seems like it would be the easiest to do, after all the Visual Studio IDE must have some way to pass the list of source files into it's compiler, right? If I could figure out how to get the list of source files, I can write a custom build event in VS to invoke emcc. Is this a viable approach, or am I just way to naive? 

Anyways I was just hoping to get some insight as to how others go about building a VS only project.

Any help would be appreciated, thanks.

**Comment by juj** [comment]
Definitely recommend using CMake and using MinGW make to drive the build for Emscripten. Emscripten has strong support for driving builds via CMake, and CMake can generate Visual Studio solutions for native Windows builds, so you'll get one build system when targeting both types of builds.

There was an experimental "vs-tool" project to integrate driving Emscripten compiler builds from Visual Studio, but that was dropped because it did not save much work, since it didn't help much converting large Windows projects in the end, because one needs to refit the VS solution/projects to build with Emscripten build flags and remove any Windows'isms.

**Comment by MikeGameDev** [comment]
I was able to create a CMakeLists.txt file for my project, I'm able to run cmake with it to generate a Visual Studio solution to build my project. Yay!

Now if I understand correctly, I need to use CMake to generate a MinGW Makefile and then pass that makefile into emmake. I installed MinGW using the following commands:
`emsdk install mingw-4.6.2-32bit`
`emsdk activate mingw-4.6.2-32bit`

When I try to use cmake to generate the make file, it gives the following error:

> Check for working C compiler: C:/Program Files/Emscripten/mingw/4.6.2_32bit/gcc.exe -- broken
CMake Error at C:/Program Files/CMake/share/cmake-3.6/Modules/CMakeTestCCompiler.cmake:61 (message):
  The C compiler "C:/Program Files/Emscripten/mingw/4.6.2_32bit/gcc.exe" is
  not able to compile a simple test program.

So when I try using gcc directly from the command line with the argument:
`gcc hello_world.c -v`

It fails saying:

> Using built-in specs.
COLLECT_GCC=gcc
Target: mingw32
Configured with: ../gcc-4.6.2/configure --enable-languages=c,c++,ada,fortran,objc,obj-c++ --disable-sjlj-exceptions --with-dwarf2 --enable-shared --enable-libgomp --disable-win32-registry --enable-libstdcxx-debug --enable-version-specific-runtime-libs --build=mingw32 --prefix=/mingw
Thread model: win32
gcc version 4.6.2 (GCC)
COLLECT_GCC_OPTIONS='-v' '-mtune=i386' '-march=i386'
 cc1 -quiet -v -iprefix c:\program files\emscripten\mingw\4.6.2_32bit\../lib/gcc/mingw32/4.6.2/ hello_world.c -quiet -dumpbase hello_world.c -mtune=i386 -march=i386 -auxbase hello_world -version -o C:\Users\Michael\AppData\Local\Temp\ccYg6s6q.s
gcc: error: CreateProcess: No such file or directory

I suspect the problem is due to this bit:

> c:\program files\emscripten\mingw\4.6.2_32bit../lib/gcc/mingw32/4.6.2/ 

Since the lib directory does not exist. So now I'm wondering if I did something incorrect when I installed MinGW through emsdk or if I missed something else.

**Comment by juj** [comment]
Great to hear!

Regarding MinGW, I've heard someone say that it wouldn't work if the computer did not have an `E:\` drive available (weird, I know), exactly giving that `CreateProcess` error. Perhaps a newer version fixed that. I suppose we should look at updating the MinGW that emsdk can provide to a more newer one.

to build HTML files, you can set the `CMAKE_EXECUTABLE_SUFFIX` property to specify HTML instead of JS. That'll get stuff running on the browser. I'll close this one as resolved!
