### ISSUE TITLE
unresolved symbol at link time from library code

### ISSUE THREAD

**Issue by ahixon** [kripken/emscripten#4761]
Compiling the following with master `emcc`:
```c
#include <netdb.h>

int main () {
    void* thing = gethostbyname("google.com");
    return 0;
}
```
gives no compiler errors, but at link time fails with:

    warning: unresolved symbol: htons

From what I can see from the muslc library code, the callpath looks like: `gethostbyname` -> `gethostbyname2` -> `gethostbyname2_r` -> `getaddrinfo` -> our friend `htons`

A workaround is simply to force `htons` to be included at link time by referencing it pointlessly. Example program:

```c
#include <stdlib.h>
#include <netdb.h>

int main () {
    void* thing = gethostbyname("google.com");
    void* other = htons;
    return 0;
}
```

**Comment by ahixon** [comment]
Probably the same problem, but if not I'll open another issue:

Weirdly, if you replace the call of `gethostbyname` to `gethostbyname2` in the above code, you get:

    warning: unresolved symbol: gethostbyname2

even though `gethostbyname` would normally call it anyway, so you'd expect to get the same unresolve symbol error rather than a different one? Also, with that example, there's *no work around*.

**Comment by kripken** [comment]
Thanks for filing. Ok, first issue is fixed on incoming. The problem is that much of our sockets code is in JS, so it can easily connect to the browser's networking APIs - so the relevant code is mostly in `library.js` instead of musl. So we need to map out the dependencies between libc and JS both ways, and the libc->JS way is not automatic, and we were missing an entry.

Second issue is that we don't have support for gethostbyname2. Looks like it's a gnu extension from the manpage? It would be nice to support it, I'm not sure offhand how easy that would be.

**Comment by ahixon** [comment]
Awesome, thanks for the fix! Works for me too on incoming now.

Also thanks for the toolchain info! Yeah, I had a quick look at the docs but couldn't spot any info on that (though tbh I didn't look super hard, heh)

No worries about gethostbyname2. My usecase was trying to build curl from master, which only needs gethostbyname. The only reason I brought it up was because of my (incorrect) assumption it was using the muslc code rather than `library.js`!
