### ISSUE TITLE
emscripten_run_script_string might not be allocating a large enough buffer

### ISSUE THREAD

**Issue by rajsite** [kripken/emscripten#4766]
As part of setting NO_DYNAMIC_EXECUTION=1 for CSP support I had to go through and replace a few instances of emscripten_run_script_string.

I started creating creating library functions to replace emscripten_run_script_string and noticed that the implementation takes a JS string and allocated a buffer of [size length+1](https://github.com/kripken/emscripten/blob/07b87426f898d6e9c677db291d9088c839197291/src/library.js#L3674) on the heap.

[emscripten_run_script_string](https://github.com/kripken/emscripten/blob/07b87426f898d6e9c677db291d9088c839197291/src/library.js#L3669) then calls [writeStingToMemory](https://github.com/kripken/emscripten/blob/07b87426f898d6e9c677db291d9088c839197291/src/preamble.js#L1540) which calls [intArrayFromString](https://github.com/kripken/emscripten/blob/07b87426f898d6e9c677db291d9088c839197291/src/preamble.js#L1515) which calls [lengthBytesUTF8](https://github.com/kripken/emscripten/blob/07b87426f898d6e9c677db291d9088c839197291/src/preamble.js#L644)

Observation makes me think that the allocated heap buffer is actually not large enough to hold JS strings that have codepoints outside of Unicode BMP as they are converted to UTF8.

I have not run into any issues specifically yet but it seems like either the buffer should be changed to [size length*4+1](https://github.com/kripken/emscripten/blob/07b87426f898d6e9c677db291d9088c839197291/src/preamble.js#L630) or maybe there should be a note saying only ASCII characters are supported for emscripten_run_script_string since the function signature is char*.

**Comment by juj** [comment]
Good catch. The buffer overrun loophole was closed earlier in PR #4497, where `writeStringToMemory()` was deprecated. After PR #4497, the behavior that will be seen is that the string write will get truncated instead of overrunning.

However reading the function now I notice that I have mistakenly glanced through that the string there would be strictly 7-bit ASCII, but of course users can return any custom characters, so the length needs to be counted properly. Posting a PR shortly.

**Comment by juj** [comment]
Fixed in above commit.
