### ISSUE TITLE
Static type cast of array

### ISSUE THREAD

**Issue by pjb7687** [kripken/emscripten#4774]
Hi, thank you for your great work! I would like to report a weird behavior regarding type casting of arrays in different types at an arbitrary address of original array. I hope that it would not be a duplicate to another issue.. For example:

```
#include <stdio.h>
#include <stdlib.h>

int main() {
    unsigned char *a = (unsigned char *)malloc(5);

    a[0] = 1;
    a[1] = 245;
    a[2] = 4;
    a[3] = 0;
    a[4] = 0;

    unsigned int *b = (unsigned int *)(a+1);
    unsigned int *c = reinterpret_cast<unsigned int *>(a+1);

    printf("C cast: %d\n", b[0]);
    printf("reinterpret cast: %d\n", c[0]);

    free((void *)a);
    return 0;
}
```

Native gcc returns:

C cast: 1269
reinterpret cast: 1269

Emscripten-compiled JavaScript returns:

C cast: 324865
reinterpret cast: 324865

I looked into the assembly code generated by Emscripten, it looks like the code tries to read values from HEAP32 after copying wrong values from HEAP8. So I also tried to do 'malloc' to allocate memory on HEAP32 and copy the content like below:

```
uint32_t *array_tmp = (uint32_t *)malloc(sizeof(uint32_t));
memcpy(array_tmp, array_test, sizeof(uint32_t));
printf("test: %d\n", array_tmp[0]);
free((void *)array_tmp);
```

Then it worked on both platforms.

**Comment by pjb7687** [comment]
Probably this could be also very similar to this issue:
https://kripken.github.io/emscripten-site/docs/porting/guidelines/function_pointer_issues.html

But in this case the problem is caused due to the different memory models, not the function tables.
It would be nice if there is a way to emulate this behavior with a compilation flag (even though it would be slow).

**Comment by pjb7687** [comment]
Sorry to make confision, this only happens when I read values from at an arbitrary address from the original array. That means, below works well on both platform:

int main() {
    unsigned char *a = (unsigned char *)malloc(5);

    a[0] = 245;
    a[1] = 4;
    a[2] = 0;
    a[3] = 0;

    unsigned int *b = (unsigned int *)(a);
    unsigned int *c = reinterpret_cast<unsigned int *>(a);

    printf("C cast: %d\n", b[0]);
    printf("reinterpret cast: %d\n", c[0]);

    free((void *)a);
    return 0;
}

I modified my original post after I found this. I tried C style type cast and also reinterpret_cast but both failed. Probably a bug in emscripten.

**Comment by juj** [comment]
The code is breaking C alignment rules, which is why it does not work. See the [Portability Guidelines](http://kripken.github.io/emscripten-site/docs/porting/guidelines/portability_guidelines.html) in the documentation, under third bullet point about x86 alignment behavior.

If code does insist on doing unaligned memory loads or stores, it must tell the compiler that it's about to do so. Clang has a compiler specific attribute flag for that. The `emscripten_align1_int*` pointer type are available as a convenience to do this. Try replacing

    unsigned int *c = reinterpret_cast<unsigned int *>(a);

with

    emscripten_align1_int *c = reinterpret_cast<emscripten_align1_int *>(a);

and add `#include <emscripten/emscripten.h>`. That tells the compiler that the integer is being loaded from unaligned memory.

In upcoming WebAssembly, this is not strictly needed, but there can be a very large performance penalty when doing unaligned memory operations that the compiler didn't know about, which is why writing proper alignment aware C code is critical even in WebAssembly.
