### ISSUE TITLE
1.37.0 merge to master

### ISSUE THREAD

**Issue by kripken** [kripken/emscripten#4803]
We should really merge to master. How about if we institute a freeze on merges to incoming until then? @juj, is now a good time to do this, or should we delay?

**Comment by kripken** [comment]
On 9a648a8ea2541ea50f40b9d54e638299f4beeb2d / f3dfdd1fbcc84a70d89ad58b7cfdf0efb2e63fb2 (fastcomp) / e44343a76d96a836e7f0abc0779d774e90621674 (binaryen), I see no errors on

 * main part of test suite
 * other
 * sockets
 * sanity

On the browser tests I do see two errors I'm not sure what to do with,

 * `test_float_tex` fails on `Shader info: 0:2(12): warning: extension `GL_ARB_gpu_shader5' unsupported in vertex shader`
 * `test_webgl_context_params` fails on `uncaught exception: Assertion failed: glGetError() == 0 && "glReadPixels of FBO 0 in implementation defined format failed"`

And on the interactive tests I see a failure on 1 test:

 * `test_html5_pointerlockerror`. This is a new test I'm not familiar with, not sure what's going on there.

Do those tests pass for other people?

Aside from those 3 failures, and if there are any problems on @juj's bots, we are ok to merge I think.

**Comment by juj** [comment]
The error you are seeing on `test_float_tex` is definitely a Linux Firefox WebGL backend bug. I think I've seen that message on one of my linux boxes at some point, but haven't quite had time to triage it down. We can ignore that on our side.

The error `test_webgl_context_params` is likewise a Firefox WebGL backend bug, which has been reported here: https://bugzilla.mozilla.org/show_bug.cgi?id=1310005 . See also this line: https://github.com/kripken/emscripten/blob/incoming/tests/test_browser.py#L2170 . I had gated that skip to Windows only because I only get it happening on the Windows bot.

The `test_html5_pointerlockerror` failure is a new one. This is due to a behavioral change in Firefox it seems. The old behavior was that when one locks the pointer, a question dialog was presented whether to allow the lock or not. The new behavior seems to be that pointer lock is always done, but one can opt out by pressing esc. I'm not sure actually how the error event factors into this then, but certainly the failure is not critical from Emscripten side.

**Comment by juj** [comment]
I'd really like to get https://github.com/kripken/emscripten/pull/4665 in for 1.37.0.

**Comment by juj** [comment]
Windows and Linux bots are green: http://clb.demon.fi:8112/#/

OS X bot is otherwise green but occassionally fails on `browser.test_glgears_deriv` and `browser.test_subdata`. I don't know why that is, when I run those tests locally on the OS X box, they succeed. My current guess is that since those tests use `requestAnimationFrame` that they somehow behave differently when I have a physical monitor attached. These two failures can be ignored for a merge to master.

**Comment by dschuff** [comment]
+1 for a merge and a freeze for commits to incoming. It doesn't have to be strictly a freeze, we can have high whitelist/high priority  commits, or just a higher bar or whatever. I do in particular really like #4665

**Comment by kripken** [comment]
Ok, with #4665 we can hopefully get this done this week? @juj please confirm that after that landed the bots still look good. I can do another full local test run later this week. If both of those are ok, we can do the merge.

Let's not merge anything to incoming meanwhile?

**Comment by juj** [comment]
I'm hopeful that the current set of runs on all bots should finish as green (ETA about 3 hours to finish from now), and we should be good to merge. No need to get anything else in anymore I think.

**Comment by juj** [comment]
Alright, all bots are green now: http://clb.demon.fi:8112/#/

**Comment by kripken** [comment]
Great, I'll do a full local run on thursday or friday, and merge to master then if there are no issues as expected. Let's not merge anything to incoming til then.

**Comment by kripken** [comment]
I'll try to merge later today.

Here is a list of PRs that can probably land on incoming after we merge to master, leaving here as a reminder to me to look at them after the merge (I might not get to them all today though):

 * https://github.com/kripken/emscripten/pull/4737
 * https://github.com/kripken/emscripten/pull/4797
 * https://github.com/kripken/emscripten/pull/4815
 * https://github.com/kripken/emscripten/pull/4802

**Comment by kripken** [comment]
Merge has been completed! :)

Leaving open for those PRs to get to later.

**Comment by kripken** [comment]
I managed to get to them now. Merged 3 of those, last is waiting on a tiny fix. Closing this issue.

**Comment by kripken** [comment]
@juj, something seems wrong on the os x master bot, http://clb.demon.fi:8112/#/builders/3/builds/1/steps/5/logs/stdio - it's using the emsdk but somehow didn't update the emscripten repo which is 3 versions behind?

**Comment by juj** [comment]
Great work on this!

The OS X master bot failure was a typo in directory names when running tests on the master branch, should be fixed now in all three bots.

**Comment by my2iu** [comment]
Hi, I'm a little unclear about how Emscripten releases work. Is 1.37 just an internal release? Is 1.35.0 still the latest stable version? 

The website still lists 1.35 as the latest release and when I use the Windows portable installer, that's what gets installed.

**Comment by kripken** [comment]
There are 3 things: incoming, where we develop, master, where we consider code to be stable, and the SDK release. Currently 1.37 is stable, but I think we don't have an SDK release for that yet - is that right, @juj?
