### ISSUE TITLE
Language support

### ISSUE THREAD

**Issue by DeepakRajendrakumaran** [kripken/emscripten#4883]
As someone who is new to webassembly and the compilation toolchain for it using emscripten, I am having an issue determining the existing support. Is there any documentation showing the 'c language support' provided by the toolchain to compile to wasm? I see an API limitation page but that seem to point out browser limitation as opposed to compiler tool-chain limitation. and I am more interested in the current emscripten capability as I am interested in non-browser applications.

p.s. I am not sure if the 'issues' page is only for current contributers. If it is, my apologies

**Comment by kripken** [comment]
Any API limitations would be the same on the web and elsewhere. Perhaps the only possible difference is in filesystem access, where node.js provides synchronous read/write but the web does not. Otherwise, it's exactly the same - JS/asm.js/wasm executing either on the client or server. Practically all portable C/C++ code should work fine.

**Comment by DeepakRajendrakumaran** [comment]
Thank you. That helps
