### ISSUE TITLE
embind'ing function pointer values

### ISSUE THREAD

**Issue by vadimkantorov** [kripken/emscripten#4927]
I am trying to embind libgit2's internal structures and they happen to use a lot function pointer values. Embinding the code below generates this error:
```
In file included from ../../emscripten/libgit2bind.cpp:1:
.../emscripten/system/include/emscripten/bind.h:844:23: error: implicit
      instantiation of undefined template 'emscripten::internal::GetterPolicy<void (*git_transport::*)(git_transport *)>'
            auto g = &GP::template get<ClassType>;
                      ^
../../emscripten/libgit2bind.cpp:14:4: note: in instantiation of function template specialization
      'emscripten::value_object<git_transport>::field<void (*git_transport::*)(git_transport *), emscripten::allow_raw_pointers>'
      requested here
                .field("free", &git_transport::free, allow_raw_pointers())
                 ^
.../emscripten/system/include/emscripten/bind.h:561:16: note: template is
      declared here
        struct GetterPolicy;
               ^
.../emscripten/system/include/emscripten/bind.h:845:23: error: implicit
      instantiation of undefined template 'emscripten::internal::SetterPolicy<emscripten::allow_raw_pointers>'
            auto s = &SP::template set<ClassType>;
                      ^
.../emscripten/system/include/emscripten/bind.h:600:16: note: template is
      declared here
        struct SetterPolicy;
               ^
.../emscripten/system/include/emscripten/bind.h:850:33: error: implicit
      instantiation of undefined template 'emscripten::internal::GetterPolicy<void (*git_transport::*)(git_transport *)>'
                TypeID<typename GP::ReturnType>::get(),
                                ^
.../emscripten/system/include/emscripten/bind.h:561:16: note: template is
      declared here
        struct GetterPolicy;
               ^
3 errors generated.
```

Code:
```cpp
#include <emscripten/bind.h>
using namespace emscripten;

struct git_transport
{
    int version;
    void (*free)(git_transport* instance);
};

EMSCRIPTEN_BINDINGS(mytest)
{
    value_object<git_transport>("git_transport")
        .field("version", &git_transport::version)
        .field("free", &git_transport::free, allow_raw_pointers())
    ;
}
```

Is there a way to bind struct's function pointer fields?

At the end of the day I'd like to implement `free` (and other similar function pointers in the real [`git_transport`](https://github.com/libgit2/libgit2/blob/master/include/git2/sys/transport.h#L35)) in JavaScript (using `Runtime.addFunction` presumably?).
Thanks!

**Comment by AlexPerrot** [comment]
Hi,

I am not about how binding function pointers is currently supported in embind (if it is supported at all).
C++11 introduces `std::function` that can be used to represent a function pointer. That might be a way to bind such a use case.

Is there any particular reason to use a function pointer instead of a method ?
Binding a method (eventually just calling the function pointer) should solve the issue.

**Comment by vadimkantorov** [comment]
The only reason is I tried to have a minimal wrapper around a pure C libgit2's codebase.

For now I gave up embind and working around with `Module.cwrap`.

**Comment by AlexPerrot** [comment]
Ok, I was able to bind a function pointer as a property with embind.
My two requirements were:

- Being able to set the function pointer from a js function like this `foo.bar = myFunction`
- Being able to call the function property from js with simply `foo.bar()`

Achieving all this required a bit of glue code.

## The class

First the definition of the class we want to bind :

``` c++
#include <emscripten/bind.h>
#include <emscripten/val.h>
#include <iostream>

using namespace emscripten;

void sayHi() {
    std::cout << "hi" << std::endl;
}

struct Foo {
    Foo() {this->bar = sayHi;}
    void (*bar)(void); //function pointer we want to bind
};
```
## The bindings

Then, the bindings is like this :

``` c++
EMSCRIPTEN_BINDINGS(fpointer) {
    class_<Foo>("Foo")
    .constructor()
    .property("bar", &getter, &setter)
;
```

### Setter

I'll begin with the `setter` function, as it is the simplest.
Its role is to create a function pointer from a js function.

``` c++
void setter(Foo& self, val jsfunc) {
    // we call Runtime.addFunction from c++
    int f_ptr = val::module_property("Runtime").call<int>("addFunction",jsfunc);
    // it returns an int that we can reinterpret as a function pointer
    void (*f)(void) = reinterpret_cast<void (*)(void)>(f_ptr);
    // and set the property
    self.bar = f;
    // maybe we should also unregister the previous function if possible
}
```

### Getter
Now, `getter` will require a little bit of js glue code also, because we want it to return a js function that can call into your function pointer.

For that, we will use a `post-js` addition to create a function calling the provided pointer :
``` c++
function generateCaller(ptr) {
    return function() {
        Module.Runtime.dynCall("v", ptr, []);
    }
}
Module['generateCaller'] = generateCaller
```

Now, we can define `getter` as : 

``` c++
val getter(const Foo& self) {
    return val::module_property("generateCaller")(reinterpret_cast<int>(self.bar));
}
```

One problem here is that it generates one caller each time you change the function pointer. Also, you need to reserve enough pointers using `-s RESERVED_FUNCTION_POINTERS=n` when compiling.
