### ISSUE TITLE
error in 1.37.2: unresolved symbol: $emscriptenWebGLGetHeapForType

### ISSUE THREAD

**Issue by evanw** [kripken/emscripten#4934]
I just tried upgrading our app to 1.37.2 but hit a build error:

```
error: unresolved symbol: $emscriptenWebGLGetHeapForType
error: unresolved symbol: $emscriptenWebGLGetShiftForType
Aborting compilation due to previous errors | undefined
```

It looks like `$emscriptenWebGLGetHeapForType` is defined in [library_gl.js](https://github.com/kripken/emscripten/blob/1.37.2/src/library_gl.js#L1236) but is guarded by `#if USE_WEBGL2`:

```js
#if USE_WEBGL2
  $emscriptenWebGLGetHeapForType: function(type) {
    ...
  },
#endif
```

It's then later used as a dependency by functions that aren't under the same guard:

```js
  glTexImage2D__sig: 'viiiiiiiii',
  glTexImage2D__deps: ['$emscriptenWebGLGetTexPixelData', '$emscriptenWebGLGetHeapForType', '$emscriptenWebGLGetShiftForType'],
  glTexImage2D: function(target, level, internalFormat, width, height, border, format, type, pixels) {
#if USE_WEBGL2
    ...
#endif

    ...
  },
```

That's my best guess as to why our builds are failing. Is this a bug? Is there a recommended workaround?

**Comment by kripken** [comment]
I think that's a known issue that @juj fixed on incoming yesterday. There isn't a new tagged version yet, but incoming should be ok. Otherwise, if you prefer tagged versions then until there's a 1.37.3, might be best to stay on 1.37.1. We can add 1.37.3 soon though.

**Comment by juj** [comment]
Very sorry about that @evanw! When authoring the patch, I did confirm that the functions are actually used only when WebGL2 is defined, but still did a silly mistake and forgot to remove them from the `__deps` directive. The fix is in this commit: https://github.com/kripken/emscripten/commit/abda378333b4b8aae8e89357e7de25bbd3297a9f

As a workaround, also building with `-s ERROR_ON_UNDEFINED_SYMBOLS=0` is safe here, because those symbols are not actually used in WebGL 1 builds, but just mistakenly present in the deps list. Again, apologies for such a silly mistake!

**Comment by evanw** [comment]
We don't want to disable `-s ERROR_ON_UNDEFINED_SYMBOLS=0` because that lets us catch errors in our code. Using 1.37.1 for now works fine. I'm upgrading because I wanted to try out WebAssembly and it looks like I can try that out using 1.37.1 too. I'm sure I'll have to update again once WebAssembly is released for real.
