### ISSUE TITLE
"IMG_Load: unknown SDL-emscripten error" in result index.html

### ISSUE THREAD

**Issue by demensdeum** [kripken/emscripten#4938]
Hi, I build hello_image_sdl.c from tests directory, and get "IMG_Load: unknown SDL-emscripten error" in result index.html

**Environment screenshot**
http://prnt.sc/e7nxl7

**Steps**
1.Put hello_image_sdl.c and screenshot.jpg into same directory
2.Build:
`emcc hello_image_sdl.c -o index.html --preload-file screenshot.jpg`
3.Run python http server in same directory:
`python -m SimpleHTTPServer`
4.Open localhost:8000

In result I got error "IMG_Load: unknown SDL-emscripten error" in console, and exception:

> uncaught exception: Assertion failed: result != 0, at: hello_image_sdl.c,33,main at jsStackTrace@http://localhost:8000/index.js:1277:13
> stackTrace@http://localhost:8000/index.js:1294:12
> ___assert_fail@http://localhost:8000/index.js:1807:210
> _main@http://localhost:8000/index.js:7883:3
> asm._main@http://localhost:8000/index.js:14762:8
> callMain@http://localhost:8000/index.js:14913:15
> doRun@http://localhost:8000/index.js:14973:42
> run/<@http://localhost:8000/index.js:14984:7

How to fix that?

**Comment by demensdeum** [comment]
Environment screenshot:
http://prnt.sc/e7nxl7

**Comment by demensdeum** [comment]
Ok I fixed it just added --use-preload-plugins
emcc hello_image_sdl.c -o index.html --use-preload-plugins --preload-file screenshot.jpg
But I don't like that whole file now inside js file, guess I need to use FS or something.

**Comment by badfd** [comment]
The `use-preload-plugins` suggestion works (I just tried it), but 3-years later, the tutorial at https://emscripten.org/docs/getting_started/Tutorial.html still neglects to mention it.

Also, maybe I'm missing something, but if my command line includes `--preload-file <filename>`, then should not the `--use-preload-plugins` flag be unnecessary? (Because clearly the need has been implied?)

**Comment by kripken** [comment]
@badfd Maybe it should be documented more, yeah. Not sure where though. In the tutorial we don't use a file type that requires a preload plugin.

> Also, maybe I'm missing something, but if my command line includes --preload-file <filename>, then should not the --use-preload-plugins flag be unnecessary? (Because clearly the need has been implied?)

The plugins are only needed if special works needs to be done. For example, an image plugin can decode an image that is preloaded. But if you just preload a text file for example, you don't need any plugins, so we don't enable them by default.

Also, preload plugins are usually not used with SDL2, which most people seem to use these days. In general it seems people prefer to ship codecs for their engines in compiled code, rather than rely on the plugins which use browser code. That's less good for code size, but is simpler...
