### ISSUE TITLE
WebGL2 entry points

### ISSUE THREAD

**Issue by marcounity** [kripken/emscripten#4968]
Is this going to work if another browser (e.g. Edge) enable support for WebGL2.0 but does not implement the new entry points:
https://github.com/kripken/emscripten/blob/incoming/src/library_gl.js#L557

Also, shouldn't
"GL.currentContext.supportsWebGL2EntryPoints >= 2"
be
"GL.currentContext.supportsWebGL2EntryPoints"

in
https://github.com/kripken/emscripten/blob/incoming/src/library_gl.js#L1329
https://github.com/kripken/emscripten/blob/incoming/src/library_gl.js#L1363
?

Thanks,
Marco

**Comment by juj** [comment]
Oh dear, great catch with the typo, fixed in https://github.com/kripken/emscripten/commit/288f8d1a8704ecc62716a8e2b47d133a2094b2c0

Indeed the code will not work if another browser supports WebGL 2 but not the new entry points. The new entry points are not optional but part of core WebGL 2, so supporting WebGL 2 requires also supporting the new entry points. The Chrome specific hack was added because Chrome missed this and shipped their WebGL 2 implementation without the required entry points, and they specifically asked us to assist here for them until they fix their implementation, which they said will ship in Chrome 58. We hope that other browsers won't screw this up, but ship a conformant WebGL 2 implementation on the first go.
