### ISSUE TITLE
In Node, onRuntimeInitialized is not called when emcc args are used together: -O2 --closure 1

### ISSUE THREAD

**Issue by jcalfee** [kripken/emscripten#5148]
### Setup
```bash
echo 'int main() {}' > test.c

echo "
console.log('Load');
var Module = {}
Module.onRuntimeInitialized = function() {
    console.log('Initialize');
}
" > test-wrap.js

```

### Both Load and Initialize prints as expected
```bash
emcc test.c --pre-js test-wrap.js -o test.js && node test.js
```
>Load
>Initialize

### Only Load prints
```bash
emcc test.c --pre-js test-wrap.js -o test.js -O2 --closure 1 && node test.js
```
>Load
---
Why didn't initialize run?  More testing reveilles that initialized is skipped only when both O2 and closure are used.

**Comment by jcalfee** [comment]
1.37.0 ((unknown revision))

**Comment by kripken** [comment]
If you change it to `Module['onRuntimeInitialized']`, does it work?

If so, then it's closure advanced mode, it needs names to be quoted or else it minifies them. This happens here because your code in a pre-js is optimized with closure, together with the rest of the code. If you prepended the code manually, after compilation, then closure wouldn't affect it and it would work without quotes.
