### ISSUE TITLE
Does WebGL 2 mean we can write modern OpenGL?

### ISSUE THREAD

**Issue by computersarecool** [kripken/emscripten#5293]
Hi,
In reading the docs the recommendation seems to be to write OpenGL ES 2. However, now that there is WebGL 2 which is based on OpenGL ES 3 I am wondering if this information is out of date.  It is possible that we can write modern OpenGL and use with Emscripten - is their any guide for this?

**Comment by juj** [comment]
We have not updated the documentation to recommend to default to WebGL 2/OpenGL ES 3 because the adoption is not universal - IE11, Edge and Safari do not ship WebGL 2 yet.

However you are correct that you can now target OpenGL ES 3.0 with Emscripten, by using the linker flag `-s USE_WEBGL2=1`. That flag enables creation on WebGL 2 contexts, and defaults to creating WebGL 2 contexts if not specified otherwise. (but does not make a compile time choice that WebGL 2 support must be present)

I do see that we are missing relevant documentation on how to initialize this. Adding these in at https://github.com/kripken/emscripten/pull/5297

**Comment by juj** [comment]
The doc page additions were merged. Does this address your questions?

**Comment by computersarecool** [comment]
Indeed it does.
