### ISSUE TITLE
Errors related to async wasm instantiation should be more friendly

### ISSUE THREAD

**Issue by dschuff** [kripken/emscripten#5346]
If you try to call ccall/cwrap on a module before the wasm module is finished instantiating, you get an error that 'Runtime.stackSave' is not a function (cwrap itself of course can't work because the C function isn't there yet but stackSave is the first thing that will fail). I'd bet there's some module-level var that means "the wasm is instantiated or is still compiling" and we should query that it some of the obvious entry points like ccall to make that error friendlier, because this is likely to be a common issue.

**Comment by kripken** [comment]
When `ASSERTIONS` is on, we throw a message with
````
Assertion failed: you need to wait for the runtime to be ready (e.g. wait for main() to be called)
````
And we enable `ASSERTIONS` by default in unoptimized builds, so that hopefully helps most people. We could also add that check in builds without assertions, but it does add a little overhead and code size. If we think this is especially confusing though then perhaps we should do it.

**Comment by dschuff** [comment]
Ah I didn't realize that ASSERTIONS did that. That's probably sufficient.
