### ISSUE TITLE
Synchronous initialization for WASM?

### ISSUE THREAD

**Issue by cpitclaudel** [kripken/emscripten#5352]
Hi there,

Is there a WASM equivalent of `--memory-init-file 0`?  And is the wasm file reloaded every time the function called by `-s MODULARIZE` is instantiated?

Some more context, in case I'm misunderstanding something: I'm compiling two programs A and B to javascript, A using js_of_ocaml, and B using emscripten.  In native mode, A calls B by starting a process and sending it input on stdin.  In JS, I'm planning to have A call an external function with the input, and feed that input to B.  However, I need to start a fresh copy of B for each new input.  Since A is synchronous, I can't wait of `onRuntimeInitialized` to run.

Maybe a different question would be: is it guaranteed that initialization will be delayed / asychronous only on the very first instantiation of the emscripten-compiled program?  Or will it make an asynchronous call to fetch the WASM code every time?

Thanks!

**Comment by kripken** [comment]
In general emscripten tries to do startup asynchronously for wasm, because it's what browsers can best optimize, and worse, Chrome currently has a limitation on the size of synchronous compilations (hopefully will be fixed soon). But you can force sync compilation with `-s BINARYEN_ASYNC_COMPILATION=0`.

That still leaves fetching the wasm binary file. By default we fetch it asynchronously, but if you have a way to get it yourself before, you can set it on `Module['wasmBinary']` and we will just use that synchronously. Alternatively, #5296 will add an option to embed that file, making it available synchronously.

**Comment by cpitclaudel** [comment]
Thanks! I'm already using `BINARYEN_ASYNC_COMPILATION=0` (I was seeing crashes otherwise). #5296 looks great, thanks for the pointer (sorry for the noise; I should have searched more). 

Just as a quick confirmation: only the first run is asynchronous, right> If I instantiate a copy of my module (by calling the function) and wait for the onRuntimeInitialized event, then all subsequent initializations are safe for immediate use, correct?

In concrete term, this is safe; correct?

```
var a = Module({onRuntimeInitialized: function () {
  var b = Module();
  b.callMain(…); // No need to wait here, runtime was already initialized by a.
});
```

Thanks a lot.

**Comment by kripken** [comment]
That doesn't look safe. Each time you do `Module()` you get a completely new and independent module. Nothing is shared between them. So if one was initialized doesn't help in knowing if another was.

(Except maybe in theory the browser may have cached downloaded files or compilation operations, which would speed up creating modules after the first, but you can't depend on that.)

**Comment by cpitclaudel** [comment]
> That doesn't look safe. Each time you do Module() you get a completely new and independent module. Nothing is shared between them. So if one was initialized doesn't help in knowing if another was.

Oh, snap. OK.  So I should fetch the WASM binary myself, and populate the `Module['wasmBinary']` attribute before instantiating. Then the code will be safe to use synchronously, correct?

**Comment by kripken** [comment]
Yes, if async compilation is turned off.

**Comment by cpitclaudel** [comment]
Super, thanks a lot!

**Comment by kripken** [comment]
Btw, I updated the docs at https://github.com/kripken/emscripten/wiki/WebAssembly#wasm-files-and-compilation , let me know if you have ideas for improving that.

**Comment by kripken** [comment]
Yes, it should - when we can do sync downloads of the wasm file, we do (workers, node.js, etc.)

**Comment by ShayRubach** [comment]
Asking in 2022:
How can I build my WASM from Rust (currently using `wasm-pack`) with these configuration flags? it seems only related to `emscripten` builds. I read the linked articles.

I basically need to avoid async compilation of my wasm module because of my current app's architecture (limitation).
