### ISSUE TITLE
emscripten/vector.h works much slower than std::array

### ISSUE THREAD

**Issue by maksymmolchanovsc** [kripken/emscripten#5387]
I've wrote an example of vector sum calculation. Here is the code:
```
#include <cstdio>
#include <cstdint>
#include <random>
#include <array>
#include <chrono>
#include <emscripten/vector.h>

constexpr int IterationCount = 100000;
constexpr int VectorCount = 500;

#ifdef VECTORIZE

using VectorType = int16x8;

#else

using VectorType = std::array<int16_t, 8>;

VectorType& operator += (VectorType& lhs, const VectorType& rhs)
{
    for (int i = 0; i < 8; ++i)
        lhs[i] += rhs[i];
    return lhs;
}

#endif

VectorType vectors[VectorCount];

std::default_random_engine gen;

void init()
{
    std::uniform_int_distribution<int16_t> valueDistribution(-31, 31);
    for (int i = 0; i < VectorCount; ++i)
        for (int j = 0; j < 8; ++j)
            vectors[i][j] = valueDistribution(gen);
}

int test()
{
    std::uniform_int_distribution<int> indexDistribution(0, VectorCount - 1);
    int result = 0;
    for (int iteration = 0; iteration < IterationCount; ++iteration)
    {
        int l = indexDistribution(gen), r = indexDistribution(gen);
        if (l > r)
        {
            int tmp = l; l = r; r = tmp;  // don't want to use swap from algorithm
        }
        VectorType sum;
        for (int i = 0; i < 8; ++i)
            sum[i] = 0;
        for (int i = l; i <= r; ++i)
            sum += vectors[i];
        for (int i = 0; i < 8; ++i)
            result += sum[i];
    }
    return result;
}

int main()
{
    init();
    auto begin = std::chrono::system_clock::now();
    printf("%d\n", test());
    auto end = std::chrono::system_clock::now();
    printf("Elapsed time = %.3lfs\n", 1e-3 * std::chrono::duration_cast<std::chrono::milliseconds>(end-begin).count());
    return 0;
}
```

Then simply compiled it in html:
`em++ ./vect.cpp -std=c++14 -O3 -o vect.asm.js.html`
Elapsed time was 0.064s on Firefox.
`em++ ./vect.cpp -std=c++14 -O3 -DVECTORIZE -o vect.asm.js.html`
Elapsed time was 66.578s on Firefox.

**As you can see it's about 1000 times difference.**

With `-s WASM=1` flag elapsed time was the same and asm2wasm returned non-zero exit status -6 with `-DVECTORIZE` flag.

**Comment by juj** [comment]
The file `emscripten/vector.h` is the API to run SIMD.js in a browser. SIMD.js is a spec that is not currently shipping in any browser, but the effort is to reintroduce SIMD in WebAssembly.

SIMD.js is supported in Firefox Nightly channel. Running the `-DVECTORIZE` build on Firefox Nightly 56.0a1 (2017-07-10) (64-bit), the output is

```
Successfully compiled asm.js code (total compilation time 24ms; stored in cache)
82261816
Elapsed time = 0.024s
```

Running the same build in Firefox stable 54.0.1 (32-bit) prints

```
TypeError: asm.js link error: bad SIMD type
82261816
Elapsed time = 150.497s
```

which is as expected, since SIMD is not available. There is a JavaScript based emulation for SIMD instructions, but that is extremely slow, as can be seen.

Curiously, running the build without `-DVECTORIZE` in Firefox Nightly gives

```
Successfully compiled asm.js code (total compilation time 24ms; stored in cache)
82261816
Elapsed time = 0.070s
````

which suggests a rough `0.070 / 0.024 = 2.916x` speedup in the current implementation in Nightly.

**Comment by juj** [comment]
Also, since SIMD.js is not available in WebAssembly, attempting to build code that uses it with `-s WASM=1` is expected to fail, there doesn't currently exist a C side fallback to scalarize LLVM vector code.

**Comment by maksymmolchanovsc** [comment]
Thanks for response, @juj . Looks like the best way is to use asm.js in Firefox Nightly. I don't know if this issue must be closed or not.

**Comment by juj** [comment]
Ok, let me close this, since this is not an Emscripten bug (Emscripten successfully compiled the code that used `int16x8` and code works correctly, and fast when supported), but just that browsers and web specs are not yet ready for prime time for SIMD. In 2018 SIMD should get development in WebAssembly, which should get fast performance when Wasm is enabled as well.
