### ISSUE TITLE
callbacks doesn't work in threads

### ISSUE THREAD

**Issue by etienne02** [kripken/emscripten#5394]
Using callbacks in threads doesnt work, it seems to block the thread.
Here a simple test program (I use abort because printf doesn't work in theads)

```
#include <stdio.h>
#include <stdlib.h>
#include <pthread.h>

typedef void (*func)(int);

void test_func(int i)
{
	if(i == 2)
		printf("%i\n", i);
	else
		abort();
}

void* threadFunc(void* a)
{
	func fun;
	fun = test_func;	
	fun(4);

	return NULL;
}

int main()
{
	pthread_t pth;
	func f;

	pthread_create(&pth,NULL,threadFunc,"processing...");

	f = test_func;
	f(2);

	return 0;
}
```

In the javascript console, no exception is never thrown (one might be thrown because of the abort).

**Comment by juj** [comment]
This program would not be guaranteed to `abort();` even when compiled natively, because once the main thread `return 0;`s, all created pthreads are killed. The application is racing to reach `return 0;` on the main thread and `abort();` in the pthread, and whichever happens to occur first would change whether the `abort();` would be observed or not.

There's three ways to make the `abort();` observable:
  a) build with the `-s NO_EXIT_RUNTIME=1` linker flag, which causes `return 0;` to not quit the application.
  b) add the line `EM_ASM(Module['noExitRuntime'] = true);` (with `#include <emscripten.h>`) at the end of `main` before returning. That does the same as the linker flag above.
  c) build with the linker flag `-s PTHREAD_POOL_SIZE=N` where `N > 0`, and add a `pthread_join()` before returning from `main` to synchronously wait for the test function to execute. That should block until the `abort();` is reached.

The same reason is why you are seeing as if `printf` is not working in pthreads. Any of a)-c) should fix `printf` to occur in pthreads as well.
