### ISSUE TITLE
Benchmark on Math.sqrt and the same implementation with "Fast Inverse Square Root"

### ISSUE THREAD

**Issue by Becavalier** [kripken/emscripten#5439]
![image](https://user-images.githubusercontent.com/8282020/29052939-abcb447e-7c1f-11e7-8609-ee347ce2e710.png)

All those benchmark tests were implemented with Emscripten tool chain, and the generated webassembly binary was optimized with flag "-O3".

Generally speaking, the same "sqrt" function which implemented with "Fast Inverse Square Root" should be faster than "Math.sqrt" which is a native javascript function.

But the benchmark result is really different and weird.

The question is "I am not sure if this is a problem of emscripten or it should be like this?"

BTW, the test result is from "Version 62.0.3178.0 (Official Build) canary (64-bit)"

**Comment by Becavalier** [comment]
Here I will show you the source code:

```c
extern "C" {
	double EMSCRIPTEN_KEEPALIVE f64_sqrt (double number) {
	    long i;
	    float x, y;
	    const float f = 1.5F;
	    x = number * 0.5F;
	    y = number;
	    i = *(long *) &y;
	    i = 0x5f3759df - (i >> 1);
	    y = *(float *) &i;
	    y = y * (f - (x * y * y));

	    return number * y;
	}
}
```

**Comment by juj** [comment]
> Generally speaking, the same "sqrt" function which implemented with "Fast Inverse Square Root" should be faster than "Math.sqrt" which is a native javascript function.

The above code for square root is somewhat of a relic, and not particularly fast or precise anymore. It comes from an era when there did not exist specific hardware instructions for square roots. In the past in native execution outside Emscripten, I recall having benchmarked the code to be more than twice as slow compared to the SSE instruction for square roots (https://github.com/juj/MathGeoLib/blob/master/tests/MathFuncTests.cpp#L358). WebAssembly has a dedicated opcode for square roots that is implemented inline using SSE: https://webassembly.github.io/spec/exec/numerics.html#op-fsqrt, and asm.js does the same with `Math.sqrt`.

This bug tracker prefers to take in performance issues about Emscripten codegen, rather than about the performance in browsers or shells, those have their own bug trackers. So if you have two different C code snippets to compare where one should produce faster code and it does not, or you have a Emscripten compiled C code snippet with a wasm-dis dump that shows suboptimal codegen, then this bug tracker is the spot. If you find performance issues in Chrome/Chromium execution of WebAssembly, you can report them to https://bugs.chromium.org/p/chromium/issues/list, and for Firefox, at https://bugzilla.mozilla.org/.

**Comment by Becavalier** [comment]
Thanks, really make sense!
