### ISSUE TITLE
Web worker from static libraries

### ISSUE THREAD

**Issue by ihaalshcd** [kripken/emscripten#5453]
Hi, in my code there are several static libraries which were written by me and built with emscripten. There are several web workers inside this libs but when I call workers I get broken objects. When I instantiate object from static lib in my main file and pass it to web worker everything is ok, Is there any chance to call worker from static lib?

**Comment by juj** [comment]
I notice you already asked this in emscripten-discuss. Please let's use only one forum for your question, since it can otherwise split the conversation in two different places, which can be confusing.

There is a reply to the same question already at https://groups.google.com/forum/#!topic/emscripten-discuss/758YU-dgKrI, so let me close this and let's focus on the conversation in that thread.
