### ISSUE TITLE
Strange behavior with EM_ASM_

### ISSUE THREAD

**Issue by newnon** [kripken/emscripten#5480]
this block of code does not compile
```
EM_ASM_({
	var hit = {
		a: 'b',
		b: 'c'
	};
}, 1);

EM_ASM_({
	var trackId = 'tracker_index_' + $0;
}, 1);
```

but this ok

```
EM_ASM_({
	var hit = {
		a: 'b'
	};
        hit.b = 'c';
}, 1);

EM_ASM_({
	var trackId = 'tracker_index_' + $0;
}, 1);
```

**Comment by juj** [comment]
The `EM_ASM_` macro uses the [stringification operator](https://gcc.gnu.org/onlinedocs/gcc-3.4.3/cpp/Stringification.html) to carry the JavaScript code snippet to JavaScript. The `,` character seems to be fixed to delimit arguments to the preprocessor, and it does not see `{` and `}` as a scope. As a result,

```C
EM_ASM_({ var hit = { a: 'b', b: 'c' };}, 1);
```
is incorrectly transformed into
```C
emscripten_asm_const_int("{ var hit = { a: 'b'", b: 'c' };}, 1);
```

Try adding extra parentheses, like this:

```C
EM_ASM_(({ var hit = { a: 'b', b: 'c' };}), 1);
```

since that is something that C preprocessor knows to respect (`foo(a,b,(c,d),e)` is four parameters, not five). That correctly produces

```C
emscripten_asm_const_int("({ var hit = { a: 'b', b: 'c' };})", 1);
```

**Comment by juj** [comment]
Closing this as resolved, the above doubling parentheses trick is the way to get around the C preprocessor parsing issues.
