### ISSUE TITLE
c++17 support

### ISSUE THREAD

**Issue by dylhunn** [kripken/emscripten#5513]
This is more of a question than an issue.

I am trying to run `./em++ -g -std=c++17 test.cpp`, but emscripten doesn't appear to know about c++17. Are there any plans for this, or a workaround?

**Comment by dschuff** [comment]
Emscripten's C++ support tracks with the version of clang and libcxx that it uses. You can see the feature matrix here: https://clang.llvm.org/cxx_status.html Currently fastcomp is at clang 4.0. 5.0 just branched so maybe someone will update fastcomp sometime soon (for WebAssembly there is also the upstream LLVM, which tracks LLVM's trunk, if you want to live on the edge). For C++17 specifically, you can use the `-std=c++1z` option (instead of `-std=c++17` because the standard is not fully finalized (or was not as of clang 4.0)

**Comment by dylhunn** [comment]
Thank you; `-std=c++1z` provides the c++17 features I needed.

**Comment by soloproc** [comment]
So is it support C++17 fully now? @dschuff

**Comment by soloproc** [comment]
> So is it support C++17 fully now? @dschuff

oooh, i see.

**Comment by sbc100** [comment]
Yes.  Fastcomp is now on clang 6.0 and apparently "Clang 5 and later implement all the features of the ISO C++ 2017 standard."
