### ISSUE TITLE
Newbie Question: is mysql available?

### ISSUE THREAD

**Issue by burningreggae** [kripken/emscripten#5582]
Hi All!
Sorry for spamming issues thread..

Does anyone know if there is a ported mysql c-connector API ?
(library_msql.js?) or is it unpossible?

Thanks!

**Comment by juj** [comment]
There is no built-in core `src/library_mysql.js` or similar. The connector API is probably a non-trivial amount of work that anyone could just rewrite it as a single JavaScript file. The appropriate way would probably to go and port the appropriate connector API that MySQL provides at https://github.com/mysql to build through Emscripten. Although I am only able to find a C++ connector API, and no repository for a C one.

If I was asked to rate the difficulty of such a port, I think it would be 4/5 or "moderately hard", because it will likely involve some amount of TCP<->WebSocket emulation, and possibly developing Emscripten side WebSocket support as well. It should be doable though, can't think of a technical reason that would prevent this, but will definitely require expertise and familiarity with Emscripten.

**Comment by burningreggae** [comment]
Thank you!
