### ISSUE TITLE
emcc -c wont generate javascript code

### ISSUE THREAD

**Issue by cancerberoSgx** [kripken/emscripten#5738]
Hello all, Although I'm new with emcc I'm notice an undesirable behavior that is forcing me to manually edit my target project's Makefiles (apache lucy): Passing '-c' command line parameter makes emcc to compile to binary code instead javascript. Example
```
emcc test1.c -c -o test1.o.js
```
Actual result: test1.o.js is binary
Expected result: test1.o.js is javascript

Removing "-c" makes emcc works as expected. 

Thanks - BTW emcc is a great product - hopefully it will allow me to compile apache lucy (lucene in C) to javascript - let's see. Thanks and keep the good work.

**Comment by gauravdewan007** [comment]
This is the standard behavior of compiler driver like gcc or llvm or emcc
Refer documention of -c option at https://kripken.github.io/emscripten-site/docs/tools_reference/emcc.html#command-line-syntax
-c    Tells emcc to generate LLVM bitcode (which can then be linked with other bitcode files), instead of compiling all the way to JavaScript.

**Comment by cancerberoSgx** [comment]
Thanks, in that case I'm closing this issue, thanks and sorry for my ignorance.
