### ISSUE TITLE
Elimination of eval() usage in compiled Module (global goal)

### ISSUE THREAD

**Issue by nazar-pc** [kripken/emscripten#5753]
I've filled 2 PRs that eliminate some `eval()` usage (#5751, #5752), but I need help to eliminate all of them (if possible) and potentially drop `NO_DYNAMIC_EXECUTION` as unnecessary (that would be perfect!).

To fix:
* [x] 1. #5813
* [x] 2. #5815
* [x] 3. #5811

1. I found multiple instances of such use of `eval()`:
https://github.com/kripken/emscripten/blob/93479ecbd390aec4f8a3765fe04bcb365d0b31b2/src/shell.js#L290-L292

It seems to not be required, since with `NO_DYNAMIC_EXECUTION` `makeEval()` might be turned into exception.

Can someone explain me why is it there, what is it doing exactly and under which conditions?

2. https://github.com/kripken/emscripten/blob/93479ecbd390aec4f8a3765fe04bcb365d0b31b2/src/preamble.js#L125-L133

Is it still expected that some functions are going to be absent on `Module`? I think a better idea would be to put all functions there and eliminate `eval()`.

3. https://github.com/kripken/emscripten/blob/93479ecbd390aec4f8a3765fe04bcb365d0b31b2/src/preamble.js#L280-L291

How can I benchmark it and why is much shorter branch slower?

4. https://github.com/kripken/emscripten/blob/8e6e71e392ef5a4cdd767d5675841179fb81e944/src/runtime.js#L107-L115

I have no idea what is this and what is it used for. Can someone explain?

Other usages do not seem to affect builds, so I didn't mention them.

**Comment by kripken** [comment]
1. `globalEval` is used in implementing `Module.load()` in shell.js, which loads code in a js file. I think that might have been used in dynamic linking, but actually I don't see where it is used now. Might be worth trying to remove it and seeing if any tests fail, we probably don't need it.
2. We currently allow `ccall` to be used on something that is not exported, so it is not on Module. I think it would be reasonable to change that, since really, if something is not exported on Module then it might be eliminated anyhow. This might break things that shouldn't work anyhow, but I think with enough notice and documentation that's ok.
3. I thought we benchmarked that at the time, but in https://github.com/kripken/emscripten/pull/2345 where it was added I don't see it. Might be worth looking in issues from around that time. But creating an artificial benchmark should be ok too, basically a loop with a lot of ccalls in it. In general, the speedup should be from creating a static function that the JIT can optimize well.
4. `uninline` should not be emitted in the code, it is used by the js compiler internally at compile time only.

**Comment by nazar-pc** [comment]
How can I run tests in `ENVIRONMENT_IS_SHELL`, looks like it is not running in Travis CI tests, am I right?

**Comment by nazar-pc** [comment]
3. Difference is more than an order of magnitude (3.8s vs 51.6s on 10^6 calls of `x*x` function), will take a look how to make it faster without `eval()`

**Comment by kripken** [comment]
`ENVIRONMENT_IS_SHELL` is enabled for the spidermonkey shell (`js`) or v8 shell (`d8`). Yes, we don't have those on travis, they aren't tested there.

**Comment by nazar-pc** [comment]
How can I run tests against those? Maybe you have some script for this?

**Comment by dschuff** [comment]
Here's how to build d8, in a nutshell:
Get Chromium's `depot_tools` (see http://commondatastorage.googleapis.com/chrome-infra-docs/flat/depot_tools/docs/html/depot_tools_tutorial.html#_setting_up):
```
$ git clone https://chromium.googlesource.com/chromium/tools/depot_tools.git
$ export PATH=$PATH:/path/to/depot_tools
```
Get V8 sources:
```
$ fetch v8
$ cd v8
```
(Later you can update the sources: `$ git pull; gclient sync`)
Build v8 with GN (see https://github.com/v8/v8/wiki/Building-with-GN):
Generate the ninja build files (ninja is included in depot_tools), and build d8:
```
$ tools/dev/v8gen.py x64.release
ninja -C out.gn/x64.release d8
```

It's not the easiest thing in the world to build, but not super hard. SpiderMonkey's `js` shell supports the same API (as far as emscripten is concerned) is not really any more difficult to build, but you can't get the sources without also getting all of Firefox.

Then once you have `d8` (or `js`) you set the path in `V8_ENGINE` (or `SPIDERMONKEY_ENGINE`) in your emscripten config file, and set `JS_ENGINES = [V8_ENGINE]` which tells the test runner which engine to test against.

**Comment by nazar-pc** [comment]
Closing as 3 primary issues mentioned here were resolved, for other stuff we can always open separate issues.
