### ISSUE TITLE
`x` permission for Windows

### ISSUE THREAD

**Issue by saschanaz** [kripken/emscripten#5819]
Currently emscripten adds `x` bit depending on `w` bit on Windows:

https://github.com/kripken/emscripten/blob/0a7ef6f4b01167a71b67abbd052b8cd3f4952a54/src/library_nodefs.js#L22-L36

This is causing #5268 where `C:/Users` has permission 444 without `w` bit. Perhaps we should just add `x` without any condition? It's what Ubuntu on Windows is doing anyway.

**Comment by juj** [comment]
Hmm... On POSIX the `x` permission on a directory means that its contents can be traversed, e.g. enumerated with `readdir`. I wonder if we should instead propagate read bits to execute bits on Windows.

I don't think we'd want to unconditionally propagate the bits, because then Linux and macOS users would erroneously see all directories as having `x` if they have a `w`. You mention Ubuntu on Windows, I wonder if this configuration is at the heart of problem here? That is, Ubuntu on Windows would need this propagation as well (since it's on a Windows-based NTFS filesystem), but in that config `NODEFS.isWindows` returns false, because it's running an Ubuntu shell on Windows? So basically this would need to be a `NODEFS.isWindowsOrMSYSorCygwinOrUbuntuPOSIXShellOnWindows` type of flag?

**Comment by juj** [comment]
Err edit: `r` already allows `readdir`, but `x` is needed to enter the directory. (the distinction is quite subtle here..)
