### ISSUE TITLE
Support for RTP/RTSP in WebAssembly

### ISSUE THREAD

**Issue by gopal1022** [kripken/emscripten#5845]
I have a C++ code which provides a live RTP/RTSP video stream and want to transpile that code to web assembly.
So, before doing that I want to know whether web assembly support RTP/RTSP Live streaming or I have to make Changes in my Code for Live Streaming?

**Comment by luxueyan** [comment]
@gopal1022  The question has been the resolved ？

**Comment by gopal1022** [comment]
No, the problem was not resolved .

**Comment by harutk7** [comment]
Any news guys reguarding this topic

**Comment by brion** [comment]
In browsers, WebAssembly has the same i/o abilities that are available to the JavaScript that it's embedded in, because to communicate with the outside world it must do so by calling JavaScript.

As far as I know, JavaScript does not expose any sort of raw sockets or RTP/RTSP interface at the low level. You could run it on top of Web Sockets pehaps, but you might consider using WebRTC natively in the browser.

**Comment by rthawkcom** [comment]
Fast forward 7 years and yes it can be done now.  The newer SV3C cameras are using it to embed RTSP video in the cameras webpage using nothing but Wasm.  The video is a bit pixilated, but the audio is clear.
