### ISSUE TITLE
glGetBufferSubData question

### ISSUE THREAD

**Issue by underscorediscovery** [kripken/emscripten#5861]
Hi, I was looking to PR a missing endpoint for WebGL 2, `glGetBufferSubData`.
It's around 3 lines, it just seems to be missing is all. 

However, I noticed that this is not in the ES3 spec, but it is in the WebGL2 spec.
What's the right approach here from emscripten point of view? If including the ES3 headers from c side, the function is undefined. From what I understand this is needed for transform feedback and various other usages, so it would be good to have access to. 

Also worth noting there is an [async](https://www.khronos.org/registry/webgl/extensions/WEBGL_get_buffer_sub_data_async/) WebGL2 extension for it as well.

I'd happily PR given some clarity of intent with regards to an idiomatic addition.
Thanks!

**Comment by kripken** [comment]
This might need to wait on input from @juj (who is on vacation currently). But this is in non-ES3 GL (in `glext.h`), so I think we should implement it in the obvious way (3 lines as you said). I'm not sure what that means for being able to use it in ES3, but I'd hope just including `glext.h` and calling the function would work?

**Comment by underscorediscovery** [comment]
It does seem to be in [GL/glext.h](https://github.com/kripken/emscripten/blob/incoming/system/include/GL/glext.h#L4711) so provided the endpoint lands in the right place, it seems fine to me!

I wasn't sure if there was an existing protocol with regards to the overlap (or lack thereof) with the endpoints. But any further clarity or corrections can land in the PR, once it gets looked at. I had a question regarding the use of subarray vs the arg dataSrcOffset but as well, that would be a minor correction on the PR.

Thanks!

---

I'll add some notes for others, if you're wanting to use it, [EM_ASM works](https://gist.github.com/megaton/d8c6f48a0eb9f5c882eac33dd852a6af):

```c++
int size = ...
void* data = new char[size];

EM_ASM_(
{
  Module.ctx.getBufferSubData(Module.ctx.ARRAY_BUFFER, 0, HEAPU8.subarray($0, $0 + $1));
}, data, size);
```

**Comment by ssg3d** [comment]
> but I'd hope just including glext.h and calling the function would work?
It doesn't work as its wrapped inside GL_GLEXT_PROTOTYPES, and I am not too sure if its right to enable it (somehow).
@ruby0x1 your little EM_ASM snippet works great, thanks! Since you closed this issue, is there a way to access glGetBufferSubData normally that I missed or should we go the EM_ASM route?

**Comment by juj** [comment]
You can do `#define GL_GLEXT_PROTOTYPES 1` before including `GL/GLext.h`, that define is odd in that way that users are intended to define it.

Or even better, do `#include <webgl/webgl2.h>` to get `glGetBufferSubData()`, since in WebGL, it is not an extension function to WebGL 1, but a core function to WebGL 2.

> Also worth noting there is an [async](https://www.khronos.org/registry/webgl/extensions/WEBGL_get_buffer_sub_data_async/) WebGL2 extension for it as well.

(after the original ticket was filed, [that async extension was later rejected from the spec in 2018](https://registry.khronos.org/webgl/extensions/rejected/WEBGL_get_buffer_sub_data_async/))

> or should we go the EM_ASM route?

The EM_ASM block is not recommended, as it will not be compatible with different Emscripten build options like 4GB and Wasm64.

**Comment by ssg3d** [comment]
Thanks @juj that helped a lot!
