### ISSUE TITLE
Allow running on Python 3?

### ISSUE THREAD

**Issue by saschanaz** [kripken/emscripten#5950]
Now we have all PRs merged to pass CI with Py3 (except #5946), we now can allow Py3 rather than forcing Py2. What do you think?

We currently have two CIs running, so we may let one to run Py2 and the other to run Py3.

**Comment by kripken** [comment]
Yeah, we should move forward here. How about allowing Py3, but showing a warning when it is used, "this is experimental" or such?

Good idea about making one CI use 2, and the other 3. That can help a lot until we can move entirely to Py3.

**Comment by kripken** [comment]
Maybe it should even be a flag, `emcc --python3`? That might be excessive though.

**Comment by saschanaz** [comment]
>Yeah, we should move forward here. How about allowing Py3, but showing a warning when it is used, "this is experimental" or such?

:+1:

>Maybe it should even be a flag, `emcc --python3`? That might be excessive though.

That way every tests should add the flag, which is not preferable in my opinion. We may add a EMCC_OPTIONS environment variable and use `EMCC_OPTIONS=--python3` to reduce diffs (like [NODE_OPTIONS do](https://medium.com/the-node-js-collection/node-options-has-landed-in-8-x-5fba57af703d))

**Comment by juj** [comment]
I think I should work on getting Emsdk to bundle up Python 3 as an optional package as well, so that we can get Windows users optionally over to Python 3 when possible, to get people to test this out. I think once things are solid, we could even look at dropping Python 2 support, since Python community seems to be aggressive about it.

This is assuming that Python 3 has at least equally good Windows support, whereas Python 2 Windows was quite buggy for a long time in piping and multiprocessing support, causing some quite annoying workarounds.

**Comment by juj** [comment]
https://pythonclock.org is an interesting site.

**Comment by saschanaz** [comment]
Fixed by #5955
