### ISSUE TITLE
Clang fastcomp incoming (version 1.37.26) being built with gdb, leading to huge files

### ISSUE THREAD

**Issue by id01** [kripken/emscripten#6016]
The /clang/fastcomp folder was unusually huge with this version at 25GB, compared with 1GB for the master branch. When looking into the binaries and compile_commands.json file, it seems that emsdk was automatically compiling everything with debugging information. Stripping the files in /bin of debug headers greatly decreased file sizes. I'm currently at 6GB. I think the size can be decreased a lot more by removing debug from compilation by default?

**Comment by kripken** [comment]
I think the emsdk builds incoming from source with debug symbols by default, it assumes most people want a development build (while binary builds are non-debug, and I guess master too). @juj ?

I think we should change that, since incoming is basically what we recommend people use all the time now, so all builds should be non-debug by default.

**Comment by juj** [comment]
The history has been that `incoming` branch builds with CMake's `RelWithDebInfo` mode, which is CMake's intended "for developers" configuration, and `master` branch and tags build with `Release` mode, which is CMake's intended "for end users" configuration. I agree that there's multiple roles of developers ("developers of emscripten itself" vs "other developers who just use emscripten") that this is tripping up too many people, and they don't notice to add a `--build=Release` when they do a build of `incoming`, so changed to build `Release` in all cases in the above commit.

**Comment by kripken** [comment]
Great, thanks @juj !
