### ISSUE TITLE
Indirect memory representation

### ISSUE THREAD

**Issue by daurnimator** [kripken/emscripten#6087]
(continuing from IRC):

I'm trying to come up with a way to reference external typed arrays.
I think what is required is a new memory model for emscripten.

My first thoughts about an optimised implementation are to essentially have "pages", so that instead of the current `HEAP8[ptr]` we'd have (e.g. assuming 4096 byte pages) `HEAP8s[ptr>>12][ptr&4095]`
Where HEAP8s would be defined as:
```js
let PAGESIZE = 12; /* 4096 byte pages */
let buffer = new ArrayBuffer(TOTAL_MEMORY);
let HEAP8s = new Array(TOTAL_MEMORY>>PAGESIZE);
for (let i=0; i< HEAP8s.length;i++) {
    HEAP8s[i] = new Uint8Array(buffer, i<<PAGESIZE, Math.min(1<<PAGESIZE, TOTAL_MEMORY-i<<PAGESIZE));
}
```

The utility of such a scheme is that code can then dynamically add additional (external) pages. via an api like
```js
function mapPage(addr, buffer, start, len){ ... }
```

It could additionally solve the much-requested feature of growable memory.

Has such a scheme been considered before? What sort of performance impact did it have/would be expected?

**Comment by kripken** [comment]
As mentioned on IRC, the `SPLIT_MEMORY` option implements a model like `HEAP8s[ptr>>12][ptr&4095]`, so it sounds very close to what you want. You can test it out just by doing `-s SPLIT_MEMORY=8388608` (the value is how big the chunks/pages are, 8MB is reasonable). It defines `HEAP8s` etc. like you suggest.

The mode has a bunch of tests, so overall it should be usable. But it hasn't been rigorously tested, and looking at it now, I see it can't run the benchmarks because it fails to accept the argc/argv arguments properly for some reason. If you're interested to improve it, that would be great, I think it's a useful mode for certain use cases (importing typed arrays, freeing memory efficiently in memory growth, etc.), even if it does have a speed cost.

**Comment by daurnimator** [comment]
Split memory seems to just have an upper + a lower section. Rather than any number of sections.
Performance wise `SPLIT_MEMORY` adds a `if` to each memory access. I wonder if indexing into an array of buffers would be faster?

**Comment by kripken** [comment]
Is it possible you're looking at an old version? This hasn't changed in a while, but maybe in the far past we did an if on each access. Currently on incoming it does loads by calling this:
```
function get32(ptr) {
  ptr = ptr | 0;
  return HEAP32s[ptr >> SPLIT_MEMORY_BITS][(ptr & SPLIT_MEMORY_MASK) >> 2]| 0;
}
```
Given a pointer, it picks the right heap out of the array of buffers, as you suggest. (We could inline that and avoid the call, but for code size it's better not to, might be worth investigating that tradeoff though.)

How many buffers are in that array depends on how big the chunks are and how big memory is. It also allocates them on demand, so at startup you may see only 1 or 2, but the list has arbitrary length.

**Comment by daurnimator** [comment]
> Is it possible you're looking at an old version? This hasn't changed in a while, but maybe in the far past we did an if on each access.

Hrm. yes looking at the current HEAD is pretty much exactly what I described.

Will close this issues as already implemented.

**Comment by kripken** [comment]
It could be improved a lot more though, if you're interested.
