### ISSUE TITLE
SDL2 printf stopped working

### ISSUE THREAD

**Issue by Division** [kripken/emscripten#6104]
When I run compiled web app with SDL2 library, the std::cout and printf calls are not shown in the console.
As I understood, SDL redirects stdout to a file. Is there a workaround for it?

**Comment by kripken** [comment]
If you use the standard html template, it should show those things in the text area below the canvas. If you use a custom html, you need to define `Module.print`, otherwise it will use console.log which only shows up in the dev console.

**Comment by Division** [comment]
Yes, that's clear. But the logs are not appearing at any place. Logging works normally before
`emscripten_set_main_loop_arg` call. After the loop is started, no logs are showing for me at all.

Here are some discussions related for this topic:
https://forums.libsdl.org/viewtopic.php?t=2514&sid=6cc2e93b8460809383c917f0b775ab62
http://forums.devshed.com/programming-42/mingw-printf-sdl-836190.html

People say that it's related to the stdio redirect. And some compiler flags when building SDL may help. But I'm not sure is it true for SDL2.

**Comment by juj** [comment]
Double check that your print functions are line-buffered with `\n` ending in printf or `std::endl` in std::cout. SDL1/2 should not be redirecting stdout to a file in web builds that I have heard of at least.

If you are suspicious as to whether the code that's doing the printing is being executed at all, you can also try troubleshooting with `emscripten_log`, see examples in the file `tests/emscripten_log/emscripten_log.cpp`:

```c++
#include <emscripten.h>

...

	// Log to Emscripten Module.
	emscripten_log(EM_LOG_NO_PATHS, "Print a log message: int: %d, string: %s.", 42, "hello");
	emscripten_log(EM_LOG_NO_PATHS | EM_LOG_WARN, "Print a warning message");
	emscripten_log(EM_LOG_NO_PATHS | EM_LOG_ERROR, "This is an error!");

	// Log directly to Browser web inspector/console.
	emscripten_log(EM_LOG_NO_PATHS | EM_LOG_CONSOLE, "Info log to console: int: %d, string: %s", 42, "hello");
	emscripten_log(EM_LOG_NO_PATHS | EM_LOG_CONSOLE | EM_LOG_WARN, "Warning message to console.");
	emscripten_log(EM_LOG_NO_PATHS | EM_LOG_CONSOLE | EM_LOG_ERROR, "Error message to console! This should appear in red!");

	// Log to with full callstack information (both original C source and JS callstacks):
	emscripten_log(EM_LOG_C_STACK | EM_LOG_JS_STACK | EM_LOG_DEMANGLE, "A message with as full call stack information as possible:");

	// Log with just mangled JS callstacks:
	emscripten_log(EM_LOG_NO_PATHS | EM_LOG_JS_STACK, "This is a message with a mangled JS callstack:");

	// Log only clean C callstack:
	emscripten_log(EM_LOG_NO_PATHS | EM_LOG_C_STACK | EM_LOG_DEMANGLE, "This message should have a clean C callstack:");

	// We can leave out the message to just print out the callstack:
	printf("The following line should show just the callstack without a message:\n");
	emscripten_log(EM_LOG_NO_PATHS | EM_LOG_ERROR | EM_LOG_C_STACK | EM_LOG_JS_STACK | EM_LOG_DEMANGLE);
```

or by using `EM_ASM`:

```c++
#include <emscripten.h>

...

    EM_ASM(console.log('hello test'));
```

and check the web page console.

**Comment by Lachrista** [comment]
@juj When I minimize the browser window, emscripten_set_main_loop_arg is only called once per second, is it because the page loses focus, and to save performance, the emscripten_set_main_loop_arg rate is reduced?
I use emscripten_set_main_loop_timing,But it doesn't help either. Is there any way to solve this problem?

**Comment by juj** [comment]
> So I would assume that SDL2 does stdout redirect in the web build (at least in my case).

Hmm, that's interesting - perhaps they indeed do something special there. You can try adding a `fflush(stdout);` or similar in the code after `printf` to see if that would affect SDL2, or perhaps someone with more intimate knowledge of SDL2 stdio internals would know more here.

> @juj When I minimize the browser window, emscripten_set_main_loop_arg is only called once per second, is it because the page loses focus, and to save performance, the emscripten_set_main_loop_arg rate is reduced?
> I use emscripten_set_main_loop_timing,But it doesn't help either. Is there any way to solve this problem?

This is true, the throttling exists to save power. This throttling actually comes from the browser itself, Emscripten does not do any throttling logic. The way browsers throttle is that `requestAnimationFrame` calls start becoming geometrically more infrequent when the browser tab is not visible. There is no way to tell the browser to not throttle `requestAnimationFrame`s.

One way to work around the throttling is to switch to using `EM_TIMING_SETIMMEDIATE` or `EM_TIMING_SETTIMEOUT` instead of `EM_TIMING_RAF` mode. `EM_TIMING_SETIMMEDIATE` and `EM_TIMING_SETTIMEOUT` loops do not throttle when on the background, but unfortunately they are not ideal for animation when the tab is on the foreground (if you need smooth 60fps WebGL for example). One way to work around this is to detect browser `blur` and `focus` events yourself, and then adjust the main loop timing with `emscripten_set_main_loop_timing` from RAF to SETIMMEDIATE or SETTIMEOUT when going to background, and then back to RAF whenever on the foreground.

**Comment by Lachrista** [comment]
Thank you. I've solved it.
