### ISSUE TITLE
more tests should run in parallel

### ISSUE THREAD

**Issue by froydnj** [kripken/emscripten#6130]
I had to run the entirety of `test_other.py` today due to my own mistakes in getting individual tests to run.  Running this one test file was...not fun:

```
Ran 271 tests in 1970.620s
```

The only test suite where parallel test running is currently supported is `test_core`:

https://github.com/kripken/emscripten/blob/incoming/tests/runner.py#L1279

Surely other test suites could reasonably be converted to be run in parallel?

**Comment by kripken** [comment]
Yeah, `other` is slow...

The reason it isn't parallel is because it has a few tests which use a global location, the canonical temp dir. When `EMCC_DEBUG=1` is in the env, we emit logging and write temp files to `/tmp/emscripten_temp` (by default), and a few tests depend on that.

We could fix this by adding a decorator for "this test must run all by itself, not in parallel with others", and that decorate would grab a lock, and we'd add that decorator to just the few tests that need it (just a grep for EMCC_DEBUG should be enough). And then adding `other` to the paralellizable tests suites should work.

**Comment by saschanaz** [comment]
(See also #5817)
