### ISSUE TITLE
"inline" functions are being wrongly eliminated

### ISSUE THREAD

**Issue by wothke** [kripken/emscripten#6144]
I noticed the below issue using emscrption 1.37.29 (Win10, 64-bit portable version, fetched from here:  https://github.com/juj/emsdk). The version that I had been using previously was 1.35 - and the problem had not existed there.

Test-case: When building my little project here: https://github.com/wothke/websid using the makeEmscripten.bat script, there are suddenly "undefined symbol" warnings for various "inline" functions. The respective "inline" functions are all locally used in the respective .c files but for some reason the recent emscripten version completely eliminates them, i.e. the compiled output no longer works. 

I had already tried to remove the various optimizer settings that I am using in my respective make script, but those do NOT seem to trigger the problem.

**Comment by kripken** [comment]
This goes beyond my understanding of C and C++, but if you take even
```
inline void x() {
}
int main() {
  x();
}
```
and compile it natively with gcc or clang then it errors on "undefined reference to `x'". Removing the `inline`, as you said, makes it work.

It's unlikely both of those compilers has the same bug, so my guess is that it's something subtle in the C or C++ language spec, and it is wrong in Tiny'R'Sid, and it was wrong in older clang, but is now fixed.

**Comment by dschuff** [comment]
Are you defining an inline function only in a C file and then trying to use it from another C file or from JS? You do have to make sure all the declarations say inline, but without any details on the errors or how you built, it's hard to say anything concrete.

**Comment by kripken** [comment]
No, it's much weirder, see the testcase I posted - that's a single C file, built natively (no emscripten or JS involvement). In other words, defining a function as inline, and using it in that very same C file, does not work in either gcc or clang.

**Comment by dschuff** [comment]
Oh, I was confused because it actually works in C++ and not in C.

[C99](http://www.open-std.org/jtc1/sc22/wg14/www/docs/n1256.pdf) §6.7.4.6 says 
> If all of the file scope declarations for a function in a translation unit include the inline function
specifier without extern, then the definition in that translation unit is an inline
definition. An inline definition does not provide an external definition for the function,
and does not forbid an external definition in another translation unit. An inline definition
provides an alternative to an external definition, which a translator may use to implement
any call to the function in the same translation unit. It is unspecified whether a call to the
function uses the inline definition or the external definition

So what is happening is
1. The declaration as written does not result in an externally-visible (i.e. linkable) definition, as specified.
2. Because you used O0, the compiler is not actually inlining the function, instead it just emits a call (to the linker it's just another undefined reference).
3. The link fails because there's a reference but no definition.

The example in §6.7.4.8 shows the same restriction (saying that there needs to be an external definition of the inline function, and that that definition is distinct from the inline-declared one). So I think gcc and clang are being spec-compliant here. Also if you do run the optimizer, then `x` does get inlined and then there's no undefined reference, so no link failure. But the compiler is not required to inline the function.

For C++ they fixed this wierdness by saying in [§ 7.1.2.4](http://www.open-std.org/jtc1/sc22/wg21/docs/papers/2013/n3690.pdf) that an inline function definition has to be defined in all the translation units, and they make it work by further requiring that all the declarations be specified as inline, that the definitions all be the same, and that the definitions all get the same address.

So I doubt the frontend behavior has changed between emscripten versions. It's possible that you are compiling with different optimization flags (or maybe that emscripten is now using a C frontend where it was previously using a C++ frontend?)

**Comment by wothke** [comment]
Thanks for the analysis/explanation: So I guess this is just standard C crap and I was just lucky that my earlier emscripten environment has been using and "incorrect" CLANG version.. I guess I'd have to use a #define to get some semantics that would stand to reason  (I had forgotten what a piece of crap C actually is - so I'll have to change my code) :-)

**Comment by wothke** [comment]
I guess this can be closed then

**Comment by hostilefork** [comment]
You can work around it with `inline static`:

https://stackoverflow.com/questions/7762731/whats-the-difference-between-static-and-static-inline-function

(Though as is oft-emphasized, the standard keyword `inline` is only a "suggestion" to inline.)
