### ISSUE TITLE
"--closure 1" breaks wasm output

### ISSUE THREAD

**Issue by wothke** [kripken/emscripten#6145]
I noticed the below issue using (the latest precompiled) emscripten 1.37.9 (Win10, 64-bit portable version, fetched from here:  https://github.com/juj/emsdk). 

The "--closure 1" option seems to break wasm output.

Test-case: Extract the attached "websidtest" ([websidtest.zip](https://github.com/kripken/emscripten/files/1667405/websidtest.zip)) folder to the document root of your webserver. Verify that this old version still works correctly (e.g. http://localhost/websidtest) - i.e. there should be some music. Now replace the "old" working version of the contained backend_tinyrsid.js using the respective newly compiled wasm output:
Use my little project here: https://github.com/wothke/websid and add " -s WASM=1 " to my respective makeEmscripten.bat script (you may need to patch about half a dozen "inline" functions until issue #6144 - which I just reported - has also been solved -> to make sure all the respective "undefined symbol" warnings are gone).

When using the new output (copy the .js + .wasm to the above folder) the web page no longer works and you'll find respective error messages in the browser's console. These problems disapear if you set "--closure 0" in the respective makeEmscripten.bat, i.e. "--closure 1" has some undesirable effect on the wasm output.

**Comment by kripken** [comment]
I'm having trouble following your steps. When I run the `.sh` file, I get `cat: htdocs/tinyrsid2.js: No such file or directory`. Also, when I copy over the `htdocs/backend_tinyrsid.js` file (is that the right one?) I see a runtime error on the page about a missing `.mem` file (maybe building with `-s SINGLE_FILE=1` would would help? Or do you want a separate .mem file?)

It might be simplest if you created a repo or zip file with everything together and a `.sh` file that does everything to build and copy over the right file(s).

**Comment by wothke** [comment]
I am using Win10 so it would be the .bat file that you'd need to use to build (The .sh script has been contributed by somebody else and I never used it - nor did I check if it is actually in a working condition).

My build file does NOT use a separate .mem file.. it just creates the backend_tinyrsid.js (any other .js files are just temporary files) as its final output (the file contains the emscipten output wrapped by some static JavaScript).

When you add the  "-s WASM=1" you'll then obviously get an additional .wasm file..

**Comment by kripken** [comment]
Oh ok, I am not on windows, so I tried the `.sh` one first... and yeah, it doesn't work.

I edited the `.bat` one into something that works with wasm:
```
set -e
emcc -s VERBOSE=0 -Wno-pointer-sign -I./src -Os -O3  --memory-init-file 0 --closure 1 --llvm-lto 1 -s NO_FILESYSTEM=1 src/memory.c src/base.c src/cpu.c src/hacks.c src/cia.c src/vic.c src/rsidengine.c src/sid.c src/digi.c src/sidplayer.c -s EXPORTED_FUNCTIONS="['_alloc','_loadSidFile', '_playTune', '_getMusicInfo', '_getSampleRate', '_getSoundBuffer', '_getSoundBufferLen', '_computeAudioSamples', '_enableVoices', '_malloc', '_free']" -o htdocs/tinyrsid2.js -s 'EXTRA_EXPORTED_RUNTIME_METHODS=["ccall"]' -s WASM=1 -s SINGLE_FILE=1 -s BINARYEN_ASYNC_COMPILATION=0 -s 'BINARYEN_TRAP_MODE="clamp"'
cat shell-pre.js > htdocs/tinyrsid.js
cat htdocs/tinyrsid2.js >> htdocs/tinyrsid.js
cat shell-post.js >> htdocs/tinyrsid.js
cat htdocs/tinyrsid.js > htdocs/backend_tinyrsid.js
cat tinyrsid_adapter.js >> htdocs/backend_tinyrsid.js
```
There were several issues along the way that are fixed in the above:
 * I had to add malloc and free to the exported functions, as they are used from your JS which is added later (and so the compiler can't tell they are used). (The optimizer was not powerful enough to remove them in the past, but it's always been the right thing to do to export things you will use.)
 * I also had to export `ccall` from the JS runtime (that's the `EXTRA_EXPORTED_RUNTIME_METHODS`). Emscripten recently switched to not export all the JS runtime by default, you must export what you need.
 * The JS uses the compiled code synchronously. This is ok with asm.js which is compiled that way, as long as you don't load a mem init file (which you don't) or anything else async. But in wasm, compilation is async by default, so you need to wait for it to be ready, see https://kripken.github.io/emscripten-site/docs/getting_started/FAQ.html#how-can-i-tell-when-the-page-is-fully-loaded-and-it-is-safe-to-call-compiled-functions Alternatively, you can disable async compilation (which is what I did here), but that might not work in some browsers, so it's not recommended. For similar reasons I added SINGLE_FILE so that the wasm file is embedded and not loaded asynchronously.
 * You were emitting html and only using the JS from that. That's dangerous, as the two can interact in various ways - it's better to just tell emcc to emit `.js` as I changed it to.
 * The code traps at runtime on integer divide by zero. That works in asm.js since it clamps values by default, but wasm doesn't. I changed `BINARYEN_TRAP_MODE` to clamp to get around that.

With those changes, it works ok, including with closure.

Not sure why you saw a closure issue, maybe it interacted with one of the above issues for you, and it seemed like closure was at fault. Also could be on an earlier version there was a closure bug (I tried on latest, 1.37.29).

Btw, the Yie Ar King Fu music brings back memories... :)

**Comment by wothke** [comment]
Thanks a lot. I realized just now that the "latest" version I am using refers to the precompiled releases and not the source so I am actually using 1.37.9 (not 1.37.29). That version does NOT seem to know switches like SINGLE_FILE yet (also it specifically warns: "WARNING:root:closure compiler is known to have issues with binaryen (FIXME)"), and there is probably no point for me to go on before I have setup a local development env that allows me to build 1.37.29 from source (I am still looking for some docs describing what tools are actually needed to do that.. the respective description in README.md unfortunately is rather useless..).

But one suggestion that I already came across is this one:
> "failed to compile wasm module: RangeError: WebAssembly.Compile is disallowed on the main thread, if the buffer size is larger than 4KB. Use WebAssembly.compile, or compile on a worker thread"

Actually I would love to use WebAssembly.compile and initialize Module directly rather just set the wasmBinary and waste my time with the browser's silly limitations ragarding what can or cannot be done from what thread.. but what would be the emscripten API to do that?

Btw: for more nostalgic memories you could also try this page here: http://www.wothke.ch/tinyrsid/index.php/charts :-)

**Comment by wothke** [comment]
update: I meanwhile managed to "install" 1.37.29 from source (using emsdk) only to find that "activate" fails miserably due to the outdated/unusable Java version that comes with 1.37.29. It seems that the build replaced the "good" Java version that I already had from 1.37.9 with some shitty outdated version that does not work. From what I saw the respectice problem (see unintelligible "CommandLineRunner : Unsupported major.minor version 52.0" message) has already been reported :-(

**Comment by kripken** [comment]
About using async compilation and checking when the code is ready to run, there are a few API options, see

https://kripken.github.io/emscripten-site/docs/getting_started/FAQ.html#how-can-i-tell-when-the-page-is-fully-loaded-and-it-is-safe-to-call-compiled-functions

> Btw: for more nostalgic memories you could also try this page here: http://www.wothke.ch/tinyrsid/index.php/charts :-)

Nice! :)

**Comment by wothke** [comment]
thanks, that's what I have based my current impl on (actually I am using "onRuntimeInitialized" and that works fine - I had tried the same using "_main" but for some reason that was never invoked..)

I guess this issue can be closed then... it still might be a good idea to add a little recommendation on your  https://github.com/kripken/emscripten/wiki/WebAssembly page regarding the emscripten versions that should be used or rather avoided if someone wants to use the feature..

**Comment by kripken** [comment]
Thanks, yeah, I have a PR to update the relevant docs open, #6126

**Comment by juj** [comment]
Emsdk should come with Java 8.152:

```
C:\code\emsdk>where java
C:\code\emsdk\java\8.152_64bit\bin\java.exe
```

we did update it recently to get past the Closure error - perhaps your emsdk installation did not grab that update for some reason? Trying with

```
git clone https://github.com/juj/emsdk.git
cd emsdk
emsdk update-tags
emsdk install latest
emsdk activate latest
```

should get Emsdk 1.37.32 with Java 8.152.
