### ISSUE TITLE
`emsdk install latest` takes hours if system doesn't have git.

### ISSUE THREAD

**Issue by kkimdev** [kripken/emscripten#6165]
I'm not sure if this is working as intended or not, but I noticed that on Ubuntu LTS, if system does not have git installed, `emsdk install latest` takes hours to complete.   Looking at the log, it's building LLVM from scratch if git is not available.

The reason I suspect that it's `git` is that we have continuous integration that builds Emscripten docker image, and one line change `apt-get install git` , made the difference.

**Comment by kkimdev** [comment]
I can provide a minimal reproducible Dockerfile if desired.

**Comment by juj** [comment]
Thanks for reporting, this was a bug. What happened is the code looked like

```py
def update():
   if git_available: download_git_tags_list()
   else: return
   download_precompiled_tags_list()
```

and as a result if one did not have git, it would neither attempt to download the list of available precompiled builds either, hence falling back to observing that there's no precompiled builds at all, and an installation from source needs to be done. Fixed in the above commit.

**Comment by kkimdev** [comment]
that was a quick fix! thans! :)
