### ISSUE TITLE
BREAKING EM_ASM API change

### ISSUE THREAD

**Issue by jgravelle-google** [kripken/emscripten#6213]
See: https://github.com/kripken/emscripten/pull/6163

So there's no way to support EM_ASM in the LLVM wasm backend without compromising on one of the following:

1. No EM_ASM-specific knowledge in upstream LLVM
2. C support
3. No API changes

We're thinking of going with option 3. Specifically one of the following APIs:
A. `EM_ASM_idd(return $0 + $1 * $2, a, b, c)`
B. `EM_ASM(idd, return $0 + $1 * $2, a, b, c)`
C. `EM_ASM(return $0 + $1 * $2, idd, a, b, c)`
Additionally, we'll need to limit the number of arguments to a given call to EM_ASM to somewhere in the 4-6 range.

Asm.js and asm2wasm users should be unaffected. We can define the new APIs to convert to the existing EM_ASM APIs for users who use both backends (also our test suite).
But, the wasm backend will become the default backend, and at that time this will be a breaking change.

Questions:
Which API is best? (I have a slight preference for B.)
Should this wait for [EM_JS](https://github.com/kripken/emscripten/issues/6147) as a potential upgrade path? (Probably not, it's a sufficiently large restructuring that I'm not sure users will want to do it, unless you have too many arguments and need to)

**Comment by kripken** [comment]
Another option we maybe didn't look enough into is using the native inline asm functionality, which emscripten used to use but stopped because of escaping issues. Ignoring the escaping, this does keep all the important information in the bitcode, I believe, e.g.
```
int main() {
  int a = 10, b, c = 123;
  asm ("waka waka;"
       : "=r"(b)        /* output */
       : "r"(a), "r"(c) /* input */
       : "%eax"         /* clobbered register */
       );  
  return b;
}
``` => ```
define i32 @main() local_unnamed_addr #0 {
entry:
  %0 = tail call i32 asm "waka waka;", "=r,r,r,~{eax},~{dirflag},~{fpsr},~{flags}"(i32 10, i32 123) #1, !srcloc !2
  ret i32 %0
}
```
By wrapping `asm` with a macro, this might be about as good as EM_ASM is.

(One possible concern about this approach is I've heard people want to use `asm()` for literal inline wasm. I'm not sure how that could work exactly or why, but maybe there's a way to do both if we really want that.)

**Comment by juj** [comment]
> So there's no way to support EM_ASM in the LLVM wasm backend without compromising on one of the following:

Hmm, sorry if I missed the core idea on the other thread, but can you expand a bit on the root issue? In fastcomp backend we can neither support integer vs double input parameters, but all input parameters get casted to doubles/Numbers. So this means that `EM_ASM_VOID` is always of signature `vd*` (`*` here with the meaning of zero or more), `EM_ASM_INT` is a `id*`, and `EM_ASM_DOUBLE` is a signature `dd*`.

> `EM_ASM_idd(return $0 + $1 * $2, a, b, c)`

In here, can you touch a bit on what `idd` refers to - the usual convention has been that in these kind of signature strings, the first param would denote the return value, and the subsequent ones are the input parameters, but in this example I wonder if it was meant that `a` is an integer and `b` and `c` are doubles? Or was this intended to be a `iddd`, i.e. the three inputs are doubles, and the return is an integer that the computation would get casted to?

Since in fastcomp we are not able to support denoting the types of the input parameters either, but they're all elevated to doubles, I think we don't need to do that in wasm backend either for `EM_ASM`(?). The `_VOID`, `_INT` and `_DOUBLE` suffixes are able to label the return type of the macro, so that's the only bit of the signature we are able to specify.

Or is it the variadicity of the input arguments that is the problem, i.e. it's proving tricky to identify how many input parameters are coming in to the macro?

**Comment by jgravelle-google** [comment]
The problems are:
* We don't have any special handling for EM_ASM in the wasm backend, at all. (We would like to keep it that way, but that's one of the axes we can consider compromising on)
* The `em_asm_const_*` functions are called with the non-vararg calling convention, but the function prototype is variadic. With special backend handling this isn't a problem, but without that we lower the call into a variadic call, and stuff the parameters into a vararg buffer
* Once in a vararg buffer, by the time we see the code in binaryen we have lost all information about the arguments, so we can't do anything there.
* We also haven't converted the arguments to doubles, so they are either ints or floats, and we don't know which. C has no way to say "give me a vararg buffer of only doubles", so we need to inject that logic somewhere, only for EM_ASM.

The fundamental problem is that EM_ASM is nearly inexpressible in C, and relies on compiler magic to work. It's doable by using macros and templates to extract the type information in the frontend and preserve it in the runtime, but that has something near a 10x performance overhead. (https://github.com/kripken/emscripten/pull/6163) Which is another option to compromise on:
D. No API changes, 10x slowdown, don't use EM_ASM in tight loops

**Comment by curiousdannii** [comment]
I'd go with whichever option is simplest to implement. Library functions are always an option if performance matters.

**Comment by jgravelle-google** [comment]
> Library functions are always an option if performance matters.

Yeah I'm thinking that's the way to go. So for now the simplest then is to just land https://github.com/kripken/emscripten/pull/6163, and accept the performance hit. If that becomes a problem we can always break the API later.

Closing this for now.
