### ISSUE TITLE
Compile to wasm object files when using LLD

### ISSUE THREAD

**Issue by sbc100** [kripken/emscripten#6232]
Right now we have `EMCC_EXPERIMENTAL_USE_LLD=1` which uses lld at link time, but still uses  `.bc` as the object format and performs whole program compilation with `llc` at link time.

To reap the benefits of using `lld` and (hopefully) speed up link time significantly we should be compiling to
wasm object files and using `lld` to link them.

**Comment by kripken** [comment]
What are you thinking here in terms of the options? It seems useful to keep the current mode possible, so would there be a flag for each, perhaps?

**Comment by sbc100** [comment]
I'm not sure we need to keep the current mode do we?  What would be the benefit?

**Comment by kripken** [comment]
A minor benefit would be a direct comparison to asm2wasm, but the bigger issue is how good dce is. Are we sure that dce will be better in the new model (versus dce on the bitcode)? And how would lto (including lto passes, not just bitcode linking) work there?

**Comment by sbc100** [comment]
DCE should be not be a problem.  `--gc-sections` is enabled by default it is should be precise, based on the entry point + any exported symbols. 

LTO is a different story, you are correct, we could need to make sure that was working before we switch over.

**Comment by kripken** [comment]
I'm still a little worried about DCE because LLVM IR is pretty detailed. All the intrinsics and attributes may be relevant, I suspect, but I don't have a concrete example. So if it's not hard I think it would be nice to be able to compare to the bitcode linking approach to test that (if it is hard, we'll still be able to compare to asm2wasm, I suppose, but many other differences would come in there).

**Comment by sbc100** [comment]
Dup of #6830
