### ISSUE TITLE
Oniguruma build fails with symbol multiply defined error

### ISSUE THREAD

**Issue by NeekSandhu** [kripken/emscripten#6239]
Followed this guide: http://kripken.github.io/emscripten-site/docs/compiling/Building-Projects.html#building-projects

These steps work without spitting non-zero exit code
```bash
# Run emconfigure with the normal configure command as an argument.
./emconfigure ./configure

# Run emmake with the normal make to generate linked LLVM bitcode.
./emmake make
```

But fails at last one : (
```bash
$ emcc src/.libs/libonig.a -s WASM=1 -o onig.js
error: Linking globals named 'regcomp': symbol multiply defined!
ERROR:root:Failed to run llvm optimizations:
```

I did a global search in files for `regcomp` identifier and found only two occurrences where it is defined, and one of them is a header file, which I don't think should bother compiler that much. Not sure how to make it happy at this point.

At this point (4 days of struggle with all this) I'd owe anyone for life. Help much appreciated.

I wanted to add this to emscripten-ports repo as well.

**Comment by kripken** [comment]
Probably the issue is that regcomp is present in libc, and linking in libc to a program where it already exists fails. To check that, you can run `llvm-nm` on that `.a` file, and on `~/.emscripten_cache/asmjs/libc.bc`, and grep for `regcomp`. If both are "T", then it is defined in both and that is the problem.

Assuming that's the issue, the question is, how is that library normally worked - does it replace part of libc, or does it use some native linking magic (weak linking?) somehow?

**Comment by NeekSandhu** [comment]
Thank you so much!

Although issue not yet resolved, but confirmed at least

> libc.bc
```bash
sweetslush@ubuntu:~/.emscripten_cache/asmjs$ llvm-nm libc.bc | grep "regcomp"
-------- T regcomp
```

> libonig.a
```bash
sweetslush@ubuntu:~/.../oniguruma$ llvm-nm src/.libs/libonig.a | grep "regcomp"
regcomp_64e0bb8d.o:
-------- T regcomp
```

I did create the same [issue](https://github.com/kkos/oniguruma/issues/77) in `oniguruma` repository and the author says to compile `libonig` without including files defining `regcomp` symbol, but I really don't know the implications it may bring. I'm gonna look more deeply into it.

In the meantime (also if above doesn't work),  is there any way we can somehow suppress `libc`'s definition?
