### ISSUE TITLE
[Docs] Search results show HTML

### ISSUE THREAD

**Issue by curiousdannii** [kripken/emscripten#6452]
The search results on the site show the HTML header of each page rather than a meaningful snippet: http://kripken.github.io/emscripten-site/search.html?q=modularize&check_keywords=yes&area=default

**Comment by DJMcNab** [comment]
From some debugging, it looks like this issue is actually showing the text from the github pages 404 page. This is because as of https://github.com/kripken/emscripten-site/commit/26135aa011bbf0fcfe727b7e7350d1296ce26768, the sources are no longer put on the github pages site. However, the search function used the sources to generate the snippets.

I'm not sure what you did in that commit, but in theory stopping doing it should probably fix this.

**Comment by kripken** [comment]
Thanks @DJMcNab ! My bad, I didn't realize the sources were needed. Pushed a fix now.

**Comment by DJMcNab** [comment]
No problem. Happy to help.

**Comment by pidddgy** [comment]
https://github.com/kripken/emscripten/issues/4012

this issue could be closed because @kripken said he already pushed a fix
