### ISSUE TITLE
std::sinh produces inconsistent results

### ISSUE THREAD

**Issue by r0mai** [kripken/emscripten#6686]
asm.js compiled code produces different results depending on whether the compiler can calculate sinh results at compile time or not. See the following, minimal C example:

```c
#include <math.h>
#include <stdio.h>

double sinh_inline(double x) {
    return sinh(x);
}

double __attribute__((noinline)) sinh_noinline(double x) {
    return sinh(x);
}

int main() {
    double x = 36.92167602106005;

    printf("  sinh_inline(%.14f) = %.14f\n", x, sinh_inline(x));
    printf("sinh_noinline(%.14f) = %.14f\n", x, sinh_noinline(x));
}
```

Compile:
```
$ emcc main.cpp -O2 -s WASM=0
```

Output:
```
$ node ./a.out.js
  sinh_inline(36.92167602106005) = 5418139254827422.00000000000000
sinh_noinline(36.92167602106005) = 5418139254827421.00000000000000
```

As you can see, the compiler produces a different result if the `sinh()` result is calculated at runtime or at compile time. The constant `36.92167602106005` is not very special. This difference can be reproduced with many different values.

The "correct" result is what the inlined (compile time) version returns. In this sense, correct means that `5418139254827422` is returned by `Math.sinh()` in JS or on the native platforms I tried on.

I can reproduce this with emscripten version 1.38.5 and 1.36.7, most likely affects more versions.

Based on my investigation, the root cause could be, that asm.js code can't use the JS builtin `Math.sinh()` function as per the [asm.js specification](http://asmjs.org/spec/latest/#standard-library), and instead has [its own implementation](https://github.com/kripken/emscripten/blob/incoming/system/lib/libc/musl/src/math/sinh.c). This implementation on the other hand does not return the same result clang thinks the standard sinh() function should return.

**Comment by kripken** [comment]
This is also the case in wasm, not just asm.js. Yes, the underlying issue is likely that the musl libc's sinh is not identical in behavior to the LLVM optimizer's, which likely uses the system libc. I'm not sure if the C spec defines the precision that sinh is meant to have. Here is a gnu libc doc page on math function errors, for example: https://www.gnu.org/software/libc/manual/html_node/Errors-in-Math-Functions.html So I suspect this may just be a minor rounding error that may exist between libcs. 

It's also possible that's not a reasonable rounding error but actually a bug in musl, though.
