### ISSUE TITLE
closure compiler: Duplicate case in a switch statement

### ISSUE THREAD

**Issue by athei** [kripken/emscripten#6828]
As soon as I add some EM_ASM or EM_JS statements to my C code I get the following error from the closure compiler. Without closure there are no problems.
```
Traceback (most recent call last):
  File "/usr/local/opt/emscripten/libexec/em++", line 15, in <module>
    python_selector.run(emcc)
  File "/usr/local/Cellar/emscripten/1.38.8/libexec/tools/python_selector.py", line 38, in run
    sys.exit(run_by_import(filename, main) if on_allowed_version() else run_by_subprocess(filename))
  File "/usr/local/Cellar/emscripten/1.38.8/libexec/tools/python_selector.py", line 13, in run_by_import
    return getattr(importlib.import_module(os.path.basename(filename)), main)()
  File "/usr/local/Cellar/emscripten/1.38.8/libexec/emcc.py", line 2019, in run
    wasm_text_target, misc_temp_files, optimizer)
  File "/usr/local/Cellar/emscripten/1.38.8/libexec/emcc.py", line 2559, in do_binaryen
    emit_symbol_map=emit_symbol_map)
  File "/usr/local/Cellar/emscripten/1.38.8/libexec/tools/shared.py", line 2492, in minify_wasm_js
    js_file = Building.closure_compiler(js_file, pretty=not minify_whitespace)
  File "/usr/local/Cellar/emscripten/1.38.8/libexec/tools/shared.py", line 2456, in closure_compiler
    raise Exception('closure compiler error: ' + process.stdout + ' (rc: %d)' % process.returncode)
Exception: closure compiler error: /tmp/tmpjBc_rf/engine.bc.o.js.mem.js.jso.js.jso.js.jso.js:1: WARNING - Duplicate case in a switch statement.
```
C Code:
```
int main( int, char** )
{
  initialize_data();
  EM_ASM(
    engine_callbacks.loaded();
  );
}
```

Removing EM_ASM resolves the error. Compiler flags:
```
-O3
-flto
--llvm-lto 1 --closure 1
-s TOTAL_MEMORY=256MB
-s WASM_MEM_MAX=1024MB
-s ALLOW_MEMORY_GROWTH=1
-s MODULARIZE=1
-s EXPORT_NAME=Simc
-s EXTRA_EXPORTED_RUNTIME_METHODS='["_free", "allocateUTF8"]'
-s EXPORTED_FUNCTIONS='["_main", "_simulate"]'
```

**Emscripten 1.38.8**

**Comment by kripken** [comment]
The EM_ASM probably causes code to be kept alive, some of which contains the code closure complains about.

To debug a closure error like this, use `-g1` so whitespace is preserved, and then the closure error message should contain more useful context. If that's not enough, build with `EMCC_DEBUG=2` in the shell, and the temp dir (`/tmp/emscripten_temp` by default) will contain the input file to closure.

**Comment by athei** [comment]
Yes this does help with the compilation. However, the closure compiler changed the names of function calls to single letter names. Instead of ignoring errors one must declare them as [externals](https://developers.google.com/closure/compiler/docs/api-tutorial3#externs).

Use the `EMCC_CLOSURE_ARGS` environment variable of emscripten to define the `--externals` flag to closure.

**Comment by hostilefork** [comment]
@athei I'm having an issue extremely similar to yours.

I've tried to set the EMCC_CLOSURE_ARGS environment variable with the `--externs` flag (not --externals, which doesn't seem to exist).  The only thing I can get it to take is a filename, so I give it a `closure-externs.json` which it seems to read.  But naming things in that list alone does not stop the "variable is undeclare" errors.

Is all you did e.g. to make a file like closure-externs.json containing:

    ['engine_callbacks']

...and then the error went away for you?  In my case, it doesn't seem there's any effect from me putting things in the list.  :-/

The definitions I have that are claiming to be undeclared are some cwraps and other service functions in my --post-js file, but as I say, naming them explicitly in this closure compile --externs doesn't seem to be helping.  Otherwise problem seems identical to the one here.  Might you or @kripken have any insight?
