### ISSUE TITLE
llvm backend pass for emscripten setjmp/longjump doen't work with separate compilation

### ISSUE THREAD

**Issue by sbc100** [kripken/emscripten#6840]
This pass is broken since it assumes it runs on the whole program and can create globals that are unique within the program.

I have a propose fix that moves the globals into a libcxxabi extras file so they exist at link time but are not autogenerated.

LLVM side: https://reviews.llvm.org/D49208

**Comment by dschuff** [comment]
So, moving the discussion of https://reviews.llvm.org/D49208 vs https://reviews.llvm.org/D49263 here from the CLs; the question of "should we generate weakly-linked functions in each object file" vs "should we include them via a library". We ended up with the former for now, which is fine, with the question of "what do we do later" still open. Basically I'm bringing this back up because @sbc100 said something along the lines of "Hopefully all this code will be removed pretty soon anyway". Unfortunately I don't think it really will because even once we have real exceptions in wasm, it will be quite a while before all the browsers support it, so we'll need to have the old option until they become ubiquitous. So as I said in the CL, I think I prefer the approach of linking this code in from a library rather than generating N copies of it. It's more consistent with how system code is usually included into programs (i.e. linking it in rather than generating it magically from the compiler). It's also easier to read and understand for non-compiler developers. Ideally LLVM wouldn't do codegen specific to emscripten (and instead we'd do transformations in wasm-emscripten-finalize) but I'm not sure that would work in this case, and anyway since we have the code there already, I'm not necessarily eager to rewrite it.

But I do think that at some point we should move relevant code to a library; perhaps whatever library @aheejin eventually uses for the runtime code for the native exceptions (e.g. probably libc++abi).

**Comment by aheejin** [comment]
I think it is possible to generate them in binaryen but I don't think that's a good place to do it, because, even if we've strived to avoid doing emscripten-specific things in llvm, we've already done it in `LowerEmscriptenEHSjLj` pass (sorry!), and separating that into two pieces would just make things worse.

I generally agree with that linking approach is more normal and better. Not that it's something we have to do now though. And I also think that code is gonna stay for quite long time. By the way, if we link them from the library, if we don't use exceptions, do they still get linked and increase binary size? I don't know how wasm linker handles it.

**Comment by sbc100** [comment]
I'm happy to look into moving these helpers in C source code, most likely as you say in the emscripten copy of  libc++abi.  I think we can avoid linking them unless they are needed.  However, i'm not sure its a priority.    Shall we open a new bug to make that transition and close this one?

**Comment by dschuff** [comment]
Yeah I think it's not a priority. Probably the right time to reconsider is when we have the situation we want with native exceptions, and then we can make something corresponding for without.

**Comment by dschuff** [comment]
So the current state is that we fixed LowerEmscriptenEHSjLj to work with wasm object files, right? If so then yeah I think we can close this.

**Comment by jgravelle-google** [comment]
Yeah, this has been working since @aheejin fixed it, closing.
