### ISSUE TITLE
CMake error with modules installed via pip (v1.34.12)

### ISSUE THREAD

**Issue by TidbitSoftware** [kripken/emscripten#7037]
First off, let me state that I realize you probably don't provide support for legacy versions of Emscripten and I am really just looking to gain some higher level insights on its structure/development. I have scoured the Emscripten site for answers to this issue, but have been unsuccessful.

I have another configuration of my project that _does not_ use Emscripten, rather it runs through the Python 2.7 interpreter and depends on mathematics packages like SciPy. Up until recently, we installed these locally rather than at the system or user levels, but decided to make a change for long term maintainability. We landed on a stable build that installs SciPy and dependencies via pip.

A second configuration of the project uses Emscripten, and up until the above, we have had a stable build using version 1.34.12. Now, however, building of Emscripten fails with,

```
-- Constructing LLVMBuild project information
CMake Error at CMakeLists.txt:444 (message):
  Unexpected failure executing llvm-build: llvm-build: fatal error: component
  u'MipsCodeGen' has invalid reference u';LOCALMOD' (via 'required library')
```

If I remove all packages installed via pip, Emscripten builds again just fine. So, I have to assume that cmake is attempting to import the pip packages, and is failing to do so due to permissions issues (although the packages were installed with `pip install --user` and we are building Emscripten while logged in as that same user).

I have already removed all pip-installed packages that are not dependencies of SciPy. The only other troubleshooting step that I can think of this point is to install the packages at a system level (again, assuming that this is somehow a permissions issue).

Finally, to my questions,
(1) Is it CMake that is attempting to pull in pip-installed modules at compilation time, or is there some way to set this in Emscripten (any version)?
(2) Is the issue that I have described above a known issue when building Emscripten (any version)?
(3) Following from (2), after what version (if any) is the above no longer an issue?

**Comment by kripken** [comment]
Strange. On the one hand, `u'MipsCodeGen' has invalid reference u';LOCALMOD' (via 'required library')` suggests to me that there is a local modification of the mips code in LLVM - perhaps a merge went badly. Searching for `LOCALMOD` under `lib/Target/Mips/`, I don't see anything in emscripten's LLVM. Is it possible your LLVM has a local change there?

On the other hand, I have no idea how this could be connected to pip. My only guess is that LLVM's build system portion that uses Python is somehow confused by pip-installed packages. To check that, I'd see if building upstream LLVM works on your system - if you see the same error, then it's an upstream LLVM bug we should report. (If you don't see it, then it's possible it used to be a bug but was fixed since, if so, we should try to find and backport it.)

**Comment by TidbitSoftware** [comment]
Okay so it turns out the issue is with one of, or some combination of, the following packages (though I do not currently have the time to figure it out),
- ipython (v5.0)
- jupyter
- pandas 
- sympy

Initially, I followed the instructions from [scipy.org](https://www.scipy.org/install.html), and used the following line to install the SciPy and dependencies via pip (note: modified to use version 5.0 of ipython, as this is the version that is supported by Python 2.7),
```
python -m pip install --user numpy scipy matplotlib ipython==5.0 jupyter pandas sympy nose
```

By uninstalling all packages then modifying the above to,
```
python -m pip install --user numpy scipy matplotlib nose
```
both the Python- and Emscripten-based projects that I described in my original post were able to build successfully on the same machine.

I am going to close this issue, but hope that someone else finds it helpful in some way. Cheers.
