### ISSUE TITLE
Emterpreter Sleep Forever & Resume

### ISSUE THREAD

**Issue by AjayP13** [kripken/emscripten#7618]
I'm running code compiled for the Emterpreter and have two questions that I can't find the answer to in the documentation.

1. Is there a way to sleep indefinitely? I can use `emscripten_sleep(<VERY LARGE NUMBER>)` as an alternative, but is there anything that truly means forever?

2. Once I have started a long sleep, is there a way in JavaScript to restart the Emterpreter? `Module.XX.resumeEmterpreter()` (?)

**Comment by kripken** [comment]
No infinite sleep option currently, but it would be easy to add one. See the source code here:

https://github.com/kripken/emscripten/blob/incoming/src/library_async.js#L392

We just call setTimeout there, but perhaps if the input were `-1` we could say that means forever. And for resuming, also see that source code - you basically need to call that `resume` method. One option might be to assign `resume` to `Module.resume` so that outside code can call it when it's ready.

**Comment by AjayP13** [comment]
Thanks, that's helpful. Since this requires modifications to the core library, I solved this on my end by monkey patching the `setTimeout` function in a closure (in case anyone needs this functionality in the future and sees this issue).
