### ISSUE TITLE
memcpy from musl is 1.4K, 3x larger than handwritten one 

### ISSUE THREAD

**Issue by kripken** [kripken/emscripten#7639]
We should check if it's worth the extra size. The extra 1K is a big chunk of the total wasm size (around 5%) in small codebases.

**Comment by juj** [comment]
Did we have memcpy and memset opcodes yet in Wasm? Those would be fastest if available? I don't doubt musl would be bad for native, it is probably tuned quite heavily - but for asm.js and/or wasm, I tend to believe our versions would be tuned better (since we can tune for our case, which musl would not have had the visibility to do).

**Comment by kripken** [comment]
Looks like memcpy etc. in wasm, bulk memory ops, are in stage 2, so not ready yet, https://github.com/WebAssembly/proposals

SIMD might also influence this, but also is not ready yet.
